/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AgentData,
  AgentDataRequest,
  CreateThreadAndRunRequest,
  FilterAgentsRequest,
  HTTPValidationError,
  RegistryEntry,
} from '../models/index';
import {
    AgentDataFromJSON,
    AgentDataToJSON,
    AgentDataRequestFromJSON,
    AgentDataRequestToJSON,
    CreateThreadAndRunRequestFromJSON,
    CreateThreadAndRunRequestToJSON,
    FilterAgentsRequestFromJSON,
    FilterAgentsRequestToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    RegistryEntryFromJSON,
    RegistryEntryToJSON,
} from '../models/index';

export interface FindAgentsV1FindAgentsPostRequest {
    filterAgentsRequest: FilterAgentsRequest;
}

export interface GetAgentDataByKeyForAuthorV1AgentDataAdminNamespaceNameKeyGetRequest {
    namespace: string;
    name: string;
    key: string;
}

export interface GetAgentDataByKeyV1AgentDataKeyGetRequest {
    key: string;
}

export interface GetAgentDataForAuthorV1AgentDataAdminNamespaceNameGetRequest {
    namespace: string;
    name: string;
}

export interface RunAgentV1AgentRunsPostRequest {
    createThreadAndRunRequest: CreateThreadAndRunRequest;
}

export interface RunAgentV1ThreadsRunsPostRequest {
    createThreadAndRunRequest: CreateThreadAndRunRequest;
}

export interface SaveAgentDataV1AgentDataPostRequest {
    agentDataRequest: AgentDataRequest;
}

/**
 * 
 */
export class AgentsAssistantsApi extends runtime.BaseAPI {

    /**
     * Find agents based on various parameters.
     * Find Agents
     */
    async findAgentsV1FindAgentsPostRaw(requestParameters: FindAgentsV1FindAgentsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<RegistryEntry>>> {
        if (requestParameters['filterAgentsRequest'] == null) {
            throw new runtime.RequiredError(
                'filterAgentsRequest',
                'Required parameter "filterAgentsRequest" was null or undefined when calling findAgentsV1FindAgentsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/find_agents`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FilterAgentsRequestToJSON(requestParameters['filterAgentsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RegistryEntryFromJSON));
    }

    /**
     * Find agents based on various parameters.
     * Find Agents
     */
    async findAgentsV1FindAgentsPost(requestParameters: FindAgentsV1FindAgentsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<RegistryEntry>> {
        const response = await this.findAgentsV1FindAgentsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Agent Data By Key For Author
     */
    async getAgentDataByKeyForAuthorV1AgentDataAdminNamespaceNameKeyGetRaw(requestParameters: GetAgentDataByKeyForAuthorV1AgentDataAdminNamespaceNameKeyGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgentData>> {
        if (requestParameters['namespace'] == null) {
            throw new runtime.RequiredError(
                'namespace',
                'Required parameter "namespace" was null or undefined when calling getAgentDataByKeyForAuthorV1AgentDataAdminNamespaceNameKeyGet().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling getAgentDataByKeyForAuthorV1AgentDataAdminNamespaceNameKeyGet().'
            );
        }

        if (requestParameters['key'] == null) {
            throw new runtime.RequiredError(
                'key',
                'Required parameter "key" was null or undefined when calling getAgentDataByKeyForAuthorV1AgentDataAdminNamespaceNameKeyGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/agent_data_admin/{namespace}/{name}/{key}`.replace(`{${"namespace"}}`, encodeURIComponent(String(requestParameters['namespace']))).replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))).replace(`{${"key"}}`, encodeURIComponent(String(requestParameters['key']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgentDataFromJSON(jsonValue));
    }

    /**
     * Get Agent Data By Key For Author
     */
    async getAgentDataByKeyForAuthorV1AgentDataAdminNamespaceNameKeyGet(requestParameters: GetAgentDataByKeyForAuthorV1AgentDataAdminNamespaceNameKeyGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgentData> {
        const response = await this.getAgentDataByKeyForAuthorV1AgentDataAdminNamespaceNameKeyGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Agent Data By Key
     */
    async getAgentDataByKeyV1AgentDataKeyGetRaw(requestParameters: GetAgentDataByKeyV1AgentDataKeyGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgentData>> {
        if (requestParameters['key'] == null) {
            throw new runtime.RequiredError(
                'key',
                'Required parameter "key" was null or undefined when calling getAgentDataByKeyV1AgentDataKeyGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/agent_data/{key}`.replace(`{${"key"}}`, encodeURIComponent(String(requestParameters['key']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgentDataFromJSON(jsonValue));
    }

    /**
     * Get Agent Data By Key
     */
    async getAgentDataByKeyV1AgentDataKeyGet(requestParameters: GetAgentDataByKeyV1AgentDataKeyGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgentData> {
        const response = await this.getAgentDataByKeyV1AgentDataKeyGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Agent Data For Author
     */
    async getAgentDataForAuthorV1AgentDataAdminNamespaceNameGetRaw(requestParameters: GetAgentDataForAuthorV1AgentDataAdminNamespaceNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AgentData>>> {
        if (requestParameters['namespace'] == null) {
            throw new runtime.RequiredError(
                'namespace',
                'Required parameter "namespace" was null or undefined when calling getAgentDataForAuthorV1AgentDataAdminNamespaceNameGet().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling getAgentDataForAuthorV1AgentDataAdminNamespaceNameGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/agent_data_admin/{namespace}/{name}`.replace(`{${"namespace"}}`, encodeURIComponent(String(requestParameters['namespace']))).replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AgentDataFromJSON));
    }

    /**
     * Get Agent Data For Author
     */
    async getAgentDataForAuthorV1AgentDataAdminNamespaceNameGet(requestParameters: GetAgentDataForAuthorV1AgentDataAdminNamespaceNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AgentData>> {
        const response = await this.getAgentDataForAuthorV1AgentDataAdminNamespaceNameGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Agent Data
     */
    async getAgentDataV1AgentDataGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AgentData>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/agent_data`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AgentDataFromJSON));
    }

    /**
     * Get Agent Data
     */
    async getAgentDataV1AgentDataGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AgentData>> {
        const response = await this.getAgentDataV1AgentDataGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Run an agent against an existing or a new thread.  Returns the ID of the new thread resulting from the run.
     * Run Agent
     */
    async runAgentV1AgentRunsPostRaw(requestParameters: RunAgentV1AgentRunsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['createThreadAndRunRequest'] == null) {
            throw new runtime.RequiredError(
                'createThreadAndRunRequest',
                'Required parameter "createThreadAndRunRequest" was null or undefined when calling runAgentV1AgentRunsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/agent/runs`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateThreadAndRunRequestToJSON(requestParameters['createThreadAndRunRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Run an agent against an existing or a new thread.  Returns the ID of the new thread resulting from the run.
     * Run Agent
     */
    async runAgentV1AgentRunsPost(requestParameters: RunAgentV1AgentRunsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.runAgentV1AgentRunsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Run an agent against an existing or a new thread.  Returns the ID of the new thread resulting from the run.
     * Run Agent
     */
    async runAgentV1ThreadsRunsPostRaw(requestParameters: RunAgentV1ThreadsRunsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['createThreadAndRunRequest'] == null) {
            throw new runtime.RequiredError(
                'createThreadAndRunRequest',
                'Required parameter "createThreadAndRunRequest" was null or undefined when calling runAgentV1ThreadsRunsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/threads/runs`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateThreadAndRunRequestToJSON(requestParameters['createThreadAndRunRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Run an agent against an existing or a new thread.  Returns the ID of the new thread resulting from the run.
     * Run Agent
     */
    async runAgentV1ThreadsRunsPost(requestParameters: RunAgentV1ThreadsRunsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.runAgentV1ThreadsRunsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Save Agent Data
     */
    async saveAgentDataV1AgentDataPostRaw(requestParameters: SaveAgentDataV1AgentDataPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgentData>> {
        if (requestParameters['agentDataRequest'] == null) {
            throw new runtime.RequiredError(
                'agentDataRequest',
                'Required parameter "agentDataRequest" was null or undefined when calling saveAgentDataV1AgentDataPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/agent_data`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AgentDataRequestToJSON(requestParameters['agentDataRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgentDataFromJSON(jsonValue));
    }

    /**
     * Save Agent Data
     */
    async saveAgentDataV1AgentDataPost(requestParameters: SaveAgentDataV1AgentDataPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgentData> {
        const response = await this.saveAgentDataV1AgentDataPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
