/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateThreadAndRunRequest,
  HTTPValidationError,
} from '../models/index';
import {
    CreateThreadAndRunRequestFromJSON,
    CreateThreadAndRunRequestToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface RunAgentV1AgentRunsPostRequest {
    createThreadAndRunRequest: CreateThreadAndRunRequest;
}

export interface RunAgentV1ThreadsRunsPostRequest {
    createThreadAndRunRequest: CreateThreadAndRunRequest;
}

/**
 * 
 */
export class AssistantsApi extends runtime.BaseAPI {

    /**
     * Run an agent against an existing or a new thread.  Returns the ID of the new thread resulting from the run.
     * Run Agent
     */
    async runAgentV1AgentRunsPostRaw(requestParameters: RunAgentV1AgentRunsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['createThreadAndRunRequest'] == null) {
            throw new runtime.RequiredError(
                'createThreadAndRunRequest',
                'Required parameter "createThreadAndRunRequest" was null or undefined when calling runAgentV1AgentRunsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/agent/runs`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateThreadAndRunRequestToJSON(requestParameters['createThreadAndRunRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Run an agent against an existing or a new thread.  Returns the ID of the new thread resulting from the run.
     * Run Agent
     */
    async runAgentV1AgentRunsPost(requestParameters: RunAgentV1AgentRunsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.runAgentV1AgentRunsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Run an agent against an existing or a new thread.  Returns the ID of the new thread resulting from the run.
     * Run Agent
     */
    async runAgentV1ThreadsRunsPostRaw(requestParameters: RunAgentV1ThreadsRunsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['createThreadAndRunRequest'] == null) {
            throw new runtime.RequiredError(
                'createThreadAndRunRequest',
                'Required parameter "createThreadAndRunRequest" was null or undefined when calling runAgentV1ThreadsRunsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/threads/runs`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateThreadAndRunRequestToJSON(requestParameters['createThreadAndRunRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Run an agent against an existing or a new thread.  Returns the ID of the new thread resulting from the run.
     * Run Agent
     */
    async runAgentV1ThreadsRunsPost(requestParameters: RunAgentV1ThreadsRunsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.runAgentV1ThreadsRunsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
