/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Delegation,
  HTTPValidationError,
} from '../models/index';
import {
    DelegationFromJSON,
    DelegationToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface DelegateV1DelegationDelegatePostRequest {
    delegateAccountId: string;
    expiresAt: Date;
}

export interface RevokeDelegationV1DelegationRevokeDelegationPostRequest {
    delegateAccountId: string;
}

/**
 * 
 */
export class DelegationApi extends runtime.BaseAPI {

    /**
     * Delegate
     */
    async delegateV1DelegationDelegatePostRaw(requestParameters: DelegateV1DelegationDelegatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['delegateAccountId'] == null) {
            throw new runtime.RequiredError(
                'delegateAccountId',
                'Required parameter "delegateAccountId" was null or undefined when calling delegateV1DelegationDelegatePost().'
            );
        }

        if (requestParameters['expiresAt'] == null) {
            throw new runtime.RequiredError(
                'expiresAt',
                'Required parameter "expiresAt" was null or undefined when calling delegateV1DelegationDelegatePost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['delegateAccountId'] != null) {
            queryParameters['delegate_account_id'] = requestParameters['delegateAccountId'];
        }

        if (requestParameters['expiresAt'] != null) {
            queryParameters['expires_at'] = (requestParameters['expiresAt'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/delegation/delegate`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delegate
     */
    async delegateV1DelegationDelegatePost(requestParameters: DelegateV1DelegationDelegatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.delegateV1DelegationDelegatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Delegation
     */
    async listDelegationV1DelegationListDelegationsPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Delegation>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/delegation/list_delegations`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DelegationFromJSON));
    }

    /**
     * List Delegation
     */
    async listDelegationV1DelegationListDelegationsPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Delegation>> {
        const response = await this.listDelegationV1DelegationListDelegationsPostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Revoke Delegation
     */
    async revokeDelegationV1DelegationRevokeDelegationPostRaw(requestParameters: RevokeDelegationV1DelegationRevokeDelegationPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['delegateAccountId'] == null) {
            throw new runtime.RequiredError(
                'delegateAccountId',
                'Required parameter "delegateAccountId" was null or undefined when calling revokeDelegationV1DelegationRevokeDelegationPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['delegateAccountId'] != null) {
            queryParameters['delegate_account_id'] = requestParameters['delegateAccountId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/delegation/revoke_delegation`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Revoke Delegation
     */
    async revokeDelegationV1DelegationRevokeDelegationPost(requestParameters: RevokeDelegationV1DelegationRevokeDelegationPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.revokeDelegationV1DelegationRevokeDelegationPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
