/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  Log,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    LogFromJSON,
    LogToJSON,
} from '../models/index';

export interface AddLogV1LogsAddLogPostRequest {
    target: string;
    body: object;
}

export interface GetLogsV1LogsGetLogsGetRequest {
    target: string;
    afterId: number;
    limit: number;
}

/**
 * 
 */
export class LogsApi extends runtime.BaseAPI {

    /**
     * Add Log
     */
    async addLogV1LogsAddLogPostRaw(requestParameters: AddLogV1LogsAddLogPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Log>> {
        if (requestParameters['target'] == null) {
            throw new runtime.RequiredError(
                'target',
                'Required parameter "target" was null or undefined when calling addLogV1LogsAddLogPost().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling addLogV1LogsAddLogPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['target'] != null) {
            queryParameters['target'] = requestParameters['target'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/logs/add_log`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LogFromJSON(jsonValue));
    }

    /**
     * Add Log
     */
    async addLogV1LogsAddLogPost(requestParameters: AddLogV1LogsAddLogPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Log> {
        const response = await this.addLogV1LogsAddLogPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Logs
     */
    async getLogsV1LogsGetLogsGetRaw(requestParameters: GetLogsV1LogsGetLogsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Log>>> {
        if (requestParameters['target'] == null) {
            throw new runtime.RequiredError(
                'target',
                'Required parameter "target" was null or undefined when calling getLogsV1LogsGetLogsGet().'
            );
        }

        if (requestParameters['afterId'] == null) {
            throw new runtime.RequiredError(
                'afterId',
                'Required parameter "afterId" was null or undefined when calling getLogsV1LogsGetLogsGet().'
            );
        }

        if (requestParameters['limit'] == null) {
            throw new runtime.RequiredError(
                'limit',
                'Required parameter "limit" was null or undefined when calling getLogsV1LogsGetLogsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['target'] != null) {
            queryParameters['target'] = requestParameters['target'];
        }

        if (requestParameters['afterId'] != null) {
            queryParameters['after_id'] = requestParameters['afterId'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/logs/get_logs`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(LogFromJSON));
    }

    /**
     * Get Logs
     */
    async getLogsV1LogsGetLogsGet(requestParameters: GetLogsV1LogsGetLogsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Log>> {
        const response = await this.getLogsV1LogsGetLogsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
