/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BodyDownloadFileV1RegistryDownloadFilePost,
  BodyDownloadMetadataV1RegistryDownloadMetadataPost,
  BodyForkEntryV1RegistryForkPost,
  BodyListFilesV1RegistryListFilesPost,
  BodyUploadMetadataV1RegistryUploadMetadataPost,
  EntryInformation,
  EntryMetadata,
  Filename,
  ForkResult,
  HTTPValidationError,
} from '../models/index';
import {
    BodyDownloadFileV1RegistryDownloadFilePostFromJSON,
    BodyDownloadFileV1RegistryDownloadFilePostToJSON,
    BodyDownloadMetadataV1RegistryDownloadMetadataPostFromJSON,
    BodyDownloadMetadataV1RegistryDownloadMetadataPostToJSON,
    BodyForkEntryV1RegistryForkPostFromJSON,
    BodyForkEntryV1RegistryForkPostToJSON,
    BodyListFilesV1RegistryListFilesPostFromJSON,
    BodyListFilesV1RegistryListFilesPostToJSON,
    BodyUploadMetadataV1RegistryUploadMetadataPostFromJSON,
    BodyUploadMetadataV1RegistryUploadMetadataPostToJSON,
    EntryInformationFromJSON,
    EntryInformationToJSON,
    EntryMetadataFromJSON,
    EntryMetadataToJSON,
    FilenameFromJSON,
    FilenameToJSON,
    ForkResultFromJSON,
    ForkResultToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface DownloadFileV1RegistryDownloadFilePostRequest {
    bodyDownloadFileV1RegistryDownloadFilePost: BodyDownloadFileV1RegistryDownloadFilePost;
}

export interface DownloadMetadataV1RegistryDownloadMetadataPostRequest {
    bodyDownloadMetadataV1RegistryDownloadMetadataPost: BodyDownloadMetadataV1RegistryDownloadMetadataPost;
}

export interface ForkEntryV1RegistryForkPostRequest {
    bodyForkEntryV1RegistryForkPost: BodyForkEntryV1RegistryForkPost;
}

export interface ListEntriesV1RegistryListEntriesPostRequest {
    namespace?: string;
    category?: string;
    tags?: string;
    total?: number;
    offset?: number;
    showHidden?: boolean;
    showLatestVersion?: boolean;
    starredBy?: string;
    starPointOfView?: string;
    forkOfName?: string;
    forkOfNamespace?: string;
}

export interface ListFilesV1RegistryListFilesPostRequest {
    bodyListFilesV1RegistryListFilesPost: BodyListFilesV1RegistryListFilesPost;
}

export interface UploadFileV1RegistryUploadFilePostRequest {
    path: string;
    file: Blob;
    namespace: string;
    name: string;
    version: string;
}

export interface UploadMetadataV1RegistryUploadMetadataPostRequest {
    bodyUploadMetadataV1RegistryUploadMetadataPost: BodyUploadMetadataV1RegistryUploadMetadataPost;
}

/**
 * 
 */
export class RegistryApi extends runtime.BaseAPI {

    /**
     * Download File
     */
    async downloadFileV1RegistryDownloadFilePostRaw(requestParameters: DownloadFileV1RegistryDownloadFilePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['bodyDownloadFileV1RegistryDownloadFilePost'] == null) {
            throw new runtime.RequiredError(
                'bodyDownloadFileV1RegistryDownloadFilePost',
                'Required parameter "bodyDownloadFileV1RegistryDownloadFilePost" was null or undefined when calling downloadFileV1RegistryDownloadFilePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/registry/download_file`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BodyDownloadFileV1RegistryDownloadFilePostToJSON(requestParameters['bodyDownloadFileV1RegistryDownloadFilePost']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Download File
     */
    async downloadFileV1RegistryDownloadFilePost(requestParameters: DownloadFileV1RegistryDownloadFilePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.downloadFileV1RegistryDownloadFilePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Download Metadata
     */
    async downloadMetadataV1RegistryDownloadMetadataPostRaw(requestParameters: DownloadMetadataV1RegistryDownloadMetadataPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntryMetadata>> {
        if (requestParameters['bodyDownloadMetadataV1RegistryDownloadMetadataPost'] == null) {
            throw new runtime.RequiredError(
                'bodyDownloadMetadataV1RegistryDownloadMetadataPost',
                'Required parameter "bodyDownloadMetadataV1RegistryDownloadMetadataPost" was null or undefined when calling downloadMetadataV1RegistryDownloadMetadataPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/registry/download_metadata`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BodyDownloadMetadataV1RegistryDownloadMetadataPostToJSON(requestParameters['bodyDownloadMetadataV1RegistryDownloadMetadataPost']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntryMetadataFromJSON(jsonValue));
    }

    /**
     * Download Metadata
     */
    async downloadMetadataV1RegistryDownloadMetadataPost(requestParameters: DownloadMetadataV1RegistryDownloadMetadataPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntryMetadata> {
        const response = await this.downloadMetadataV1RegistryDownloadMetadataPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Fork an existing registry entry to the current user\'s namespace.
     * Fork Entry
     */
    async forkEntryV1RegistryForkPostRaw(requestParameters: ForkEntryV1RegistryForkPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ForkResult>> {
        if (requestParameters['bodyForkEntryV1RegistryForkPost'] == null) {
            throw new runtime.RequiredError(
                'bodyForkEntryV1RegistryForkPost',
                'Required parameter "bodyForkEntryV1RegistryForkPost" was null or undefined when calling forkEntryV1RegistryForkPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/registry/fork`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BodyForkEntryV1RegistryForkPostToJSON(requestParameters['bodyForkEntryV1RegistryForkPost']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ForkResultFromJSON(jsonValue));
    }

    /**
     * Fork an existing registry entry to the current user\'s namespace.
     * Fork Entry
     */
    async forkEntryV1RegistryForkPost(requestParameters: ForkEntryV1RegistryForkPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ForkResult> {
        const response = await this.forkEntryV1RegistryForkPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Entries
     */
    async listEntriesV1RegistryListEntriesPostRaw(requestParameters: ListEntriesV1RegistryListEntriesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<EntryInformation>>> {
        const queryParameters: any = {};

        if (requestParameters['namespace'] != null) {
            queryParameters['namespace'] = requestParameters['namespace'];
        }

        if (requestParameters['category'] != null) {
            queryParameters['category'] = requestParameters['category'];
        }

        if (requestParameters['tags'] != null) {
            queryParameters['tags'] = requestParameters['tags'];
        }

        if (requestParameters['total'] != null) {
            queryParameters['total'] = requestParameters['total'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['showHidden'] != null) {
            queryParameters['show_hidden'] = requestParameters['showHidden'];
        }

        if (requestParameters['showLatestVersion'] != null) {
            queryParameters['show_latest_version'] = requestParameters['showLatestVersion'];
        }

        if (requestParameters['starredBy'] != null) {
            queryParameters['starred_by'] = requestParameters['starredBy'];
        }

        if (requestParameters['starPointOfView'] != null) {
            queryParameters['star_point_of_view'] = requestParameters['starPointOfView'];
        }

        if (requestParameters['forkOfName'] != null) {
            queryParameters['fork_of_name'] = requestParameters['forkOfName'];
        }

        if (requestParameters['forkOfNamespace'] != null) {
            queryParameters['fork_of_namespace'] = requestParameters['forkOfNamespace'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v1/registry/list_entries`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(EntryInformationFromJSON));
    }

    /**
     * List Entries
     */
    async listEntriesV1RegistryListEntriesPost(requestParameters: ListEntriesV1RegistryListEntriesPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<EntryInformation>> {
        const response = await this.listEntriesV1RegistryListEntriesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Lists all files that belong to an entry.
     * List Files
     */
    async listFilesV1RegistryListFilesPostRaw(requestParameters: ListFilesV1RegistryListFilesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Filename>>> {
        if (requestParameters['bodyListFilesV1RegistryListFilesPost'] == null) {
            throw new runtime.RequiredError(
                'bodyListFilesV1RegistryListFilesPost',
                'Required parameter "bodyListFilesV1RegistryListFilesPost" was null or undefined when calling listFilesV1RegistryListFilesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/registry/list_files`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BodyListFilesV1RegistryListFilesPostToJSON(requestParameters['bodyListFilesV1RegistryListFilesPost']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FilenameFromJSON));
    }

    /**
     * Lists all files that belong to an entry.
     * List Files
     */
    async listFilesV1RegistryListFilesPost(requestParameters: ListFilesV1RegistryListFilesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Filename>> {
        const response = await this.listFilesV1RegistryListFilesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Upload File
     */
    async uploadFileV1RegistryUploadFilePostRaw(requestParameters: UploadFileV1RegistryUploadFilePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['path'] == null) {
            throw new runtime.RequiredError(
                'path',
                'Required parameter "path" was null or undefined when calling uploadFileV1RegistryUploadFilePost().'
            );
        }

        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling uploadFileV1RegistryUploadFilePost().'
            );
        }

        if (requestParameters['namespace'] == null) {
            throw new runtime.RequiredError(
                'namespace',
                'Required parameter "namespace" was null or undefined when calling uploadFileV1RegistryUploadFilePost().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling uploadFileV1RegistryUploadFilePost().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling uploadFileV1RegistryUploadFilePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['path'] != null) {
            formParams.append('path', requestParameters['path'] as any);
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        if (requestParameters['namespace'] != null) {
            formParams.append('namespace', requestParameters['namespace'] as any);
        }

        if (requestParameters['name'] != null) {
            formParams.append('name', requestParameters['name'] as any);
        }

        if (requestParameters['version'] != null) {
            formParams.append('version', requestParameters['version'] as any);
        }

        const response = await this.request({
            path: `/v1/registry/upload_file`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Upload File
     */
    async uploadFileV1RegistryUploadFilePost(requestParameters: UploadFileV1RegistryUploadFilePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.uploadFileV1RegistryUploadFilePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Upload Metadata
     */
    async uploadMetadataV1RegistryUploadMetadataPostRaw(requestParameters: UploadMetadataV1RegistryUploadMetadataPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['bodyUploadMetadataV1RegistryUploadMetadataPost'] == null) {
            throw new runtime.RequiredError(
                'bodyUploadMetadataV1RegistryUploadMetadataPost',
                'Required parameter "bodyUploadMetadataV1RegistryUploadMetadataPost" was null or undefined when calling uploadMetadataV1RegistryUploadMetadataPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/registry/upload_metadata`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BodyUploadMetadataV1RegistryUploadMetadataPostToJSON(requestParameters['bodyUploadMetadataV1RegistryUploadMetadataPost']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Upload Metadata
     */
    async uploadMetadataV1RegistryUploadMetadataPost(requestParameters: UploadMetadataV1RegistryUploadMetadataPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.uploadMetadataV1RegistryUploadMetadataPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
