/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateScheduleRunRequest,
  HTTPValidationError,
} from '../models/index';
import {
    CreateScheduleRunRequestFromJSON,
    CreateScheduleRunRequestToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface ScheduleRunV1ScheduleRunPostRequest {
    createScheduleRunRequest: CreateScheduleRunRequest;
}

/**
 * 
 */
export class RunScheduleApi extends runtime.BaseAPI {

    /**
     * Endpoint to schedule a new run.
     * Schedule Run
     */
    async scheduleRunV1ScheduleRunPostRaw(requestParameters: ScheduleRunV1ScheduleRunPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['createScheduleRunRequest'] == null) {
            throw new runtime.RequiredError(
                'createScheduleRunRequest',
                'Required parameter "createScheduleRunRequest" was null or undefined when calling scheduleRunV1ScheduleRunPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/schedule_run`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateScheduleRunRequestToJSON(requestParameters['createScheduleRunRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Endpoint to schedule a new run.
     * Schedule Run
     */
    async scheduleRunV1ScheduleRunPost(requestParameters: ScheduleRunV1ScheduleRunPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.scheduleRunV1ScheduleRunPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
