/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  ListMessagesResponse,
  MessageCreateParams,
  MessageOutput,
  MessageUpdateParams,
  Run,
  RunCreateParamsBase,
  RunUpdateParams,
  SubthreadCreateParams,
  Thread,
  ThreadCreateParams,
  ThreadDeletionStatus,
  ThreadForkResponse,
  ThreadUpdateParams,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ListMessagesResponseFromJSON,
    ListMessagesResponseToJSON,
    MessageCreateParamsFromJSON,
    MessageCreateParamsToJSON,
    MessageOutputFromJSON,
    MessageOutputToJSON,
    MessageUpdateParamsFromJSON,
    MessageUpdateParamsToJSON,
    RunFromJSON,
    RunToJSON,
    RunCreateParamsBaseFromJSON,
    RunCreateParamsBaseToJSON,
    RunUpdateParamsFromJSON,
    RunUpdateParamsToJSON,
    SubthreadCreateParamsFromJSON,
    SubthreadCreateParamsToJSON,
    ThreadFromJSON,
    ThreadToJSON,
    ThreadCreateParamsFromJSON,
    ThreadCreateParamsToJSON,
    ThreadDeletionStatusFromJSON,
    ThreadDeletionStatusToJSON,
    ThreadForkResponseFromJSON,
    ThreadForkResponseToJSON,
    ThreadUpdateParamsFromJSON,
    ThreadUpdateParamsToJSON,
} from '../models/index';

export interface CreateMessageV1ThreadsThreadIdMessagesPostRequest {
    threadId: string;
    messageCreateParams: MessageCreateParams;
}

export interface CreateRunV1ThreadsThreadIdRunsPostRequest {
    threadId: string;
    runCreateParamsBase: RunCreateParamsBase;
}

export interface CreateSubthreadV1ThreadsParentIdSubthreadPostRequest {
    parentId: string;
    subthreadCreateParams: SubthreadCreateParams;
}

export interface CreateThreadV1ThreadsPostRequest {
    threadCreateParams: ThreadCreateParams;
}

export interface DeleteThreadV1ThreadsThreadIdDeleteRequest {
    threadId: string;
}

export interface ForkThreadV1ThreadsThreadIdForkPostRequest {
    threadId: string;
}

export interface GetRunV1ThreadsThreadIdRunsRunIdGetRequest {
    threadId: string;
    runId: string;
}

export interface GetThreadV1ThreadsThreadIdGetRequest {
    threadId: string;
}

export interface ListMessagesV1ThreadsThreadIdMessagesGetRequest {
    threadId: string;
    after?: string;
    before?: string;
    limit?: number;
    order?: ListMessagesV1ThreadsThreadIdMessagesGetOrderEnum;
    runId?: string;
    includeSubthreads?: boolean;
}

export interface ListThreadsV1ThreadsGetRequest {
    includeSubthreads?: boolean | null;
}

export interface ModifyMessageV1ThreadsThreadIdMessagesMessageIdPatchRequest {
    messageId: string;
    messageUpdateParams: MessageUpdateParams;
}

export interface ThreadSubscribeV1ThreadsThreadIdStreamRunIdGetRequest {
    threadId: string;
    runId: string | null;
}

export interface UpdateRunV1ThreadsThreadIdRunsRunIdPostRequest {
    threadId: string;
    runId: string;
    runUpdateParams: RunUpdateParams;
}

export interface UpdateThreadV1ThreadsThreadIdPostRequest {
    threadId: string;
    threadUpdateParams: ThreadUpdateParams;
}

/**
 * 
 */
export class ThreadsApi extends runtime.BaseAPI {

    /**
     * Create Message
     */
    async createMessageV1ThreadsThreadIdMessagesPostRaw(requestParameters: CreateMessageV1ThreadsThreadIdMessagesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageOutput>> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling createMessageV1ThreadsThreadIdMessagesPost().'
            );
        }

        if (requestParameters['messageCreateParams'] == null) {
            throw new runtime.RequiredError(
                'messageCreateParams',
                'Required parameter "messageCreateParams" was null or undefined when calling createMessageV1ThreadsThreadIdMessagesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/threads/{thread_id}/messages`.replace(`{${"thread_id"}}`, encodeURIComponent(String(requestParameters['threadId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MessageCreateParamsToJSON(requestParameters['messageCreateParams']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageOutputFromJSON(jsonValue));
    }

    /**
     * Create Message
     */
    async createMessageV1ThreadsThreadIdMessagesPost(requestParameters: CreateMessageV1ThreadsThreadIdMessagesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageOutput> {
        const response = await this.createMessageV1ThreadsThreadIdMessagesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create Run
     */
    async createRunV1ThreadsThreadIdRunsPostRaw(requestParameters: CreateRunV1ThreadsThreadIdRunsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling createRunV1ThreadsThreadIdRunsPost().'
            );
        }

        if (requestParameters['runCreateParamsBase'] == null) {
            throw new runtime.RequiredError(
                'runCreateParamsBase',
                'Required parameter "runCreateParamsBase" was null or undefined when calling createRunV1ThreadsThreadIdRunsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/threads/{thread_id}/runs`.replace(`{${"thread_id"}}`, encodeURIComponent(String(requestParameters['threadId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RunCreateParamsBaseToJSON(requestParameters['runCreateParamsBase']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Create Run
     */
    async createRunV1ThreadsThreadIdRunsPost(requestParameters: CreateRunV1ThreadsThreadIdRunsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.createRunV1ThreadsThreadIdRunsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create Subthread
     */
    async createSubthreadV1ThreadsParentIdSubthreadPostRaw(requestParameters: CreateSubthreadV1ThreadsParentIdSubthreadPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Thread>> {
        if (requestParameters['parentId'] == null) {
            throw new runtime.RequiredError(
                'parentId',
                'Required parameter "parentId" was null or undefined when calling createSubthreadV1ThreadsParentIdSubthreadPost().'
            );
        }

        if (requestParameters['subthreadCreateParams'] == null) {
            throw new runtime.RequiredError(
                'subthreadCreateParams',
                'Required parameter "subthreadCreateParams" was null or undefined when calling createSubthreadV1ThreadsParentIdSubthreadPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/threads/{parent_id}/subthread`.replace(`{${"parent_id"}}`, encodeURIComponent(String(requestParameters['parentId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SubthreadCreateParamsToJSON(requestParameters['subthreadCreateParams']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ThreadFromJSON(jsonValue));
    }

    /**
     * Create Subthread
     */
    async createSubthreadV1ThreadsParentIdSubthreadPost(requestParameters: CreateSubthreadV1ThreadsParentIdSubthreadPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Thread> {
        const response = await this.createSubthreadV1ThreadsParentIdSubthreadPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create Thread
     */
    async createThreadV1ThreadsPostRaw(requestParameters: CreateThreadV1ThreadsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Thread>> {
        if (requestParameters['threadCreateParams'] == null) {
            throw new runtime.RequiredError(
                'threadCreateParams',
                'Required parameter "threadCreateParams" was null or undefined when calling createThreadV1ThreadsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/threads`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ThreadCreateParamsToJSON(requestParameters['threadCreateParams']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ThreadFromJSON(jsonValue));
    }

    /**
     * Create Thread
     */
    async createThreadV1ThreadsPost(requestParameters: CreateThreadV1ThreadsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Thread> {
        const response = await this.createThreadV1ThreadsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Thread
     */
    async deleteThreadV1ThreadsThreadIdDeleteRaw(requestParameters: DeleteThreadV1ThreadsThreadIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ThreadDeletionStatus>> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling deleteThreadV1ThreadsThreadIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/threads/{thread_id}`.replace(`{${"thread_id"}}`, encodeURIComponent(String(requestParameters['threadId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ThreadDeletionStatusFromJSON(jsonValue));
    }

    /**
     * Delete Thread
     */
    async deleteThreadV1ThreadsThreadIdDelete(requestParameters: DeleteThreadV1ThreadsThreadIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ThreadDeletionStatus> {
        const response = await this.deleteThreadV1ThreadsThreadIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Fork Thread
     */
    async forkThreadV1ThreadsThreadIdForkPostRaw(requestParameters: ForkThreadV1ThreadsThreadIdForkPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ThreadForkResponse>> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling forkThreadV1ThreadsThreadIdForkPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/threads/{thread_id}/fork`.replace(`{${"thread_id"}}`, encodeURIComponent(String(requestParameters['threadId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ThreadForkResponseFromJSON(jsonValue));
    }

    /**
     * Fork Thread
     */
    async forkThreadV1ThreadsThreadIdForkPost(requestParameters: ForkThreadV1ThreadsThreadIdForkPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ThreadForkResponse> {
        const response = await this.forkThreadV1ThreadsThreadIdForkPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get details of a specific run for a thread.
     * Get Run
     */
    async getRunV1ThreadsThreadIdRunsRunIdGetRaw(requestParameters: GetRunV1ThreadsThreadIdRunsRunIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Run>> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling getRunV1ThreadsThreadIdRunsRunIdGet().'
            );
        }

        if (requestParameters['runId'] == null) {
            throw new runtime.RequiredError(
                'runId',
                'Required parameter "runId" was null or undefined when calling getRunV1ThreadsThreadIdRunsRunIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/threads/{thread_id}/runs/{run_id}`.replace(`{${"thread_id"}}`, encodeURIComponent(String(requestParameters['threadId']))).replace(`{${"run_id"}}`, encodeURIComponent(String(requestParameters['runId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RunFromJSON(jsonValue));
    }

    /**
     * Get details of a specific run for a thread.
     * Get Run
     */
    async getRunV1ThreadsThreadIdRunsRunIdGet(requestParameters: GetRunV1ThreadsThreadIdRunsRunIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Run> {
        const response = await this.getRunV1ThreadsThreadIdRunsRunIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Thread
     */
    async getThreadV1ThreadsThreadIdGetRaw(requestParameters: GetThreadV1ThreadsThreadIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Thread>> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling getThreadV1ThreadsThreadIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/threads/{thread_id}`.replace(`{${"thread_id"}}`, encodeURIComponent(String(requestParameters['threadId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ThreadFromJSON(jsonValue));
    }

    /**
     * Get Thread
     */
    async getThreadV1ThreadsThreadIdGet(requestParameters: GetThreadV1ThreadsThreadIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Thread> {
        const response = await this.getThreadV1ThreadsThreadIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Messages
     */
    async listMessagesV1ThreadsThreadIdMessagesGetRaw(requestParameters: ListMessagesV1ThreadsThreadIdMessagesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListMessagesResponse>> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling listMessagesV1ThreadsThreadIdMessagesGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['after'] != null) {
            queryParameters['after'] = requestParameters['after'];
        }

        if (requestParameters['before'] != null) {
            queryParameters['before'] = requestParameters['before'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['order'] != null) {
            queryParameters['order'] = requestParameters['order'];
        }

        if (requestParameters['runId'] != null) {
            queryParameters['run_id'] = requestParameters['runId'];
        }

        if (requestParameters['includeSubthreads'] != null) {
            queryParameters['include_subthreads'] = requestParameters['includeSubthreads'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/threads/{thread_id}/messages`.replace(`{${"thread_id"}}`, encodeURIComponent(String(requestParameters['threadId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListMessagesResponseFromJSON(jsonValue));
    }

    /**
     * List Messages
     */
    async listMessagesV1ThreadsThreadIdMessagesGet(requestParameters: ListMessagesV1ThreadsThreadIdMessagesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListMessagesResponse> {
        const response = await this.listMessagesV1ThreadsThreadIdMessagesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Threads
     */
    async listThreadsV1ThreadsGetRaw(requestParameters: ListThreadsV1ThreadsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Thread>>> {
        const queryParameters: any = {};

        if (requestParameters['includeSubthreads'] != null) {
            queryParameters['include_subthreads'] = requestParameters['includeSubthreads'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/threads`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ThreadFromJSON));
    }

    /**
     * List Threads
     */
    async listThreadsV1ThreadsGet(requestParameters: ListThreadsV1ThreadsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Thread>> {
        const response = await this.listThreadsV1ThreadsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Modify Message
     */
    async modifyMessageV1ThreadsThreadIdMessagesMessageIdPatchRaw(requestParameters: ModifyMessageV1ThreadsThreadIdMessagesMessageIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageOutput>> {
        if (requestParameters['messageId'] == null) {
            throw new runtime.RequiredError(
                'messageId',
                'Required parameter "messageId" was null or undefined when calling modifyMessageV1ThreadsThreadIdMessagesMessageIdPatch().'
            );
        }

        if (requestParameters['messageUpdateParams'] == null) {
            throw new runtime.RequiredError(
                'messageUpdateParams',
                'Required parameter "messageUpdateParams" was null or undefined when calling modifyMessageV1ThreadsThreadIdMessagesMessageIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/threads/{thread_id}/messages/{message_id}`.replace(`{${"message_id"}}`, encodeURIComponent(String(requestParameters['messageId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: MessageUpdateParamsToJSON(requestParameters['messageUpdateParams']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageOutputFromJSON(jsonValue));
    }

    /**
     * Modify Message
     */
    async modifyMessageV1ThreadsThreadIdMessagesMessageIdPatch(requestParameters: ModifyMessageV1ThreadsThreadIdMessagesMessageIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageOutput> {
        const response = await this.modifyMessageV1ThreadsThreadIdMessagesMessageIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Subscribe to deltas for a thread and run (for client channels outside of the run).
     * Thread Subscribe
     */
    async threadSubscribeV1ThreadsThreadIdStreamRunIdGetRaw(requestParameters: ThreadSubscribeV1ThreadsThreadIdStreamRunIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling threadSubscribeV1ThreadsThreadIdStreamRunIdGet().'
            );
        }

        if (requestParameters['runId'] == null) {
            throw new runtime.RequiredError(
                'runId',
                'Required parameter "runId" was null or undefined when calling threadSubscribeV1ThreadsThreadIdStreamRunIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/threads/{thread_id}/stream/{run_id}`.replace(`{${"thread_id"}}`, encodeURIComponent(String(requestParameters['threadId']))).replace(`{${"run_id"}}`, encodeURIComponent(String(requestParameters['runId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Subscribe to deltas for a thread and run (for client channels outside of the run).
     * Thread Subscribe
     */
    async threadSubscribeV1ThreadsThreadIdStreamRunIdGet(requestParameters: ThreadSubscribeV1ThreadsThreadIdStreamRunIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.threadSubscribeV1ThreadsThreadIdStreamRunIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Run
     */
    async updateRunV1ThreadsThreadIdRunsRunIdPostRaw(requestParameters: UpdateRunV1ThreadsThreadIdRunsRunIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Run>> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling updateRunV1ThreadsThreadIdRunsRunIdPost().'
            );
        }

        if (requestParameters['runId'] == null) {
            throw new runtime.RequiredError(
                'runId',
                'Required parameter "runId" was null or undefined when calling updateRunV1ThreadsThreadIdRunsRunIdPost().'
            );
        }

        if (requestParameters['runUpdateParams'] == null) {
            throw new runtime.RequiredError(
                'runUpdateParams',
                'Required parameter "runUpdateParams" was null or undefined when calling updateRunV1ThreadsThreadIdRunsRunIdPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/threads/{thread_id}/runs/{run_id}`.replace(`{${"thread_id"}}`, encodeURIComponent(String(requestParameters['threadId']))).replace(`{${"run_id"}}`, encodeURIComponent(String(requestParameters['runId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RunUpdateParamsToJSON(requestParameters['runUpdateParams']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RunFromJSON(jsonValue));
    }

    /**
     * Update Run
     */
    async updateRunV1ThreadsThreadIdRunsRunIdPost(requestParameters: UpdateRunV1ThreadsThreadIdRunsRunIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Run> {
        const response = await this.updateRunV1ThreadsThreadIdRunsRunIdPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Thread
     */
    async updateThreadV1ThreadsThreadIdPostRaw(requestParameters: UpdateThreadV1ThreadsThreadIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Thread>> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling updateThreadV1ThreadsThreadIdPost().'
            );
        }

        if (requestParameters['threadUpdateParams'] == null) {
            throw new runtime.RequiredError(
                'threadUpdateParams',
                'Required parameter "threadUpdateParams" was null or undefined when calling updateThreadV1ThreadsThreadIdPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/threads/{thread_id}`.replace(`{${"thread_id"}}`, encodeURIComponent(String(requestParameters['threadId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ThreadUpdateParamsToJSON(requestParameters['threadUpdateParams']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ThreadFromJSON(jsonValue));
    }

    /**
     * Update Thread
     */
    async updateThreadV1ThreadsThreadIdPost(requestParameters: UpdateThreadV1ThreadsThreadIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Thread> {
        const response = await this.updateThreadV1ThreadsThreadIdPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ListMessagesV1ThreadsThreadIdMessagesGetOrderEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type ListMessagesV1ThreadsThreadIdMessagesGetOrderEnum = typeof ListMessagesV1ThreadsThreadIdMessagesGetOrderEnum[keyof typeof ListMessagesV1ThreadsThreadIdMessagesGetOrderEnum];
