apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
  namespace: {{.Release.Namespace}}
type: Opaque
data:
  basic-auth-user: '{{ ( .Values.openfaas | default dict ).username | default "YWRtaW4="}}'
  basic-auth-password: '{{ ( .Values.openfaas | default dict ).password | default "YWRtaW4="}}'
