/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdditionalMessageAttachmentToolFileSearch } from './AdditionalMessageAttachmentToolFileSearch';
import {
    AdditionalMessageAttachmentToolFileSearchFromJSON,
    AdditionalMessageAttachmentToolFileSearchFromJSONTyped,
    AdditionalMessageAttachmentToolFileSearchToJSON,
    AdditionalMessageAttachmentToolFileSearchToJSONTyped,
} from './AdditionalMessageAttachmentToolFileSearch';
import type { CodeInterpreterToolParam } from './CodeInterpreterToolParam';
import {
    CodeInterpreterToolParamFromJSON,
    CodeInterpreterToolParamFromJSONTyped,
    CodeInterpreterToolParamToJSON,
    CodeInterpreterToolParamToJSONTyped,
} from './CodeInterpreterToolParam';

/**
 * 
 * @export
 * @interface AdditionalMessageAttachmentToolsInner
 */
export interface AdditionalMessageAttachmentToolsInner {
    /**
     * 
     * @type {string}
     * @memberof AdditionalMessageAttachmentToolsInner
     */
    type: AdditionalMessageAttachmentToolsInnerTypeEnum;
}


/**
 * @export
 */
export const AdditionalMessageAttachmentToolsInnerTypeEnum = {
    CodeInterpreter: 'code_interpreter',
    FileSearch: 'file_search'
} as const;
export type AdditionalMessageAttachmentToolsInnerTypeEnum = typeof AdditionalMessageAttachmentToolsInnerTypeEnum[keyof typeof AdditionalMessageAttachmentToolsInnerTypeEnum];


/**
 * Check if a given object implements the AdditionalMessageAttachmentToolsInner interface.
 */
export function instanceOfAdditionalMessageAttachmentToolsInner(value: object): value is AdditionalMessageAttachmentToolsInner {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function AdditionalMessageAttachmentToolsInnerFromJSON(json: any): AdditionalMessageAttachmentToolsInner {
    return AdditionalMessageAttachmentToolsInnerFromJSONTyped(json, false);
}

export function AdditionalMessageAttachmentToolsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdditionalMessageAttachmentToolsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
    };
}

export function AdditionalMessageAttachmentToolsInnerToJSON(json: any): AdditionalMessageAttachmentToolsInner {
    return AdditionalMessageAttachmentToolsInnerToJSONTyped(json, false);
}

export function AdditionalMessageAttachmentToolsInnerToJSONTyped(value?: AdditionalMessageAttachmentToolsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
    };
}

