/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Content } from './Content';
import {
    ContentFromJSON,
    ContentFromJSONTyped,
    ContentToJSON,
    ContentToJSONTyped,
} from './Content';
import type { AdditionalMessageAttachment } from './AdditionalMessageAttachment';
import {
    AdditionalMessageAttachmentFromJSON,
    AdditionalMessageAttachmentFromJSONTyped,
    AdditionalMessageAttachmentToJSON,
    AdditionalMessageAttachmentToJSONTyped,
} from './AdditionalMessageAttachment';

/**
 * 
 * @export
 * @interface AdditionalMessage
 */
export interface AdditionalMessage {
    /**
     * 
     * @type {Content}
     * @memberof AdditionalMessage
     */
    content: Content;
    /**
     * 
     * @type {string}
     * @memberof AdditionalMessage
     */
    role: AdditionalMessageRoleEnum;
    /**
     * 
     * @type {Array<AdditionalMessageAttachment>}
     * @memberof AdditionalMessage
     */
    attachments?: Array<AdditionalMessageAttachment> | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof AdditionalMessage
     */
    metadata?: { [key: string]: string; } | null;
}


/**
 * @export
 */
export const AdditionalMessageRoleEnum = {
    User: 'user',
    Assistant: 'assistant'
} as const;
export type AdditionalMessageRoleEnum = typeof AdditionalMessageRoleEnum[keyof typeof AdditionalMessageRoleEnum];


/**
 * Check if a given object implements the AdditionalMessage interface.
 */
export function instanceOfAdditionalMessage(value: object): value is AdditionalMessage {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function AdditionalMessageFromJSON(json: any): AdditionalMessage {
    return AdditionalMessageFromJSONTyped(json, false);
}

export function AdditionalMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdditionalMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'content': ContentFromJSON(json['content']),
        'role': json['role'],
        'attachments': json['attachments'] == null ? undefined : ((json['attachments'] as Array<any>).map(AdditionalMessageAttachmentFromJSON)),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function AdditionalMessageToJSON(json: any): AdditionalMessage {
    return AdditionalMessageToJSONTyped(json, false);
}

export function AdditionalMessageToJSONTyped(value?: AdditionalMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': ContentToJSON(value['content']),
        'role': value['role'],
        'attachments': value['attachments'] == null ? undefined : ((value['attachments'] as Array<any>).map(AdditionalMessageAttachmentToJSON)),
        'metadata': value['metadata'],
    };
}

