/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdditionalMessageAttachmentToolFileSearch
 */
export interface AdditionalMessageAttachmentToolFileSearch {
    /**
     * 
     * @type {string}
     * @memberof AdditionalMessageAttachmentToolFileSearch
     */
    type: AdditionalMessageAttachmentToolFileSearchTypeEnum;
}


/**
 * @export
 */
export const AdditionalMessageAttachmentToolFileSearchTypeEnum = {
    FileSearch: 'file_search'
} as const;
export type AdditionalMessageAttachmentToolFileSearchTypeEnum = typeof AdditionalMessageAttachmentToolFileSearchTypeEnum[keyof typeof AdditionalMessageAttachmentToolFileSearchTypeEnum];


/**
 * Check if a given object implements the AdditionalMessageAttachmentToolFileSearch interface.
 */
export function instanceOfAdditionalMessageAttachmentToolFileSearch(value: object): value is AdditionalMessageAttachmentToolFileSearch {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function AdditionalMessageAttachmentToolFileSearchFromJSON(json: any): AdditionalMessageAttachmentToolFileSearch {
    return AdditionalMessageAttachmentToolFileSearchFromJSONTyped(json, false);
}

export function AdditionalMessageAttachmentToolFileSearchFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdditionalMessageAttachmentToolFileSearch {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
    };
}

export function AdditionalMessageAttachmentToolFileSearchToJSON(json: any): AdditionalMessageAttachmentToolFileSearch {
    return AdditionalMessageAttachmentToolFileSearchToJSONTyped(json, false);
}

export function AdditionalMessageAttachmentToolFileSearchToJSONTyped(value?: AdditionalMessageAttachmentToolFileSearch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
    };
}

