/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AgentDataRequest
 */
export interface AgentDataRequest {
    /**
     * 
     * @type {string}
     * @memberof AgentDataRequest
     */
    key: string;
    /**
     * 
     * @type {object}
     * @memberof AgentDataRequest
     */
    value: object;
}

/**
 * Check if a given object implements the AgentDataRequest interface.
 */
export function instanceOfAgentDataRequest(value: object): value is AgentDataRequest {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function AgentDataRequestFromJSON(json: any): AgentDataRequest {
    return AgentDataRequestFromJSONTyped(json, false);
}

export function AgentDataRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentDataRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'value': json['value'],
    };
}

export function AgentDataRequestToJSON(json: any): AgentDataRequest {
    return AgentDataRequestToJSONTyped(json, false);
}

export function AgentDataRequestToJSONTyped(value?: AgentDataRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'value': value['value'],
    };
}

