/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AttachmentToolsInner } from './AttachmentToolsInner';
import {
    AttachmentToolsInnerFromJSON,
    AttachmentToolsInnerFromJSONTyped,
    AttachmentToolsInnerToJSON,
    AttachmentToolsInnerToJSONTyped,
} from './AttachmentToolsInner';

/**
 * 
 * @export
 * @interface Attachment
 */
export interface Attachment {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof Attachment
     */
    fileId?: string | null;
    /**
     * 
     * @type {Array<AttachmentToolsInner>}
     * @memberof Attachment
     */
    tools?: Array<AttachmentToolsInner> | null;
}

/**
 * Check if a given object implements the Attachment interface.
 */
export function instanceOfAttachment(value: object): value is Attachment {
    return true;
}

export function AttachmentFromJSON(json: any): Attachment {
    return AttachmentFromJSONTyped(json, false);
}

export function AttachmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Attachment {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'fileId': json['file_id'] == null ? undefined : json['file_id'],
        'tools': json['tools'] == null ? undefined : ((json['tools'] as Array<any>).map(AttachmentToolsInnerFromJSON)),
    };
}

export function AttachmentToJSON(json: any): Attachment {
    return AttachmentToJSONTyped(json, false);
}

export function AttachmentToJSONTyped(value?: Attachment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'file_id': value['fileId'],
        'tools': value['tools'] == null ? undefined : ((value['tools'] as Array<any>).map(AttachmentToolsInnerToJSON)),
    };
}

