/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AttachmentToolAssistantToolsFileSearchTypeOnly
 */
export interface AttachmentToolAssistantToolsFileSearchTypeOnly {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof AttachmentToolAssistantToolsFileSearchTypeOnly
     */
    type: AttachmentToolAssistantToolsFileSearchTypeOnlyTypeEnum;
}


/**
 * @export
 */
export const AttachmentToolAssistantToolsFileSearchTypeOnlyTypeEnum = {
    FileSearch: 'file_search'
} as const;
export type AttachmentToolAssistantToolsFileSearchTypeOnlyTypeEnum = typeof AttachmentToolAssistantToolsFileSearchTypeOnlyTypeEnum[keyof typeof AttachmentToolAssistantToolsFileSearchTypeOnlyTypeEnum];


/**
 * Check if a given object implements the AttachmentToolAssistantToolsFileSearchTypeOnly interface.
 */
export function instanceOfAttachmentToolAssistantToolsFileSearchTypeOnly(value: object): value is AttachmentToolAssistantToolsFileSearchTypeOnly {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function AttachmentToolAssistantToolsFileSearchTypeOnlyFromJSON(json: any): AttachmentToolAssistantToolsFileSearchTypeOnly {
    return AttachmentToolAssistantToolsFileSearchTypeOnlyFromJSONTyped(json, false);
}

export function AttachmentToolAssistantToolsFileSearchTypeOnlyFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttachmentToolAssistantToolsFileSearchTypeOnly {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'type': json['type'],
    };
}

export function AttachmentToolAssistantToolsFileSearchTypeOnlyToJSON(json: any): AttachmentToolAssistantToolsFileSearchTypeOnly {
    return AttachmentToolAssistantToolsFileSearchTypeOnlyToJSONTyped(json, false);
}

export function AttachmentToolAssistantToolsFileSearchTypeOnlyToJSONTyped(value?: AttachmentToolAssistantToolsFileSearchTypeOnly | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'type': value['type'],
    };
}

