/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AutoFileChunkingStrategyParam
 */
export interface AutoFileChunkingStrategyParam {
    /**
     * 
     * @type {string}
     * @memberof AutoFileChunkingStrategyParam
     */
    type: AutoFileChunkingStrategyParamTypeEnum;
}


/**
 * @export
 */
export const AutoFileChunkingStrategyParamTypeEnum = {
    Auto: 'auto'
} as const;
export type AutoFileChunkingStrategyParamTypeEnum = typeof AutoFileChunkingStrategyParamTypeEnum[keyof typeof AutoFileChunkingStrategyParamTypeEnum];


/**
 * Check if a given object implements the AutoFileChunkingStrategyParam interface.
 */
export function instanceOfAutoFileChunkingStrategyParam(value: object): value is AutoFileChunkingStrategyParam {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function AutoFileChunkingStrategyParamFromJSON(json: any): AutoFileChunkingStrategyParam {
    return AutoFileChunkingStrategyParamFromJSONTyped(json, false);
}

export function AutoFileChunkingStrategyParamFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutoFileChunkingStrategyParam {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
    };
}

export function AutoFileChunkingStrategyParamToJSON(json: any): AutoFileChunkingStrategyParam {
    return AutoFileChunkingStrategyParamToJSONTyped(json, false);
}

export function AutoFileChunkingStrategyParamToJSONTyped(value?: AutoFileChunkingStrategyParam | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
    };
}

