/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntryLocation } from './EntryLocation';
import {
    EntryLocationFromJSON,
    EntryLocationFromJSONTyped,
    EntryLocationToJSON,
    EntryLocationToJSONTyped,
} from './EntryLocation';

/**
 * 
 * @export
 * @interface BodyAddJobV1JobsAddJobPost
 */
export interface BodyAddJobV1JobsAddJobPost {
    /**
     * 
     * @type {EntryLocation}
     * @memberof BodyAddJobV1JobsAddJobPost
     */
    entryLocation: EntryLocation;
}

/**
 * Check if a given object implements the BodyAddJobV1JobsAddJobPost interface.
 */
export function instanceOfBodyAddJobV1JobsAddJobPost(value: object): value is BodyAddJobV1JobsAddJobPost {
    if (!('entryLocation' in value) || value['entryLocation'] === undefined) return false;
    return true;
}

export function BodyAddJobV1JobsAddJobPostFromJSON(json: any): BodyAddJobV1JobsAddJobPost {
    return BodyAddJobV1JobsAddJobPostFromJSONTyped(json, false);
}

export function BodyAddJobV1JobsAddJobPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): BodyAddJobV1JobsAddJobPost {
    if (json == null) {
        return json;
    }
    return {
        
        'entryLocation': EntryLocationFromJSON(json['entry_location']),
    };
}

export function BodyAddJobV1JobsAddJobPostToJSON(json: any): BodyAddJobV1JobsAddJobPost {
    return BodyAddJobV1JobsAddJobPostToJSONTyped(json, false);
}

export function BodyAddJobV1JobsAddJobPostToJSONTyped(value?: BodyAddJobV1JobsAddJobPost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entry_location': EntryLocationToJSON(value['entryLocation']),
    };
}

