/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntryLocation } from './EntryLocation';
import {
    EntryLocationFromJSON,
    EntryLocationFromJSONTyped,
    EntryLocationToJSON,
    EntryLocationToJSONTyped,
} from './EntryLocation';

/**
 * 
 * @export
 * @interface BodyListFilesV1RegistryListFilesPost
 */
export interface BodyListFilesV1RegistryListFilesPost {
    /**
     * 
     * @type {EntryLocation}
     * @memberof BodyListFilesV1RegistryListFilesPost
     */
    entryLocation: EntryLocation;
}

/**
 * Check if a given object implements the BodyListFilesV1RegistryListFilesPost interface.
 */
export function instanceOfBodyListFilesV1RegistryListFilesPost(value: object): value is BodyListFilesV1RegistryListFilesPost {
    if (!('entryLocation' in value) || value['entryLocation'] === undefined) return false;
    return true;
}

export function BodyListFilesV1RegistryListFilesPostFromJSON(json: any): BodyListFilesV1RegistryListFilesPost {
    return BodyListFilesV1RegistryListFilesPostFromJSONTyped(json, false);
}

export function BodyListFilesV1RegistryListFilesPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): BodyListFilesV1RegistryListFilesPost {
    if (json == null) {
        return json;
    }
    return {
        
        'entryLocation': EntryLocationFromJSON(json['entry_location']),
    };
}

export function BodyListFilesV1RegistryListFilesPostToJSON(json: any): BodyListFilesV1RegistryListFilesPost {
    return BodyListFilesV1RegistryListFilesPostToJSONTyped(json, false);
}

export function BodyListFilesV1RegistryListFilesPostToJSONTyped(value?: BodyListFilesV1RegistryListFilesPost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entry_location': EntryLocationToJSON(value['entryLocation']),
    };
}

