/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ForkEntryModifications } from './ForkEntryModifications';
import {
    ForkEntryModificationsFromJSON,
    ForkEntryModificationsFromJSONTyped,
    ForkEntryModificationsToJSON,
    ForkEntryModificationsToJSONTyped,
} from './ForkEntryModifications';
import type { EntryLocation } from './EntryLocation';
import {
    EntryLocationFromJSON,
    EntryLocationFromJSONTyped,
    EntryLocationToJSON,
    EntryLocationToJSONTyped,
} from './EntryLocation';

/**
 * 
 * @export
 * @interface BodyForkEntryV1RegistryForkPost
 */
export interface BodyForkEntryV1RegistryForkPost {
    /**
     * 
     * @type {ForkEntryModifications}
     * @memberof BodyForkEntryV1RegistryForkPost
     */
    modifications: ForkEntryModifications;
    /**
     * 
     * @type {EntryLocation}
     * @memberof BodyForkEntryV1RegistryForkPost
     */
    entryLocation: EntryLocation;
}

/**
 * Check if a given object implements the BodyForkEntryV1RegistryForkPost interface.
 */
export function instanceOfBodyForkEntryV1RegistryForkPost(value: object): value is BodyForkEntryV1RegistryForkPost {
    if (!('modifications' in value) || value['modifications'] === undefined) return false;
    if (!('entryLocation' in value) || value['entryLocation'] === undefined) return false;
    return true;
}

export function BodyForkEntryV1RegistryForkPostFromJSON(json: any): BodyForkEntryV1RegistryForkPost {
    return BodyForkEntryV1RegistryForkPostFromJSONTyped(json, false);
}

export function BodyForkEntryV1RegistryForkPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): BodyForkEntryV1RegistryForkPost {
    if (json == null) {
        return json;
    }
    return {
        
        'modifications': ForkEntryModificationsFromJSON(json['modifications']),
        'entryLocation': EntryLocationFromJSON(json['entry_location']),
    };
}

export function BodyForkEntryV1RegistryForkPostToJSON(json: any): BodyForkEntryV1RegistryForkPost {
    return BodyForkEntryV1RegistryForkPostToJSONTyped(json, false);
}

export function BodyForkEntryV1RegistryForkPostToJSONTyped(value?: BodyForkEntryV1RegistryForkPost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'modifications': ForkEntryModificationsToJSON(value['modifications']),
        'entry_location': EntryLocationToJSON(value['entryLocation']),
    };
}

