/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntryLocation } from './EntryLocation';
import {
    EntryLocationFromJSON,
    EntryLocationFromJSONTyped,
    EntryLocationToJSON,
    EntryLocationToJSONTyped,
} from './EntryLocation';

/**
 * 
 * @export
 * @interface BodyDownloadMetadataV1RegistryDownloadMetadataPost
 */
export interface BodyDownloadMetadataV1RegistryDownloadMetadataPost {
    /**
     * 
     * @type {EntryLocation}
     * @memberof BodyDownloadMetadataV1RegistryDownloadMetadataPost
     */
    entryLocation: EntryLocation;
}

/**
 * Check if a given object implements the BodyDownloadMetadataV1RegistryDownloadMetadataPost interface.
 */
export function instanceOfBodyDownloadMetadataV1RegistryDownloadMetadataPost(value: object): value is BodyDownloadMetadataV1RegistryDownloadMetadataPost {
    if (!('entryLocation' in value) || value['entryLocation'] === undefined) return false;
    return true;
}

export function BodyDownloadMetadataV1RegistryDownloadMetadataPostFromJSON(json: any): BodyDownloadMetadataV1RegistryDownloadMetadataPost {
    return BodyDownloadMetadataV1RegistryDownloadMetadataPostFromJSONTyped(json, false);
}

export function BodyDownloadMetadataV1RegistryDownloadMetadataPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): BodyDownloadMetadataV1RegistryDownloadMetadataPost {
    if (json == null) {
        return json;
    }
    return {
        
        'entryLocation': EntryLocationFromJSON(json['entry_location']),
    };
}

export function BodyDownloadMetadataV1RegistryDownloadMetadataPostToJSON(json: any): BodyDownloadMetadataV1RegistryDownloadMetadataPost {
    return BodyDownloadMetadataV1RegistryDownloadMetadataPostToJSONTyped(json, false);
}

export function BodyDownloadMetadataV1RegistryDownloadMetadataPostToJSONTyped(value?: BodyDownloadMetadataV1RegistryDownloadMetadataPost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entry_location': EntryLocationToJSON(value['entryLocation']),
    };
}

