/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntryLocation } from './EntryLocation';
import {
    EntryLocationFromJSON,
    EntryLocationFromJSONTyped,
    EntryLocationToJSON,
    EntryLocationToJSONTyped,
} from './EntryLocation';

/**
 * 
 * @export
 * @interface BodyDownloadFileV1RegistryDownloadFilePost
 */
export interface BodyDownloadFileV1RegistryDownloadFilePost {
    /**
     * 
     * @type {string}
     * @memberof BodyDownloadFileV1RegistryDownloadFilePost
     */
    path: string;
    /**
     * 
     * @type {EntryLocation}
     * @memberof BodyDownloadFileV1RegistryDownloadFilePost
     */
    entryLocation: EntryLocation;
}

/**
 * Check if a given object implements the BodyDownloadFileV1RegistryDownloadFilePost interface.
 */
export function instanceOfBodyDownloadFileV1RegistryDownloadFilePost(value: object): value is BodyDownloadFileV1RegistryDownloadFilePost {
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('entryLocation' in value) || value['entryLocation'] === undefined) return false;
    return true;
}

export function BodyDownloadFileV1RegistryDownloadFilePostFromJSON(json: any): BodyDownloadFileV1RegistryDownloadFilePost {
    return BodyDownloadFileV1RegistryDownloadFilePostFromJSONTyped(json, false);
}

export function BodyDownloadFileV1RegistryDownloadFilePostFromJSONTyped(json: any, ignoreDiscriminator: boolean): BodyDownloadFileV1RegistryDownloadFilePost {
    if (json == null) {
        return json;
    }
    return {
        
        'path': json['path'],
        'entryLocation': EntryLocationFromJSON(json['entry_location']),
    };
}

export function BodyDownloadFileV1RegistryDownloadFilePostToJSON(json: any): BodyDownloadFileV1RegistryDownloadFilePost {
    return BodyDownloadFileV1RegistryDownloadFilePostToJSONTyped(json, false);
}

export function BodyDownloadFileV1RegistryDownloadFilePostToJSONTyped(value?: BodyDownloadFileV1RegistryDownloadFilePost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'path': value['path'],
        'entry_location': EntryLocationToJSON(value['entryLocation']),
    };
}

