/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AutoFileChunkingStrategyParam } from './AutoFileChunkingStrategyParam';
import {
    AutoFileChunkingStrategyParamFromJSON,
    AutoFileChunkingStrategyParamFromJSONTyped,
    AutoFileChunkingStrategyParamToJSON,
    AutoFileChunkingStrategyParamToJSONTyped,
} from './AutoFileChunkingStrategyParam';
import type { StaticFileChunkingStrategyParam } from './StaticFileChunkingStrategyParam';
import {
    StaticFileChunkingStrategyParamFromJSON,
    StaticFileChunkingStrategyParamFromJSONTyped,
    StaticFileChunkingStrategyParamToJSON,
    StaticFileChunkingStrategyParamToJSONTyped,
} from './StaticFileChunkingStrategyParam';

/**
 * 
 * @export
 * @interface ChunkingStrategy
 */
export interface ChunkingStrategy {
    /**
     * 
     * @type {string}
     * @memberof ChunkingStrategy
     */
    type: ChunkingStrategyTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof ChunkingStrategy
     */
    chunkOverlapTokens: number;
    /**
     * 
     * @type {number}
     * @memberof ChunkingStrategy
     */
    maxChunkSizeTokens: number;
}


/**
 * @export
 */
export const ChunkingStrategyTypeEnum = {
    Auto: 'auto'
} as const;
export type ChunkingStrategyTypeEnum = typeof ChunkingStrategyTypeEnum[keyof typeof ChunkingStrategyTypeEnum];


/**
 * Check if a given object implements the ChunkingStrategy interface.
 */
export function instanceOfChunkingStrategy(value: object): value is ChunkingStrategy {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('chunkOverlapTokens' in value) || value['chunkOverlapTokens'] === undefined) return false;
    if (!('maxChunkSizeTokens' in value) || value['maxChunkSizeTokens'] === undefined) return false;
    return true;
}

export function ChunkingStrategyFromJSON(json: any): ChunkingStrategy {
    return ChunkingStrategyFromJSONTyped(json, false);
}

export function ChunkingStrategyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChunkingStrategy {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'chunkOverlapTokens': json['chunk_overlap_tokens'],
        'maxChunkSizeTokens': json['max_chunk_size_tokens'],
    };
}

export function ChunkingStrategyToJSON(json: any): ChunkingStrategy {
    return ChunkingStrategyToJSONTyped(json, false);
}

export function ChunkingStrategyToJSONTyped(value?: ChunkingStrategy | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'chunk_overlap_tokens': value['chunkOverlapTokens'],
        'max_chunk_size_tokens': value['maxChunkSizeTokens'],
    };
}

