/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CodeInterpreterToolParam
 */
export interface CodeInterpreterToolParam {
    /**
     * 
     * @type {string}
     * @memberof CodeInterpreterToolParam
     */
    type: CodeInterpreterToolParamTypeEnum;
}


/**
 * @export
 */
export const CodeInterpreterToolParamTypeEnum = {
    CodeInterpreter: 'code_interpreter'
} as const;
export type CodeInterpreterToolParamTypeEnum = typeof CodeInterpreterToolParamTypeEnum[keyof typeof CodeInterpreterToolParamTypeEnum];


/**
 * Check if a given object implements the CodeInterpreterToolParam interface.
 */
export function instanceOfCodeInterpreterToolParam(value: object): value is CodeInterpreterToolParam {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function CodeInterpreterToolParamFromJSON(json: any): CodeInterpreterToolParam {
    return CodeInterpreterToolParamFromJSONTyped(json, false);
}

export function CodeInterpreterToolParamFromJSONTyped(json: any, ignoreDiscriminator: boolean): CodeInterpreterToolParam {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
    };
}

export function CodeInterpreterToolParamToJSON(json: any): CodeInterpreterToolParam {
    return CodeInterpreterToolParamToJSONTyped(json, false);
}

export function CodeInterpreterToolParamToJSONTyped(value?: CodeInterpreterToolParam | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
    };
}

