/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseFormat } from './ResponseFormat';
import {
    ResponseFormatFromJSON,
    ResponseFormatFromJSONTyped,
    ResponseFormatToJSON,
    ResponseFormatToJSONTyped,
} from './ResponseFormat';
import type { Stop } from './Stop';
import {
    StopFromJSON,
    StopFromJSONTyped,
    StopToJSON,
    StopToJSONTyped,
} from './Stop';

/**
 * Request for completions.
 * @export
 * @interface CompletionsRequest
 */
export interface CompletionsRequest {
    /**
     * 
     * @type {string}
     * @memberof CompletionsRequest
     */
    model?: string;
    /**
     * 
     * @type {string}
     * @memberof CompletionsRequest
     */
    provider?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CompletionsRequest
     */
    maxTokens?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CompletionsRequest
     */
    logprobs?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CompletionsRequest
     */
    temperature?: number;
    /**
     * 
     * @type {number}
     * @memberof CompletionsRequest
     */
    topP?: number;
    /**
     * 
     * @type {number}
     * @memberof CompletionsRequest
     */
    frequencyPenalty?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CompletionsRequest
     */
    n?: number;
    /**
     * 
     * @type {Stop}
     * @memberof CompletionsRequest
     */
    stop?: Stop | null;
    /**
     * 
     * @type {ResponseFormat}
     * @memberof CompletionsRequest
     */
    responseFormat?: ResponseFormat | null;
    /**
     * 
     * @type {boolean}
     * @memberof CompletionsRequest
     */
    stream?: boolean;
    /**
     * 
     * @type {Array<any>}
     * @memberof CompletionsRequest
     */
    tools?: Array<any> | null;
    /**
     * 
     * @type {string}
     * @memberof CompletionsRequest
     */
    prompt: string;
}

/**
 * Check if a given object implements the CompletionsRequest interface.
 */
export function instanceOfCompletionsRequest(value: object): value is CompletionsRequest {
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    return true;
}

export function CompletionsRequestFromJSON(json: any): CompletionsRequest {
    return CompletionsRequestFromJSONTyped(json, false);
}

export function CompletionsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompletionsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'model': json['model'] == null ? undefined : json['model'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'maxTokens': json['max_tokens'] == null ? undefined : json['max_tokens'],
        'logprobs': json['logprobs'] == null ? undefined : json['logprobs'],
        'temperature': json['temperature'] == null ? undefined : json['temperature'],
        'topP': json['top_p'] == null ? undefined : json['top_p'],
        'frequencyPenalty': json['frequency_penalty'] == null ? undefined : json['frequency_penalty'],
        'n': json['n'] == null ? undefined : json['n'],
        'stop': json['stop'] == null ? undefined : StopFromJSON(json['stop']),
        'responseFormat': json['response_format'] == null ? undefined : ResponseFormatFromJSON(json['response_format']),
        'stream': json['stream'] == null ? undefined : json['stream'],
        'tools': json['tools'] == null ? undefined : json['tools'],
        'prompt': json['prompt'],
    };
}

export function CompletionsRequestToJSON(json: any): CompletionsRequest {
    return CompletionsRequestToJSONTyped(json, false);
}

export function CompletionsRequestToJSONTyped(value?: CompletionsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'model': value['model'],
        'provider': value['provider'],
        'max_tokens': value['maxTokens'],
        'logprobs': value['logprobs'],
        'temperature': value['temperature'],
        'top_p': value['topP'],
        'frequency_penalty': value['frequencyPenalty'],
        'n': value['n'],
        'stop': StopToJSON(value['stop']),
        'response_format': ResponseFormatToJSON(value['responseFormat']),
        'stream': value['stream'],
        'tools': value['tools'],
        'prompt': value['prompt'],
    };
}

