/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImageFileParam } from './ImageFileParam';
import {
    ImageFileParamFromJSON,
    ImageFileParamFromJSONTyped,
    ImageFileParamToJSON,
    ImageFileParamToJSONTyped,
} from './ImageFileParam';
import type { ImageFileContentBlockParam } from './ImageFileContentBlockParam';
import {
    ImageFileContentBlockParamFromJSON,
    ImageFileContentBlockParamFromJSONTyped,
    ImageFileContentBlockParamToJSON,
    ImageFileContentBlockParamToJSONTyped,
} from './ImageFileContentBlockParam';
import type { ImageURLParam } from './ImageURLParam';
import {
    ImageURLParamFromJSON,
    ImageURLParamFromJSONTyped,
    ImageURLParamToJSON,
    ImageURLParamToJSONTyped,
} from './ImageURLParam';
import type { TextContentBlockParam } from './TextContentBlockParam';
import {
    TextContentBlockParamFromJSON,
    TextContentBlockParamFromJSONTyped,
    TextContentBlockParamToJSON,
    TextContentBlockParamToJSONTyped,
} from './TextContentBlockParam';
import type { ImageURLContentBlockParam } from './ImageURLContentBlockParam';
import {
    ImageURLContentBlockParamFromJSON,
    ImageURLContentBlockParamFromJSONTyped,
    ImageURLContentBlockParamToJSON,
    ImageURLContentBlockParamToJSONTyped,
} from './ImageURLContentBlockParam';

/**
 * 
 * @export
 * @interface ContentAnyOfInner
 */
export interface ContentAnyOfInner {
    /**
     * 
     * @type {ImageFileParam}
     * @memberof ContentAnyOfInner
     */
    imageFile: ImageFileParam;
    /**
     * 
     * @type {string}
     * @memberof ContentAnyOfInner
     */
    type: ContentAnyOfInnerTypeEnum;
    /**
     * 
     * @type {ImageURLParam}
     * @memberof ContentAnyOfInner
     */
    imageUrl: ImageURLParam;
    /**
     * 
     * @type {string}
     * @memberof ContentAnyOfInner
     */
    text: string;
}


/**
 * @export
 */
export const ContentAnyOfInnerTypeEnum = {
    ImageFile: 'image_file',
    ImageUrl: 'image_url',
    Text: 'text'
} as const;
export type ContentAnyOfInnerTypeEnum = typeof ContentAnyOfInnerTypeEnum[keyof typeof ContentAnyOfInnerTypeEnum];


/**
 * Check if a given object implements the ContentAnyOfInner interface.
 */
export function instanceOfContentAnyOfInner(value: object): value is ContentAnyOfInner {
    if (!('imageFile' in value) || value['imageFile'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('imageUrl' in value) || value['imageUrl'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function ContentAnyOfInnerFromJSON(json: any): ContentAnyOfInner {
    return ContentAnyOfInnerFromJSONTyped(json, false);
}

export function ContentAnyOfInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentAnyOfInner {
    if (json == null) {
        return json;
    }
    return {
        
        'imageFile': ImageFileParamFromJSON(json['image_file']),
        'type': json['type'],
        'imageUrl': ImageURLParamFromJSON(json['image_url']),
        'text': json['text'],
    };
}

export function ContentAnyOfInnerToJSON(json: any): ContentAnyOfInner {
    return ContentAnyOfInnerToJSONTyped(json, false);
}

export function ContentAnyOfInnerToJSONTyped(value?: ContentAnyOfInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'image_file': ImageFileParamToJSON(value['imageFile']),
        'type': value['type'],
        'image_url': ImageURLParamToJSON(value['imageUrl']),
        'text': value['text'],
    };
}

