/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateThreadAndRunRequest
 */
export interface CreateThreadAndRunRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateThreadAndRunRequest
     */
    agentId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateThreadAndRunRequest
     */
    assistantId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateThreadAndRunRequest
     */
    threadId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateThreadAndRunRequest
     */
    newMessage?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CreateThreadAndRunRequest
     */
    recordRun?: boolean | null;
    /**
     * 
     * @type {object}
     * @memberof CreateThreadAndRunRequest
     */
    toolResources?: object | null;
    /**
     * 
     * @type {object}
     * @memberof CreateThreadAndRunRequest
     */
    userEnvVars?: object | null;
}

/**
 * Check if a given object implements the CreateThreadAndRunRequest interface.
 */
export function instanceOfCreateThreadAndRunRequest(value: object): value is CreateThreadAndRunRequest {
    return true;
}

export function CreateThreadAndRunRequestFromJSON(json: any): CreateThreadAndRunRequest {
    return CreateThreadAndRunRequestFromJSONTyped(json, false);
}

export function CreateThreadAndRunRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateThreadAndRunRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'agentId': json['agent_id'] == null ? undefined : json['agent_id'],
        'assistantId': json['assistant_id'] == null ? undefined : json['assistant_id'],
        'threadId': json['thread_id'] == null ? undefined : json['thread_id'],
        'newMessage': json['new_message'] == null ? undefined : json['new_message'],
        'recordRun': json['record_run'] == null ? undefined : json['record_run'],
        'toolResources': json['tool_resources'] == null ? undefined : json['tool_resources'],
        'userEnvVars': json['user_env_vars'] == null ? undefined : json['user_env_vars'],
    };
}

export function CreateThreadAndRunRequestToJSON(json: any): CreateThreadAndRunRequest {
    return CreateThreadAndRunRequestToJSONTyped(json, false);
}

export function CreateThreadAndRunRequestToJSONTyped(value?: CreateThreadAndRunRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'agent_id': value['agentId'],
        'assistant_id': value['assistantId'],
        'thread_id': value['threadId'],
        'new_message': value['newMessage'],
        'record_run': value['recordRun'],
        'tool_resources': value['toolResources'],
        'user_env_vars': value['userEnvVars'],
    };
}

