/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExpiresAfterInput } from './ExpiresAfterInput';
import {
    ExpiresAfterInputFromJSON,
    ExpiresAfterInputFromJSONTyped,
    ExpiresAfterInputToJSON,
    ExpiresAfterInputToJSONTyped,
} from './ExpiresAfterInput';
import type { Source } from './Source';
import {
    SourceFromJSON,
    SourceFromJSONTyped,
    SourceToJSON,
    SourceToJSONTyped,
} from './Source';

/**
 * 
 * @export
 * @interface CreateVectorStoreFromSourceRequest
 */
export interface CreateVectorStoreFromSourceRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateVectorStoreFromSourceRequest
     */
    name: string;
    /**
     * 
     * @type {Source}
     * @memberof CreateVectorStoreFromSourceRequest
     */
    source: Source;
    /**
     * 
     * @type {string}
     * @memberof CreateVectorStoreFromSourceRequest
     */
    sourceAuth?: string | null;
    /**
     * Defines the chunking strategy for vector stores.
     * @type {object}
     * @memberof CreateVectorStoreFromSourceRequest
     */
    chunkingStrategy?: object;
    /**
     * 
     * @type {ExpiresAfterInput}
     * @memberof CreateVectorStoreFromSourceRequest
     */
    expiresAfter?: ExpiresAfterInput | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof CreateVectorStoreFromSourceRequest
     */
    metadata?: { [key: string]: string; } | null;
}

/**
 * Check if a given object implements the CreateVectorStoreFromSourceRequest interface.
 */
export function instanceOfCreateVectorStoreFromSourceRequest(value: object): value is CreateVectorStoreFromSourceRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    return true;
}

export function CreateVectorStoreFromSourceRequestFromJSON(json: any): CreateVectorStoreFromSourceRequest {
    return CreateVectorStoreFromSourceRequestFromJSONTyped(json, false);
}

export function CreateVectorStoreFromSourceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateVectorStoreFromSourceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'source': SourceFromJSON(json['source']),
        'sourceAuth': json['source_auth'] == null ? undefined : json['source_auth'],
        'chunkingStrategy': json['chunking_strategy'] == null ? undefined : json['chunking_strategy'],
        'expiresAfter': json['expires_after'] == null ? undefined : ExpiresAfterInputFromJSON(json['expires_after']),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function CreateVectorStoreFromSourceRequestToJSON(json: any): CreateVectorStoreFromSourceRequest {
    return CreateVectorStoreFromSourceRequestToJSONTyped(json, false);
}

export function CreateVectorStoreFromSourceRequestToJSONTyped(value?: CreateVectorStoreFromSourceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'source': SourceToJSON(value['source']),
        'source_auth': value['sourceAuth'],
        'chunking_strategy': value['chunkingStrategy'],
        'expires_after': ExpiresAfterInputToJSON(value['expiresAfter']),
        'metadata': value['metadata'],
    };
}

