/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request model for creating a new scheduled run.
 * @export
 * @interface CreateScheduleRunRequest
 */
export interface CreateScheduleRunRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateScheduleRunRequest
     */
    agent: string;
    /**
     * 
     * @type {string}
     * @memberof CreateScheduleRunRequest
     */
    inputMessage: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof CreateScheduleRunRequest
     */
    runParams: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof CreateScheduleRunRequest
     */
    threadId: string | null;
    /**
     * 
     * @type {Date}
     * @memberof CreateScheduleRunRequest
     */
    runAt: Date;
}

/**
 * Check if a given object implements the CreateScheduleRunRequest interface.
 */
export function instanceOfCreateScheduleRunRequest(value: object): value is CreateScheduleRunRequest {
    if (!('agent' in value) || value['agent'] === undefined) return false;
    if (!('inputMessage' in value) || value['inputMessage'] === undefined) return false;
    if (!('runParams' in value) || value['runParams'] === undefined) return false;
    if (!('threadId' in value) || value['threadId'] === undefined) return false;
    if (!('runAt' in value) || value['runAt'] === undefined) return false;
    return true;
}

export function CreateScheduleRunRequestFromJSON(json: any): CreateScheduleRunRequest {
    return CreateScheduleRunRequestFromJSONTyped(json, false);
}

export function CreateScheduleRunRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateScheduleRunRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'agent': json['agent'],
        'inputMessage': json['input_message'],
        'runParams': json['run_params'],
        'threadId': json['thread_id'],
        'runAt': (new Date(json['run_at'])),
    };
}

export function CreateScheduleRunRequestToJSON(json: any): CreateScheduleRunRequest {
    return CreateScheduleRunRequestToJSONTyped(json, false);
}

export function CreateScheduleRunRequestToJSONTyped(value?: CreateScheduleRunRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'agent': value['agent'],
        'input_message': value['inputMessage'],
        'run_params': value['runParams'],
        'thread_id': value['threadId'],
        'run_at': ((value['runAt']).toISOString()),
    };
}

