/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Delegation
 */
export interface Delegation {
    /**
     * 
     * @type {number}
     * @memberof Delegation
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Delegation
     */
    originalAccountId: string;
    /**
     * 
     * @type {string}
     * @memberof Delegation
     */
    delegationAccountId: string;
    /**
     * 
     * @type {Date}
     * @memberof Delegation
     */
    expiresAt?: Date | null;
}

/**
 * Check if a given object implements the Delegation interface.
 */
export function instanceOfDelegation(value: object): value is Delegation {
    if (!('originalAccountId' in value) || value['originalAccountId'] === undefined) return false;
    if (!('delegationAccountId' in value) || value['delegationAccountId'] === undefined) return false;
    return true;
}

export function DelegationFromJSON(json: any): Delegation {
    return DelegationFromJSONTyped(json, false);
}

export function DelegationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Delegation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'originalAccountId': json['original_account_id'],
        'delegationAccountId': json['delegation_account_id'],
        'expiresAt': json['expires_at'] == null ? undefined : (new Date(json['expires_at'])),
    };
}

export function DelegationToJSON(json: any): Delegation {
    return DelegationToJSONTyped(json, false);
}

export function DelegationToJSONTyped(value?: Delegation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'original_account_id': value['originalAccountId'],
        'delegation_account_id': value['delegationAccountId'],
        'expires_at': value['expiresAt'] == null ? undefined : ((value['expiresAt'] as any).toISOString()),
    };
}

