/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EntryLocation
 */
export interface EntryLocation {
    /**
     * 
     * @type {string}
     * @memberof EntryLocation
     */
    namespace: string;
    /**
     * 
     * @type {string}
     * @memberof EntryLocation
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof EntryLocation
     */
    version: string;
}

/**
 * Check if a given object implements the EntryLocation interface.
 */
export function instanceOfEntryLocation(value: object): value is EntryLocation {
    if (!('namespace' in value) || value['namespace'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function EntryLocationFromJSON(json: any): EntryLocation {
    return EntryLocationFromJSONTyped(json, false);
}

export function EntryLocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntryLocation {
    if (json == null) {
        return json;
    }
    return {
        
        'namespace': json['namespace'],
        'name': json['name'],
        'version': json['version'],
    };
}

export function EntryLocationToJSON(json: any): EntryLocation {
    return EntryLocationToJSONTyped(json, false);
}

export function EntryLocationToJSONTyped(value?: EntryLocation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'namespace': value['namespace'],
        'name': value['name'],
        'version': value['version'],
    };
}

