/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EntryMetadataInput
 */
export interface EntryMetadataInput {
    /**
     * 
     * @type {string}
     * @memberof EntryMetadataInput
     */
    category: string;
    /**
     * 
     * @type {string}
     * @memberof EntryMetadataInput
     */
    description: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof EntryMetadataInput
     */
    tags: Array<string>;
    /**
     * 
     * @type {object}
     * @memberof EntryMetadataInput
     */
    details: object;
    /**
     * 
     * @type {boolean}
     * @memberof EntryMetadataInput
     */
    showEntry: boolean;
}

/**
 * Check if a given object implements the EntryMetadataInput interface.
 */
export function instanceOfEntryMetadataInput(value: object): value is EntryMetadataInput {
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('tags' in value) || value['tags'] === undefined) return false;
    if (!('details' in value) || value['details'] === undefined) return false;
    if (!('showEntry' in value) || value['showEntry'] === undefined) return false;
    return true;
}

export function EntryMetadataInputFromJSON(json: any): EntryMetadataInput {
    return EntryMetadataInputFromJSONTyped(json, false);
}

export function EntryMetadataInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntryMetadataInput {
    if (json == null) {
        return json;
    }
    return {
        
        'category': json['category'],
        'description': json['description'],
        'tags': json['tags'],
        'details': json['details'],
        'showEntry': json['show_entry'],
    };
}

export function EntryMetadataInputToJSON(json: any): EntryMetadataInput {
    return EntryMetadataInputToJSONTyped(json, false);
}

export function EntryMetadataInputToJSONTyped(value?: EntryMetadataInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'category': value['category'],
        'description': value['description'],
        'tags': value['tags'],
        'details': value['details'],
        'show_entry': value['showEntry'],
    };
}

