/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EntryMetadata
 */
export interface EntryMetadata {
    /**
     * 
     * @type {string}
     * @memberof EntryMetadata
     */
    category: string;
    /**
     * 
     * @type {string}
     * @memberof EntryMetadata
     */
    description: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof EntryMetadata
     */
    tags: Array<string>;
    /**
     * 
     * @type {object}
     * @memberof EntryMetadata
     */
    details: object;
    /**
     * 
     * @type {boolean}
     * @memberof EntryMetadata
     */
    showEntry: boolean;
    /**
     * 
     * @type {string}
     * @memberof EntryMetadata
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof EntryMetadata
     */
    version: string;
}

/**
 * Check if a given object implements the EntryMetadata interface.
 */
export function instanceOfEntryMetadata(value: object): value is EntryMetadata {
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('tags' in value) || value['tags'] === undefined) return false;
    if (!('details' in value) || value['details'] === undefined) return false;
    if (!('showEntry' in value) || value['showEntry'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function EntryMetadataFromJSON(json: any): EntryMetadata {
    return EntryMetadataFromJSONTyped(json, false);
}

export function EntryMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntryMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'category': json['category'],
        'description': json['description'],
        'tags': json['tags'],
        'details': json['details'],
        'showEntry': json['show_entry'],
        'name': json['name'],
        'version': json['version'],
    };
}

export function EntryMetadataToJSON(json: any): EntryMetadata {
    return EntryMetadataToJSONTyped(json, false);
}

export function EntryMetadataToJSONTyped(value?: EntryMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'category': value['category'],
        'description': value['description'],
        'tags': value['tags'],
        'details': value['details'],
        'show_entry': value['showEntry'],
        'name': value['name'],
        'version': value['version'],
    };
}

