/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExpiresAfterOutput
 */
export interface ExpiresAfterOutput {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof ExpiresAfterOutput
     */
    anchor: ExpiresAfterOutputAnchorEnum;
    /**
     * 
     * @type {number}
     * @memberof ExpiresAfterOutput
     */
    days: number;
}


/**
 * @export
 */
export const ExpiresAfterOutputAnchorEnum = {
    LastActiveAt: 'last_active_at'
} as const;
export type ExpiresAfterOutputAnchorEnum = typeof ExpiresAfterOutputAnchorEnum[keyof typeof ExpiresAfterOutputAnchorEnum];


/**
 * Check if a given object implements the ExpiresAfterOutput interface.
 */
export function instanceOfExpiresAfterOutput(value: object): value is ExpiresAfterOutput {
    if (!('anchor' in value) || value['anchor'] === undefined) return false;
    if (!('days' in value) || value['days'] === undefined) return false;
    return true;
}

export function ExpiresAfterOutputFromJSON(json: any): ExpiresAfterOutput {
    return ExpiresAfterOutputFromJSONTyped(json, false);
}

export function ExpiresAfterOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpiresAfterOutput {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'anchor': json['anchor'],
        'days': json['days'],
    };
}

export function ExpiresAfterOutputToJSON(json: any): ExpiresAfterOutput {
    return ExpiresAfterOutputToJSONTyped(json, false);
}

export function ExpiresAfterOutputToJSONTyped(value?: ExpiresAfterOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'anchor': value['anchor'],
        'days': value['days'],
    };
}

