/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExpiresAfterInput
 */
export interface ExpiresAfterInput {
    /**
     * 
     * @type {string}
     * @memberof ExpiresAfterInput
     */
    anchor: ExpiresAfterInputAnchorEnum;
    /**
     * 
     * @type {number}
     * @memberof ExpiresAfterInput
     */
    days: number;
}


/**
 * @export
 */
export const ExpiresAfterInputAnchorEnum = {
    LastActiveAt: 'last_active_at'
} as const;
export type ExpiresAfterInputAnchorEnum = typeof ExpiresAfterInputAnchorEnum[keyof typeof ExpiresAfterInputAnchorEnum];


/**
 * Check if a given object implements the ExpiresAfterInput interface.
 */
export function instanceOfExpiresAfterInput(value: object): value is ExpiresAfterInput {
    if (!('anchor' in value) || value['anchor'] === undefined) return false;
    if (!('days' in value) || value['days'] === undefined) return false;
    return true;
}

export function ExpiresAfterInputFromJSON(json: any): ExpiresAfterInput {
    return ExpiresAfterInputFromJSONTyped(json, false);
}

export function ExpiresAfterInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpiresAfterInput {
    if (json == null) {
        return json;
    }
    return {
        
        'anchor': json['anchor'],
        'days': json['days'],
    };
}

export function ExpiresAfterInputToJSON(json: any): ExpiresAfterInput {
    return ExpiresAfterInputToJSONTyped(json, false);
}

export function ExpiresAfterInputToJSONTyped(value?: ExpiresAfterInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'anchor': value['anchor'],
        'days': value['days'],
    };
}

