/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileCitation
 */
export interface FileCitation {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof FileCitation
     */
    fileId: string;
}

/**
 * Check if a given object implements the FileCitation interface.
 */
export function instanceOfFileCitation(value: object): value is FileCitation {
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    return true;
}

export function FileCitationFromJSON(json: any): FileCitation {
    return FileCitationFromJSONTyped(json, false);
}

export function FileCitationFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileCitation {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'fileId': json['file_id'],
    };
}

export function FileCitationToJSON(json: any): FileCitation {
    return FileCitationToJSONTyped(json, false);
}

export function FileCitationToJSONTyped(value?: FileCitation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'file_id': value['fileId'],
    };
}

