/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileSearch } from './FileSearch';
import {
    FileSearchFromJSON,
    FileSearchFromJSONTyped,
    FileSearchToJSON,
    FileSearchToJSONTyped,
} from './FileSearch';

/**
 * 
 * @export
 * @interface FileSearchTool
 */
export interface FileSearchTool {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof FileSearchTool
     */
    type: FileSearchToolTypeEnum;
    /**
     * 
     * @type {FileSearch}
     * @memberof FileSearchTool
     */
    fileSearch?: FileSearch | null;
}


/**
 * @export
 */
export const FileSearchToolTypeEnum = {
    FileSearch: 'file_search'
} as const;
export type FileSearchToolTypeEnum = typeof FileSearchToolTypeEnum[keyof typeof FileSearchToolTypeEnum];


/**
 * Check if a given object implements the FileSearchTool interface.
 */
export function instanceOfFileSearchTool(value: object): value is FileSearchTool {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function FileSearchToolFromJSON(json: any): FileSearchTool {
    return FileSearchToolFromJSONTyped(json, false);
}

export function FileSearchToolFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileSearchTool {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'type': json['type'],
        'fileSearch': json['file_search'] == null ? undefined : FileSearchFromJSON(json['file_search']),
    };
}

export function FileSearchToolToJSON(json: any): FileSearchTool {
    return FileSearchToolToJSONTyped(json, false);
}

export function FileSearchToolToJSONTyped(value?: FileSearchTool | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'type': value['type'],
        'file_search': FileSearchToJSON(value['fileSearch']),
    };
}

