/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileSearchRankingOptions
 */
export interface FileSearchRankingOptions {
    [key: string]: any | any;
    /**
     * 
     * @type {number}
     * @memberof FileSearchRankingOptions
     */
    scoreThreshold: number;
    /**
     * 
     * @type {string}
     * @memberof FileSearchRankingOptions
     */
    ranker?: FileSearchRankingOptionsRankerEnum | null;
}


/**
 * @export
 */
export const FileSearchRankingOptionsRankerEnum = {
    Auto: 'auto',
    Default20240821: 'default_2024_08_21'
} as const;
export type FileSearchRankingOptionsRankerEnum = typeof FileSearchRankingOptionsRankerEnum[keyof typeof FileSearchRankingOptionsRankerEnum];


/**
 * Check if a given object implements the FileSearchRankingOptions interface.
 */
export function instanceOfFileSearchRankingOptions(value: object): value is FileSearchRankingOptions {
    if (!('scoreThreshold' in value) || value['scoreThreshold'] === undefined) return false;
    return true;
}

export function FileSearchRankingOptionsFromJSON(json: any): FileSearchRankingOptions {
    return FileSearchRankingOptionsFromJSONTyped(json, false);
}

export function FileSearchRankingOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileSearchRankingOptions {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'scoreThreshold': json['score_threshold'],
        'ranker': json['ranker'] == null ? undefined : json['ranker'],
    };
}

export function FileSearchRankingOptionsToJSON(json: any): FileSearchRankingOptions {
    return FileSearchRankingOptionsToJSONTyped(json, false);
}

export function FileSearchRankingOptionsToJSONTyped(value?: FileSearchRankingOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'score_threshold': value['scoreThreshold'],
        'ranker': value['ranker'],
    };
}

