/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileSearchRankingOptions } from './FileSearchRankingOptions';
import {
    FileSearchRankingOptionsFromJSON,
    FileSearchRankingOptionsFromJSONTyped,
    FileSearchRankingOptionsToJSON,
    FileSearchRankingOptionsToJSONTyped,
} from './FileSearchRankingOptions';

/**
 * 
 * @export
 * @interface FileSearch
 */
export interface FileSearch {
    [key: string]: any | any;
    /**
     * 
     * @type {number}
     * @memberof FileSearch
     */
    maxNumResults?: number | null;
    /**
     * 
     * @type {FileSearchRankingOptions}
     * @memberof FileSearch
     */
    rankingOptions?: FileSearchRankingOptions | null;
}

/**
 * Check if a given object implements the FileSearch interface.
 */
export function instanceOfFileSearch(value: object): value is FileSearch {
    return true;
}

export function FileSearchFromJSON(json: any): FileSearch {
    return FileSearchFromJSONTyped(json, false);
}

export function FileSearchFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileSearch {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'maxNumResults': json['max_num_results'] == null ? undefined : json['max_num_results'],
        'rankingOptions': json['ranking_options'] == null ? undefined : FileSearchRankingOptionsFromJSON(json['ranking_options']),
    };
}

export function FileSearchToJSON(json: any): FileSearch {
    return FileSearchToJSONTyped(json, false);
}

export function FileSearchToJSONTyped(value?: FileSearch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'max_num_results': value['maxNumResults'],
        'ranking_options': FileSearchRankingOptionsToJSON(value['rankingOptions']),
    };
}

