/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FilePath } from './FilePath';
import {
    FilePathFromJSON,
    FilePathFromJSONTyped,
    FilePathToJSON,
    FilePathToJSONTyped,
} from './FilePath';

/**
 * 
 * @export
 * @interface FilePathAnnotation
 */
export interface FilePathAnnotation {
    [key: string]: any | any;
    /**
     * 
     * @type {number}
     * @memberof FilePathAnnotation
     */
    endIndex: number;
    /**
     * 
     * @type {FilePath}
     * @memberof FilePathAnnotation
     */
    filePath: FilePath;
    /**
     * 
     * @type {number}
     * @memberof FilePathAnnotation
     */
    startIndex: number;
    /**
     * 
     * @type {string}
     * @memberof FilePathAnnotation
     */
    text: string;
    /**
     * 
     * @type {string}
     * @memberof FilePathAnnotation
     */
    type: FilePathAnnotationTypeEnum;
}


/**
 * @export
 */
export const FilePathAnnotationTypeEnum = {
    FilePath: 'file_path'
} as const;
export type FilePathAnnotationTypeEnum = typeof FilePathAnnotationTypeEnum[keyof typeof FilePathAnnotationTypeEnum];


/**
 * Check if a given object implements the FilePathAnnotation interface.
 */
export function instanceOfFilePathAnnotation(value: object): value is FilePathAnnotation {
    if (!('endIndex' in value) || value['endIndex'] === undefined) return false;
    if (!('filePath' in value) || value['filePath'] === undefined) return false;
    if (!('startIndex' in value) || value['startIndex'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function FilePathAnnotationFromJSON(json: any): FilePathAnnotation {
    return FilePathAnnotationFromJSONTyped(json, false);
}

export function FilePathAnnotationFromJSONTyped(json: any, ignoreDiscriminator: boolean): FilePathAnnotation {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'endIndex': json['end_index'],
        'filePath': FilePathFromJSON(json['file_path']),
        'startIndex': json['start_index'],
        'text': json['text'],
        'type': json['type'],
    };
}

export function FilePathAnnotationToJSON(json: any): FilePathAnnotation {
    return FilePathAnnotationToJSONTyped(json, false);
}

export function FilePathAnnotationToJSONTyped(value?: FilePathAnnotation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'end_index': value['endIndex'],
        'file_path': FilePathToJSON(value['filePath']),
        'start_index': value['startIndex'],
        'text': value['text'],
        'type': value['type'],
    };
}

