/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ForkOf
 */
export interface ForkOf {
    /**
     * 
     * @type {string}
     * @memberof ForkOf
     */
    namespace: string;
    /**
     * 
     * @type {string}
     * @memberof ForkOf
     */
    name: string;
}

/**
 * Check if a given object implements the ForkOf interface.
 */
export function instanceOfForkOf(value: object): value is ForkOf {
    if (!('namespace' in value) || value['namespace'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ForkOfFromJSON(json: any): ForkOf {
    return ForkOfFromJSONTyped(json, false);
}

export function ForkOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForkOf {
    if (json == null) {
        return json;
    }
    return {
        
        'namespace': json['namespace'],
        'name': json['name'],
    };
}

export function ForkOfToJSON(json: any): ForkOf {
    return ForkOfToJSONTyped(json, false);
}

export function ForkOfToJSONTyped(value?: ForkOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'namespace': value['namespace'],
        'name': value['name'],
    };
}

