/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntryLocation } from './EntryLocation';
import {
    EntryLocationFromJSON,
    EntryLocationFromJSONTyped,
    EntryLocationToJSON,
    EntryLocationToJSONTyped,
} from './EntryLocation';

/**
 * 
 * @export
 * @interface ForkResult
 */
export interface ForkResult {
    /**
     * 
     * @type {string}
     * @memberof ForkResult
     */
    status: string;
    /**
     * 
     * @type {EntryLocation}
     * @memberof ForkResult
     */
    entry: EntryLocation;
}

/**
 * Check if a given object implements the ForkResult interface.
 */
export function instanceOfForkResult(value: object): value is ForkResult {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('entry' in value) || value['entry'] === undefined) return false;
    return true;
}

export function ForkResultFromJSON(json: any): ForkResult {
    return ForkResultFromJSONTyped(json, false);
}

export function ForkResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForkResult {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'entry': EntryLocationFromJSON(json['entry']),
    };
}

export function ForkResultToJSON(json: any): ForkResult {
    return ForkResultToJSONTyped(json, false);
}

export function ForkResultToJSONTyped(value?: ForkResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'entry': EntryLocationToJSON(value['entry']),
    };
}

