/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ForkEntryModifications
 */
export interface ForkEntryModifications {
    /**
     * 
     * @type {string}
     * @memberof ForkEntryModifications
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ForkEntryModifications
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof ForkEntryModifications
     */
    version: string;
}

/**
 * Check if a given object implements the ForkEntryModifications interface.
 */
export function instanceOfForkEntryModifications(value: object): value is ForkEntryModifications {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function ForkEntryModificationsFromJSON(json: any): ForkEntryModifications {
    return ForkEntryModificationsFromJSONTyped(json, false);
}

export function ForkEntryModificationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForkEntryModifications {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'version': json['version'],
    };
}

export function ForkEntryModificationsToJSON(json: any): ForkEntryModifications {
    return ForkEntryModificationsToJSONTyped(json, false);
}

export function ForkEntryModificationsToJSONTyped(value?: ForkEntryModifications | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'version': value['version'],
    };
}

