/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FunctionDefinition
 */
export interface FunctionDefinition {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof FunctionDefinition
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof FunctionDefinition
     */
    description?: string | null;
    /**
     * 
     * @type {object}
     * @memberof FunctionDefinition
     */
    parameters?: object | null;
    /**
     * 
     * @type {boolean}
     * @memberof FunctionDefinition
     */
    strict?: boolean | null;
}

/**
 * Check if a given object implements the FunctionDefinition interface.
 */
export function instanceOfFunctionDefinition(value: object): value is FunctionDefinition {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function FunctionDefinitionFromJSON(json: any): FunctionDefinition {
    return FunctionDefinitionFromJSONTyped(json, false);
}

export function FunctionDefinitionFromJSONTyped(json: any, ignoreDiscriminator: boolean): FunctionDefinition {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'parameters': json['parameters'] == null ? undefined : json['parameters'],
        'strict': json['strict'] == null ? undefined : json['strict'],
    };
}

export function FunctionDefinitionToJSON(json: any): FunctionDefinition {
    return FunctionDefinitionToJSONTyped(json, false);
}

export function FunctionDefinitionToJSONTyped(value?: FunctionDefinition | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'name': value['name'],
        'description': value['description'],
        'parameters': value['parameters'],
        'strict': value['strict'],
    };
}

