/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FunctionDefinition } from './FunctionDefinition';
import {
    FunctionDefinitionFromJSON,
    FunctionDefinitionFromJSONTyped,
    FunctionDefinitionToJSON,
    FunctionDefinitionToJSONTyped,
} from './FunctionDefinition';

/**
 * 
 * @export
 * @interface FunctionTool
 */
export interface FunctionTool {
    [key: string]: any | any;
    /**
     * 
     * @type {FunctionDefinition}
     * @memberof FunctionTool
     */
    _function: FunctionDefinition;
    /**
     * 
     * @type {string}
     * @memberof FunctionTool
     */
    type: FunctionToolTypeEnum;
}


/**
 * @export
 */
export const FunctionToolTypeEnum = {
    Function: 'function'
} as const;
export type FunctionToolTypeEnum = typeof FunctionToolTypeEnum[keyof typeof FunctionToolTypeEnum];


/**
 * Check if a given object implements the FunctionTool interface.
 */
export function instanceOfFunctionTool(value: object): value is FunctionTool {
    if (!('_function' in value) || value['_function'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function FunctionToolFromJSON(json: any): FunctionTool {
    return FunctionToolFromJSONTyped(json, false);
}

export function FunctionToolFromJSONTyped(json: any, ignoreDiscriminator: boolean): FunctionTool {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        '_function': FunctionDefinitionFromJSON(json['function']),
        'type': json['type'],
    };
}

export function FunctionToolToJSON(json: any): FunctionTool {
    return FunctionToolToJSONTyped(json, false);
}

export function FunctionToolToJSONTyped(value?: FunctionTool | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'function': FunctionDefinitionToJSON(value['_function']),
        'type': value['type'],
    };
}

