/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GitLabSource
 */
export interface GitLabSource {
    /**
     * 
     * @type {string}
     * @memberof GitLabSource
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof GitLabSource
     */
    owner: string;
    /**
     * 
     * @type {string}
     * @memberof GitLabSource
     */
    repo: string;
    /**
     * 
     * @type {string}
     * @memberof GitLabSource
     */
    branch?: string;
}

/**
 * Check if a given object implements the GitLabSource interface.
 */
export function instanceOfGitLabSource(value: object): value is GitLabSource {
    if (!('owner' in value) || value['owner'] === undefined) return false;
    if (!('repo' in value) || value['repo'] === undefined) return false;
    return true;
}

export function GitLabSourceFromJSON(json: any): GitLabSource {
    return GitLabSourceFromJSONTyped(json, false);
}

export function GitLabSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): GitLabSource {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'owner': json['owner'],
        'repo': json['repo'],
        'branch': json['branch'] == null ? undefined : json['branch'],
    };
}

export function GitLabSourceToJSON(json: any): GitLabSource {
    return GitLabSourceToJSONTyped(json, false);
}

export function GitLabSourceToJSONTyped(value?: GitLabSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'owner': value['owner'],
        'repo': value['repo'],
        'branch': value['branch'],
    };
}

