/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImageURLParam } from './ImageURLParam';
import {
    ImageURLParamFromJSON,
    ImageURLParamFromJSONTyped,
    ImageURLParamToJSON,
    ImageURLParamToJSONTyped,
} from './ImageURLParam';

/**
 * 
 * @export
 * @interface ImageURLContentBlockParam
 */
export interface ImageURLContentBlockParam {
    /**
     * 
     * @type {ImageURLParam}
     * @memberof ImageURLContentBlockParam
     */
    imageUrl: ImageURLParam;
    /**
     * 
     * @type {string}
     * @memberof ImageURLContentBlockParam
     */
    type: ImageURLContentBlockParamTypeEnum;
}


/**
 * @export
 */
export const ImageURLContentBlockParamTypeEnum = {
    ImageUrl: 'image_url'
} as const;
export type ImageURLContentBlockParamTypeEnum = typeof ImageURLContentBlockParamTypeEnum[keyof typeof ImageURLContentBlockParamTypeEnum];


/**
 * Check if a given object implements the ImageURLContentBlockParam interface.
 */
export function instanceOfImageURLContentBlockParam(value: object): value is ImageURLContentBlockParam {
    if (!('imageUrl' in value) || value['imageUrl'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ImageURLContentBlockParamFromJSON(json: any): ImageURLContentBlockParam {
    return ImageURLContentBlockParamFromJSONTyped(json, false);
}

export function ImageURLContentBlockParamFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageURLContentBlockParam {
    if (json == null) {
        return json;
    }
    return {
        
        'imageUrl': ImageURLParamFromJSON(json['image_url']),
        'type': json['type'],
    };
}

export function ImageURLContentBlockParamToJSON(json: any): ImageURLContentBlockParam {
    return ImageURLContentBlockParamToJSONTyped(json, false);
}

export function ImageURLContentBlockParamToJSONTyped(value?: ImageURLContentBlockParam | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'image_url': ImageURLParamToJSON(value['imageUrl']),
        'type': value['type'],
    };
}

