/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImageURL
 */
export interface ImageURL {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof ImageURL
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof ImageURL
     */
    detail?: ImageURLDetailEnum | null;
}


/**
 * @export
 */
export const ImageURLDetailEnum = {
    Auto: 'auto',
    Low: 'low',
    High: 'high'
} as const;
export type ImageURLDetailEnum = typeof ImageURLDetailEnum[keyof typeof ImageURLDetailEnum];


/**
 * Check if a given object implements the ImageURL interface.
 */
export function instanceOfImageURL(value: object): value is ImageURL {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function ImageURLFromJSON(json: any): ImageURL {
    return ImageURLFromJSONTyped(json, false);
}

export function ImageURLFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageURL {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'url': json['url'],
        'detail': json['detail'] == null ? undefined : json['detail'],
    };
}

export function ImageURLToJSON(json: any): ImageURL {
    return ImageURLToJSONTyped(json, false);
}

export function ImageURLToJSONTyped(value?: ImageURL | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'url': value['url'],
        'detail': value['detail'],
    };
}

