/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImageFileParam } from './ImageFileParam';
import {
    ImageFileParamFromJSON,
    ImageFileParamFromJSONTyped,
    ImageFileParamToJSON,
    ImageFileParamToJSONTyped,
} from './ImageFileParam';

/**
 * 
 * @export
 * @interface ImageFileContentBlockParam
 */
export interface ImageFileContentBlockParam {
    /**
     * 
     * @type {ImageFileParam}
     * @memberof ImageFileContentBlockParam
     */
    imageFile: ImageFileParam;
    /**
     * 
     * @type {string}
     * @memberof ImageFileContentBlockParam
     */
    type: ImageFileContentBlockParamTypeEnum;
}


/**
 * @export
 */
export const ImageFileContentBlockParamTypeEnum = {
    ImageFile: 'image_file'
} as const;
export type ImageFileContentBlockParamTypeEnum = typeof ImageFileContentBlockParamTypeEnum[keyof typeof ImageFileContentBlockParamTypeEnum];


/**
 * Check if a given object implements the ImageFileContentBlockParam interface.
 */
export function instanceOfImageFileContentBlockParam(value: object): value is ImageFileContentBlockParam {
    if (!('imageFile' in value) || value['imageFile'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ImageFileContentBlockParamFromJSON(json: any): ImageFileContentBlockParam {
    return ImageFileContentBlockParamFromJSONTyped(json, false);
}

export function ImageFileContentBlockParamFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageFileContentBlockParam {
    if (json == null) {
        return json;
    }
    return {
        
        'imageFile': ImageFileParamFromJSON(json['image_file']),
        'type': json['type'],
    };
}

export function ImageFileContentBlockParamToJSON(json: any): ImageFileContentBlockParam {
    return ImageFileContentBlockParamToJSONTyped(json, false);
}

export function ImageFileContentBlockParamToJSONTyped(value?: ImageFileContentBlockParam | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'image_file': ImageFileParamToJSON(value['imageFile']),
        'type': value['type'],
    };
}

