/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImageURL } from './ImageURL';
import {
    ImageURLFromJSON,
    ImageURLFromJSONTyped,
    ImageURLToJSON,
    ImageURLToJSONTyped,
} from './ImageURL';

/**
 * 
 * @export
 * @interface ImageURLContentBlock
 */
export interface ImageURLContentBlock {
    [key: string]: any | any;
    /**
     * 
     * @type {ImageURL}
     * @memberof ImageURLContentBlock
     */
    imageUrl: ImageURL;
    /**
     * 
     * @type {string}
     * @memberof ImageURLContentBlock
     */
    type: ImageURLContentBlockTypeEnum;
}


/**
 * @export
 */
export const ImageURLContentBlockTypeEnum = {
    ImageUrl: 'image_url'
} as const;
export type ImageURLContentBlockTypeEnum = typeof ImageURLContentBlockTypeEnum[keyof typeof ImageURLContentBlockTypeEnum];


/**
 * Check if a given object implements the ImageURLContentBlock interface.
 */
export function instanceOfImageURLContentBlock(value: object): value is ImageURLContentBlock {
    if (!('imageUrl' in value) || value['imageUrl'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ImageURLContentBlockFromJSON(json: any): ImageURLContentBlock {
    return ImageURLContentBlockFromJSONTyped(json, false);
}

export function ImageURLContentBlockFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageURLContentBlock {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'imageUrl': ImageURLFromJSON(json['image_url']),
        'type': json['type'],
    };
}

export function ImageURLContentBlockToJSON(json: any): ImageURLContentBlock {
    return ImageURLContentBlockToJSONTyped(json, false);
}

export function ImageURLContentBlockToJSONTyped(value?: ImageURLContentBlock | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'image_url': ImageURLToJSON(value['imageUrl']),
        'type': value['type'],
    };
}

