/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImageFile
 */
export interface ImageFile {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof ImageFile
     */
    fileId: string;
    /**
     * 
     * @type {string}
     * @memberof ImageFile
     */
    detail?: ImageFileDetailEnum | null;
}


/**
 * @export
 */
export const ImageFileDetailEnum = {
    Auto: 'auto',
    Low: 'low',
    High: 'high'
} as const;
export type ImageFileDetailEnum = typeof ImageFileDetailEnum[keyof typeof ImageFileDetailEnum];


/**
 * Check if a given object implements the ImageFile interface.
 */
export function instanceOfImageFile(value: object): value is ImageFile {
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    return true;
}

export function ImageFileFromJSON(json: any): ImageFile {
    return ImageFileFromJSONTyped(json, false);
}

export function ImageFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageFile {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'fileId': json['file_id'],
        'detail': json['detail'] == null ? undefined : json['detail'],
    };
}

export function ImageFileToJSON(json: any): ImageFile {
    return ImageFileToJSONTyped(json, false);
}

export function ImageFileToJSONTyped(value?: ImageFile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'file_id': value['fileId'],
        'detail': value['detail'],
    };
}

