/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LastError
 */
export interface LastError {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof LastError
     */
    code: LastErrorCodeEnum;
    /**
     * 
     * @type {string}
     * @memberof LastError
     */
    message: string;
}


/**
 * @export
 */
export const LastErrorCodeEnum = {
    ServerError: 'server_error',
    RateLimitExceeded: 'rate_limit_exceeded',
    InvalidPrompt: 'invalid_prompt'
} as const;
export type LastErrorCodeEnum = typeof LastErrorCodeEnum[keyof typeof LastErrorCodeEnum];


/**
 * Check if a given object implements the LastError interface.
 */
export function instanceOfLastError(value: object): value is LastError {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function LastErrorFromJSON(json: any): LastError {
    return LastErrorFromJSONTyped(json, false);
}

export function LastErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): LastError {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'code': json['code'],
        'message': json['message'],
    };
}

export function LastErrorToJSON(json: any): LastError {
    return LastErrorToJSONTyped(json, false);
}

export function LastErrorToJSONTyped(value?: LastError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'code': value['code'],
        'message': value['message'],
    };
}

