/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Content } from './Content';
import {
    ContentFromJSON,
    ContentFromJSONTyped,
    ContentToJSON,
    ContentToJSONTyped,
} from './Content';
import type { Attachment } from './Attachment';
import {
    AttachmentFromJSON,
    AttachmentFromJSONTyped,
    AttachmentToJSON,
    AttachmentToJSONTyped,
} from './Attachment';

/**
 * 
 * @export
 * @interface MessageCreateParams
 */
export interface MessageCreateParams {
    [key: string]: any | any;
    /**
     * 
     * @type {Content}
     * @memberof MessageCreateParams
     */
    content: Content;
    /**
     * 
     * @type {string}
     * @memberof MessageCreateParams
     */
    role: MessageCreateParamsRoleEnum;
    /**
     * 
     * @type {Array<Attachment>}
     * @memberof MessageCreateParams
     */
    attachments?: Array<Attachment> | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof MessageCreateParams
     */
    metadata?: { [key: string]: string; } | null;
    /**
     * 
     * @type {string}
     * @memberof MessageCreateParams
     */
    assistantId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MessageCreateParams
     */
    runId?: string | null;
}


/**
 * @export
 */
export const MessageCreateParamsRoleEnum = {
    User: 'user',
    Assistant: 'assistant',
    System: 'system'
} as const;
export type MessageCreateParamsRoleEnum = typeof MessageCreateParamsRoleEnum[keyof typeof MessageCreateParamsRoleEnum];


/**
 * Check if a given object implements the MessageCreateParams interface.
 */
export function instanceOfMessageCreateParams(value: object): value is MessageCreateParams {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function MessageCreateParamsFromJSON(json: any): MessageCreateParams {
    return MessageCreateParamsFromJSONTyped(json, false);
}

export function MessageCreateParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageCreateParams {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'content': ContentFromJSON(json['content']),
        'role': json['role'],
        'attachments': json['attachments'] == null ? undefined : ((json['attachments'] as Array<any>).map(AttachmentFromJSON)),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'assistantId': json['assistant_id'] == null ? undefined : json['assistant_id'],
        'runId': json['run_id'] == null ? undefined : json['run_id'],
    };
}

export function MessageCreateParamsToJSON(json: any): MessageCreateParams {
    return MessageCreateParamsToJSONTyped(json, false);
}

export function MessageCreateParamsToJSONTyped(value?: MessageCreateParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'content': ContentToJSON(value['content']),
        'role': value['role'],
        'attachments': value['attachments'] == null ? undefined : ((value['attachments'] as Array<any>).map(AttachmentToJSON)),
        'metadata': value['metadata'],
        'assistant_id': value['assistantId'],
        'run_id': value['runId'],
    };
}

