/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessageAttachmentToolFileSearch
 */
export interface MessageAttachmentToolFileSearch {
    /**
     * 
     * @type {string}
     * @memberof MessageAttachmentToolFileSearch
     */
    type: MessageAttachmentToolFileSearchTypeEnum;
}


/**
 * @export
 */
export const MessageAttachmentToolFileSearchTypeEnum = {
    FileSearch: 'file_search'
} as const;
export type MessageAttachmentToolFileSearchTypeEnum = typeof MessageAttachmentToolFileSearchTypeEnum[keyof typeof MessageAttachmentToolFileSearchTypeEnum];


/**
 * Check if a given object implements the MessageAttachmentToolFileSearch interface.
 */
export function instanceOfMessageAttachmentToolFileSearch(value: object): value is MessageAttachmentToolFileSearch {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function MessageAttachmentToolFileSearchFromJSON(json: any): MessageAttachmentToolFileSearch {
    return MessageAttachmentToolFileSearchFromJSONTyped(json, false);
}

export function MessageAttachmentToolFileSearchFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageAttachmentToolFileSearch {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
    };
}

export function MessageAttachmentToolFileSearchToJSON(json: any): MessageAttachmentToolFileSearch {
    return MessageAttachmentToolFileSearchToJSONTyped(json, false);
}

export function MessageAttachmentToolFileSearchToJSONTyped(value?: MessageAttachmentToolFileSearch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
    };
}

