/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImageFile } from './ImageFile';
import {
    ImageFileFromJSON,
    ImageFileFromJSONTyped,
    ImageFileToJSON,
    ImageFileToJSONTyped,
} from './ImageFile';
import type { ImageURLContentBlock } from './ImageURLContentBlock';
import {
    ImageURLContentBlockFromJSON,
    ImageURLContentBlockFromJSONTyped,
    ImageURLContentBlockToJSON,
    ImageURLContentBlockToJSONTyped,
} from './ImageURLContentBlock';
import type { TextContentBlock } from './TextContentBlock';
import {
    TextContentBlockFromJSON,
    TextContentBlockFromJSONTyped,
    TextContentBlockToJSON,
    TextContentBlockToJSONTyped,
} from './TextContentBlock';
import type { ImageFileContentBlock } from './ImageFileContentBlock';
import {
    ImageFileContentBlockFromJSON,
    ImageFileContentBlockFromJSONTyped,
    ImageFileContentBlockToJSON,
    ImageFileContentBlockToJSONTyped,
} from './ImageFileContentBlock';
import type { ImageURL } from './ImageURL';
import {
    ImageURLFromJSON,
    ImageURLFromJSONTyped,
    ImageURLToJSON,
    ImageURLToJSONTyped,
} from './ImageURL';
import type { Text } from './Text';
import {
    TextFromJSON,
    TextFromJSONTyped,
    TextToJSON,
    TextToJSONTyped,
} from './Text';
import type { RefusalContentBlock } from './RefusalContentBlock';
import {
    RefusalContentBlockFromJSON,
    RefusalContentBlockFromJSONTyped,
    RefusalContentBlockToJSON,
    RefusalContentBlockToJSONTyped,
} from './RefusalContentBlock';

/**
 * 
 * @export
 * @interface MessageOutputContentInner
 */
export interface MessageOutputContentInner {
    /**
     * 
     * @type {ImageFile}
     * @memberof MessageOutputContentInner
     */
    imageFile: ImageFile;
    /**
     * 
     * @type {string}
     * @memberof MessageOutputContentInner
     */
    type: MessageOutputContentInnerTypeEnum;
    /**
     * 
     * @type {ImageURL}
     * @memberof MessageOutputContentInner
     */
    imageUrl: ImageURL;
    /**
     * 
     * @type {Text}
     * @memberof MessageOutputContentInner
     */
    text: Text;
    /**
     * 
     * @type {string}
     * @memberof MessageOutputContentInner
     */
    refusal: string;
}


/**
 * @export
 */
export const MessageOutputContentInnerTypeEnum = {
    ImageFile: 'image_file',
    ImageUrl: 'image_url',
    Text: 'text',
    Refusal: 'refusal'
} as const;
export type MessageOutputContentInnerTypeEnum = typeof MessageOutputContentInnerTypeEnum[keyof typeof MessageOutputContentInnerTypeEnum];


/**
 * Check if a given object implements the MessageOutputContentInner interface.
 */
export function instanceOfMessageOutputContentInner(value: object): value is MessageOutputContentInner {
    if (!('imageFile' in value) || value['imageFile'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('imageUrl' in value) || value['imageUrl'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('refusal' in value) || value['refusal'] === undefined) return false;
    return true;
}

export function MessageOutputContentInnerFromJSON(json: any): MessageOutputContentInner {
    return MessageOutputContentInnerFromJSONTyped(json, false);
}

export function MessageOutputContentInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageOutputContentInner {
    if (json == null) {
        return json;
    }
    return {
        
        'imageFile': ImageFileFromJSON(json['image_file']),
        'type': json['type'],
        'imageUrl': ImageURLFromJSON(json['image_url']),
        'text': TextFromJSON(json['text']),
        'refusal': json['refusal'],
    };
}

export function MessageOutputContentInnerToJSON(json: any): MessageOutputContentInner {
    return MessageOutputContentInnerToJSONTyped(json, false);
}

export function MessageOutputContentInnerToJSONTyped(value?: MessageOutputContentInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'image_file': ImageFileToJSON(value['imageFile']),
        'type': value['type'],
        'image_url': ImageURLToJSON(value['imageUrl']),
        'text': TextToJSON(value['text']),
        'refusal': value['refusal'],
    };
}

