/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OpenaiTypesBetaThreadsMessageIncompleteDetails } from './OpenaiTypesBetaThreadsMessageIncompleteDetails';
import {
    OpenaiTypesBetaThreadsMessageIncompleteDetailsFromJSON,
    OpenaiTypesBetaThreadsMessageIncompleteDetailsFromJSONTyped,
    OpenaiTypesBetaThreadsMessageIncompleteDetailsToJSON,
    OpenaiTypesBetaThreadsMessageIncompleteDetailsToJSONTyped,
} from './OpenaiTypesBetaThreadsMessageIncompleteDetails';
import type { Attachment } from './Attachment';
import {
    AttachmentFromJSON,
    AttachmentFromJSONTyped,
    AttachmentToJSON,
    AttachmentToJSONTyped,
} from './Attachment';
import type { MessageOutputContentInner } from './MessageOutputContentInner';
import {
    MessageOutputContentInnerFromJSON,
    MessageOutputContentInnerFromJSONTyped,
    MessageOutputContentInnerToJSON,
    MessageOutputContentInnerToJSONTyped,
} from './MessageOutputContentInner';

/**
 * 
 * @export
 * @interface MessageOutput
 */
export interface MessageOutput {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof MessageOutput
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof MessageOutput
     */
    assistantId?: string | null;
    /**
     * 
     * @type {Array<Attachment>}
     * @memberof MessageOutput
     */
    attachments?: Array<Attachment> | null;
    /**
     * 
     * @type {number}
     * @memberof MessageOutput
     */
    completedAt?: number | null;
    /**
     * 
     * @type {Array<MessageOutputContentInner>}
     * @memberof MessageOutput
     */
    content: Array<MessageOutputContentInner>;
    /**
     * 
     * @type {number}
     * @memberof MessageOutput
     */
    createdAt: number;
    /**
     * 
     * @type {number}
     * @memberof MessageOutput
     */
    incompleteAt?: number | null;
    /**
     * 
     * @type {OpenaiTypesBetaThreadsMessageIncompleteDetails}
     * @memberof MessageOutput
     */
    incompleteDetails?: OpenaiTypesBetaThreadsMessageIncompleteDetails | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof MessageOutput
     */
    metadata?: { [key: string]: string; } | null;
    /**
     * 
     * @type {string}
     * @memberof MessageOutput
     */
    object: MessageOutputObjectEnum;
    /**
     * 
     * @type {string}
     * @memberof MessageOutput
     */
    role: MessageOutputRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof MessageOutput
     */
    runId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MessageOutput
     */
    status: MessageOutputStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof MessageOutput
     */
    threadId: string;
}


/**
 * @export
 */
export const MessageOutputObjectEnum = {
    ThreadMessage: 'thread.message'
} as const;
export type MessageOutputObjectEnum = typeof MessageOutputObjectEnum[keyof typeof MessageOutputObjectEnum];

/**
 * @export
 */
export const MessageOutputRoleEnum = {
    User: 'user',
    Assistant: 'assistant'
} as const;
export type MessageOutputRoleEnum = typeof MessageOutputRoleEnum[keyof typeof MessageOutputRoleEnum];

/**
 * @export
 */
export const MessageOutputStatusEnum = {
    InProgress: 'in_progress',
    Incomplete: 'incomplete',
    Completed: 'completed'
} as const;
export type MessageOutputStatusEnum = typeof MessageOutputStatusEnum[keyof typeof MessageOutputStatusEnum];


/**
 * Check if a given object implements the MessageOutput interface.
 */
export function instanceOfMessageOutput(value: object): value is MessageOutput {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('threadId' in value) || value['threadId'] === undefined) return false;
    return true;
}

export function MessageOutputFromJSON(json: any): MessageOutput {
    return MessageOutputFromJSONTyped(json, false);
}

export function MessageOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageOutput {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'],
        'assistantId': json['assistant_id'] == null ? undefined : json['assistant_id'],
        'attachments': json['attachments'] == null ? undefined : ((json['attachments'] as Array<any>).map(AttachmentFromJSON)),
        'completedAt': json['completed_at'] == null ? undefined : json['completed_at'],
        'content': ((json['content'] as Array<any>).map(MessageOutputContentInnerFromJSON)),
        'createdAt': json['created_at'],
        'incompleteAt': json['incomplete_at'] == null ? undefined : json['incomplete_at'],
        'incompleteDetails': json['incomplete_details'] == null ? undefined : OpenaiTypesBetaThreadsMessageIncompleteDetailsFromJSON(json['incomplete_details']),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'object': json['object'],
        'role': json['role'],
        'runId': json['run_id'] == null ? undefined : json['run_id'],
        'status': json['status'],
        'threadId': json['thread_id'],
    };
}

export function MessageOutputToJSON(json: any): MessageOutput {
    return MessageOutputToJSONTyped(json, false);
}

export function MessageOutputToJSONTyped(value?: MessageOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'id': value['id'],
        'assistant_id': value['assistantId'],
        'attachments': value['attachments'] == null ? undefined : ((value['attachments'] as Array<any>).map(AttachmentToJSON)),
        'completed_at': value['completedAt'],
        'content': ((value['content'] as Array<any>).map(MessageOutputContentInnerToJSON)),
        'created_at': value['createdAt'],
        'incomplete_at': value['incompleteAt'],
        'incomplete_details': OpenaiTypesBetaThreadsMessageIncompleteDetailsToJSON(value['incompleteDetails']),
        'metadata': value['metadata'],
        'object': value['object'],
        'role': value['role'],
        'run_id': value['runId'],
        'status': value['status'],
        'thread_id': value['threadId'],
    };
}

