/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MessageAttachmentToolsInner } from './MessageAttachmentToolsInner';
import {
    MessageAttachmentToolsInnerFromJSON,
    MessageAttachmentToolsInnerFromJSONTyped,
    MessageAttachmentToolsInnerToJSON,
    MessageAttachmentToolsInnerToJSONTyped,
} from './MessageAttachmentToolsInner';

/**
 * 
 * @export
 * @interface MessageAttachment
 */
export interface MessageAttachment {
    /**
     * 
     * @type {string}
     * @memberof MessageAttachment
     */
    fileId?: string;
    /**
     * 
     * @type {Array<MessageAttachmentToolsInner>}
     * @memberof MessageAttachment
     */
    tools?: Array<MessageAttachmentToolsInner>;
}

/**
 * Check if a given object implements the MessageAttachment interface.
 */
export function instanceOfMessageAttachment(value: object): value is MessageAttachment {
    return true;
}

export function MessageAttachmentFromJSON(json: any): MessageAttachment {
    return MessageAttachmentFromJSONTyped(json, false);
}

export function MessageAttachmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageAttachment {
    if (json == null) {
        return json;
    }
    return {
        
        'fileId': json['file_id'] == null ? undefined : json['file_id'],
        'tools': json['tools'] == null ? undefined : ((json['tools'] as Array<any>).map(MessageAttachmentToolsInnerFromJSON)),
    };
}

export function MessageAttachmentToJSON(json: any): MessageAttachment {
    return MessageAttachmentToJSONTyped(json, false);
}

export function MessageAttachmentToJSONTyped(value?: MessageAttachment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'file_id': value['fileId'],
        'tools': value['tools'] == null ? undefined : ((value['tools'] as Array<any>).map(MessageAttachmentToolsInnerToJSON)),
    };
}

