/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessageUpdateParams
 */
export interface MessageUpdateParams {
    /**
     * 
     * @type {string}
     * @memberof MessageUpdateParams
     */
    threadId: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof MessageUpdateParams
     */
    metadata?: { [key: string]: string; } | null;
}

/**
 * Check if a given object implements the MessageUpdateParams interface.
 */
export function instanceOfMessageUpdateParams(value: object): value is MessageUpdateParams {
    if (!('threadId' in value) || value['threadId'] === undefined) return false;
    return true;
}

export function MessageUpdateParamsFromJSON(json: any): MessageUpdateParams {
    return MessageUpdateParamsFromJSONTyped(json, false);
}

export function MessageUpdateParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageUpdateParams {
    if (json == null) {
        return json;
    }
    return {
        
        'threadId': json['thread_id'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function MessageUpdateParamsToJSON(json: any): MessageUpdateParams {
    return MessageUpdateParamsToJSONTyped(json, false);
}

export function MessageUpdateParamsToJSONTyped(value?: MessageUpdateParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'thread_id': value['threadId'],
        'metadata': value['metadata'],
    };
}

