/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MessageAttachment } from './MessageAttachment';
import {
    MessageAttachmentFromJSON,
    MessageAttachmentFromJSONTyped,
    MessageAttachmentToJSON,
    MessageAttachmentToJSONTyped,
} from './MessageAttachment';
import type { Content } from './Content';
import {
    ContentFromJSON,
    ContentFromJSONTyped,
    ContentToJSON,
    ContentToJSONTyped,
} from './Content';

/**
 * 
 * @export
 * @interface OpenaiTypesBetaThreadCreateParamsMessage
 */
export interface OpenaiTypesBetaThreadCreateParamsMessage {
    /**
     * 
     * @type {Content}
     * @memberof OpenaiTypesBetaThreadCreateParamsMessage
     */
    content: Content;
    /**
     * 
     * @type {string}
     * @memberof OpenaiTypesBetaThreadCreateParamsMessage
     */
    role: OpenaiTypesBetaThreadCreateParamsMessageRoleEnum;
    /**
     * 
     * @type {Array<MessageAttachment>}
     * @memberof OpenaiTypesBetaThreadCreateParamsMessage
     */
    attachments?: Array<MessageAttachment> | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof OpenaiTypesBetaThreadCreateParamsMessage
     */
    metadata?: { [key: string]: string; } | null;
}


/**
 * @export
 */
export const OpenaiTypesBetaThreadCreateParamsMessageRoleEnum = {
    User: 'user',
    Assistant: 'assistant'
} as const;
export type OpenaiTypesBetaThreadCreateParamsMessageRoleEnum = typeof OpenaiTypesBetaThreadCreateParamsMessageRoleEnum[keyof typeof OpenaiTypesBetaThreadCreateParamsMessageRoleEnum];


/**
 * Check if a given object implements the OpenaiTypesBetaThreadCreateParamsMessage interface.
 */
export function instanceOfOpenaiTypesBetaThreadCreateParamsMessage(value: object): value is OpenaiTypesBetaThreadCreateParamsMessage {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function OpenaiTypesBetaThreadCreateParamsMessageFromJSON(json: any): OpenaiTypesBetaThreadCreateParamsMessage {
    return OpenaiTypesBetaThreadCreateParamsMessageFromJSONTyped(json, false);
}

export function OpenaiTypesBetaThreadCreateParamsMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenaiTypesBetaThreadCreateParamsMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'content': ContentFromJSON(json['content']),
        'role': json['role'],
        'attachments': json['attachments'] == null ? undefined : ((json['attachments'] as Array<any>).map(MessageAttachmentFromJSON)),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function OpenaiTypesBetaThreadCreateParamsMessageToJSON(json: any): OpenaiTypesBetaThreadCreateParamsMessage {
    return OpenaiTypesBetaThreadCreateParamsMessageToJSONTyped(json, false);
}

export function OpenaiTypesBetaThreadCreateParamsMessageToJSONTyped(value?: OpenaiTypesBetaThreadCreateParamsMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': ContentToJSON(value['content']),
        'role': value['role'],
        'attachments': value['attachments'] == null ? undefined : ((value['attachments'] as Array<any>).map(MessageAttachmentToJSON)),
        'metadata': value['metadata'],
    };
}

