/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OpenaiTypesSharedParamsResponseFormatJsonObjectResponseFormatJSONObject
 */
export interface OpenaiTypesSharedParamsResponseFormatJsonObjectResponseFormatJSONObject {
    /**
     * 
     * @type {string}
     * @memberof OpenaiTypesSharedParamsResponseFormatJsonObjectResponseFormatJSONObject
     */
    type: OpenaiTypesSharedParamsResponseFormatJsonObjectResponseFormatJSONObjectTypeEnum;
}


/**
 * @export
 */
export const OpenaiTypesSharedParamsResponseFormatJsonObjectResponseFormatJSONObjectTypeEnum = {
    JsonObject: 'json_object'
} as const;
export type OpenaiTypesSharedParamsResponseFormatJsonObjectResponseFormatJSONObjectTypeEnum = typeof OpenaiTypesSharedParamsResponseFormatJsonObjectResponseFormatJSONObjectTypeEnum[keyof typeof OpenaiTypesSharedParamsResponseFormatJsonObjectResponseFormatJSONObjectTypeEnum];


/**
 * Check if a given object implements the OpenaiTypesSharedParamsResponseFormatJsonObjectResponseFormatJSONObject interface.
 */
export function instanceOfOpenaiTypesSharedParamsResponseFormatJsonObjectResponseFormatJSONObject(value: object): value is OpenaiTypesSharedParamsResponseFormatJsonObjectResponseFormatJSONObject {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function OpenaiTypesSharedParamsResponseFormatJsonObjectResponseFormatJSONObjectFromJSON(json: any): OpenaiTypesSharedParamsResponseFormatJsonObjectResponseFormatJSONObject {
    return OpenaiTypesSharedParamsResponseFormatJsonObjectResponseFormatJSONObjectFromJSONTyped(json, false);
}

export function OpenaiTypesSharedParamsResponseFormatJsonObjectResponseFormatJSONObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenaiTypesSharedParamsResponseFormatJsonObjectResponseFormatJSONObject {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
    };
}

export function OpenaiTypesSharedParamsResponseFormatJsonObjectResponseFormatJSONObjectToJSON(json: any): OpenaiTypesSharedParamsResponseFormatJsonObjectResponseFormatJSONObject {
    return OpenaiTypesSharedParamsResponseFormatJsonObjectResponseFormatJSONObjectToJSONTyped(json, false);
}

export function OpenaiTypesSharedParamsResponseFormatJsonObjectResponseFormatJSONObjectToJSONTyped(value?: OpenaiTypesSharedParamsResponseFormatJsonObjectResponseFormatJSONObject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
    };
}

