/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OpenaiTypesSharedResponseFormatJsonSchemaJSONSchema
 */
export interface OpenaiTypesSharedResponseFormatJsonSchemaJSONSchema {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof OpenaiTypesSharedResponseFormatJsonSchemaJSONSchema
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof OpenaiTypesSharedResponseFormatJsonSchemaJSONSchema
     */
    description?: string | null;
    /**
     * 
     * @type {object}
     * @memberof OpenaiTypesSharedResponseFormatJsonSchemaJSONSchema
     */
    schema?: object | null;
    /**
     * 
     * @type {boolean}
     * @memberof OpenaiTypesSharedResponseFormatJsonSchemaJSONSchema
     */
    strict?: boolean | null;
}

/**
 * Check if a given object implements the OpenaiTypesSharedResponseFormatJsonSchemaJSONSchema interface.
 */
export function instanceOfOpenaiTypesSharedResponseFormatJsonSchemaJSONSchema(value: object): value is OpenaiTypesSharedResponseFormatJsonSchemaJSONSchema {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function OpenaiTypesSharedResponseFormatJsonSchemaJSONSchemaFromJSON(json: any): OpenaiTypesSharedResponseFormatJsonSchemaJSONSchema {
    return OpenaiTypesSharedResponseFormatJsonSchemaJSONSchemaFromJSONTyped(json, false);
}

export function OpenaiTypesSharedResponseFormatJsonSchemaJSONSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenaiTypesSharedResponseFormatJsonSchemaJSONSchema {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'schema': json['schema'] == null ? undefined : json['schema'],
        'strict': json['strict'] == null ? undefined : json['strict'],
    };
}

export function OpenaiTypesSharedResponseFormatJsonSchemaJSONSchemaToJSON(json: any): OpenaiTypesSharedResponseFormatJsonSchemaJSONSchema {
    return OpenaiTypesSharedResponseFormatJsonSchemaJSONSchemaToJSONTyped(json, false);
}

export function OpenaiTypesSharedResponseFormatJsonSchemaJSONSchemaToJSONTyped(value?: OpenaiTypesSharedResponseFormatJsonSchemaJSONSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'name': value['name'],
        'description': value['description'],
        'schema': value['schema'],
        'strict': value['strict'],
    };
}

