/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OpenaiTypesSharedResponseFormatTextResponseFormatText
 */
export interface OpenaiTypesSharedResponseFormatTextResponseFormatText {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof OpenaiTypesSharedResponseFormatTextResponseFormatText
     */
    type: OpenaiTypesSharedResponseFormatTextResponseFormatTextTypeEnum;
}


/**
 * @export
 */
export const OpenaiTypesSharedResponseFormatTextResponseFormatTextTypeEnum = {
    Text: 'text'
} as const;
export type OpenaiTypesSharedResponseFormatTextResponseFormatTextTypeEnum = typeof OpenaiTypesSharedResponseFormatTextResponseFormatTextTypeEnum[keyof typeof OpenaiTypesSharedResponseFormatTextResponseFormatTextTypeEnum];


/**
 * Check if a given object implements the OpenaiTypesSharedResponseFormatTextResponseFormatText interface.
 */
export function instanceOfOpenaiTypesSharedResponseFormatTextResponseFormatText(value: object): value is OpenaiTypesSharedResponseFormatTextResponseFormatText {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function OpenaiTypesSharedResponseFormatTextResponseFormatTextFromJSON(json: any): OpenaiTypesSharedResponseFormatTextResponseFormatText {
    return OpenaiTypesSharedResponseFormatTextResponseFormatTextFromJSONTyped(json, false);
}

export function OpenaiTypesSharedResponseFormatTextResponseFormatTextFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenaiTypesSharedResponseFormatTextResponseFormatText {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'type': json['type'],
    };
}

export function OpenaiTypesSharedResponseFormatTextResponseFormatTextToJSON(json: any): OpenaiTypesSharedResponseFormatTextResponseFormatText {
    return OpenaiTypesSharedResponseFormatTextResponseFormatTextToJSONTyped(json, false);
}

export function OpenaiTypesSharedResponseFormatTextResponseFormatTextToJSONTyped(value?: OpenaiTypesSharedResponseFormatTextResponseFormatText | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'type': value['type'],
    };
}

