/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OpenaiTypesBetaThreadsRunIncompleteDetails
 */
export interface OpenaiTypesBetaThreadsRunIncompleteDetails {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof OpenaiTypesBetaThreadsRunIncompleteDetails
     */
    reason?: OpenaiTypesBetaThreadsRunIncompleteDetailsReasonEnum | null;
}


/**
 * @export
 */
export const OpenaiTypesBetaThreadsRunIncompleteDetailsReasonEnum = {
    MaxCompletionTokens: 'max_completion_tokens',
    MaxPromptTokens: 'max_prompt_tokens'
} as const;
export type OpenaiTypesBetaThreadsRunIncompleteDetailsReasonEnum = typeof OpenaiTypesBetaThreadsRunIncompleteDetailsReasonEnum[keyof typeof OpenaiTypesBetaThreadsRunIncompleteDetailsReasonEnum];


/**
 * Check if a given object implements the OpenaiTypesBetaThreadsRunIncompleteDetails interface.
 */
export function instanceOfOpenaiTypesBetaThreadsRunIncompleteDetails(value: object): value is OpenaiTypesBetaThreadsRunIncompleteDetails {
    return true;
}

export function OpenaiTypesBetaThreadsRunIncompleteDetailsFromJSON(json: any): OpenaiTypesBetaThreadsRunIncompleteDetails {
    return OpenaiTypesBetaThreadsRunIncompleteDetailsFromJSONTyped(json, false);
}

export function OpenaiTypesBetaThreadsRunIncompleteDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenaiTypesBetaThreadsRunIncompleteDetails {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function OpenaiTypesBetaThreadsRunIncompleteDetailsToJSON(json: any): OpenaiTypesBetaThreadsRunIncompleteDetails {
    return OpenaiTypesBetaThreadsRunIncompleteDetailsToJSONTyped(json, false);
}

export function OpenaiTypesBetaThreadsRunIncompleteDetailsToJSONTyped(value?: OpenaiTypesBetaThreadsRunIncompleteDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'reason': value['reason'],
    };
}

