/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OpenaiTypesBetaThreadsMessageIncompleteDetails
 */
export interface OpenaiTypesBetaThreadsMessageIncompleteDetails {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof OpenaiTypesBetaThreadsMessageIncompleteDetails
     */
    reason: OpenaiTypesBetaThreadsMessageIncompleteDetailsReasonEnum;
}


/**
 * @export
 */
export const OpenaiTypesBetaThreadsMessageIncompleteDetailsReasonEnum = {
    ContentFilter: 'content_filter',
    MaxTokens: 'max_tokens',
    RunCancelled: 'run_cancelled',
    RunExpired: 'run_expired',
    RunFailed: 'run_failed'
} as const;
export type OpenaiTypesBetaThreadsMessageIncompleteDetailsReasonEnum = typeof OpenaiTypesBetaThreadsMessageIncompleteDetailsReasonEnum[keyof typeof OpenaiTypesBetaThreadsMessageIncompleteDetailsReasonEnum];


/**
 * Check if a given object implements the OpenaiTypesBetaThreadsMessageIncompleteDetails interface.
 */
export function instanceOfOpenaiTypesBetaThreadsMessageIncompleteDetails(value: object): value is OpenaiTypesBetaThreadsMessageIncompleteDetails {
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function OpenaiTypesBetaThreadsMessageIncompleteDetailsFromJSON(json: any): OpenaiTypesBetaThreadsMessageIncompleteDetails {
    return OpenaiTypesBetaThreadsMessageIncompleteDetailsFromJSONTyped(json, false);
}

export function OpenaiTypesBetaThreadsMessageIncompleteDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenaiTypesBetaThreadsMessageIncompleteDetails {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'reason': json['reason'],
    };
}

export function OpenaiTypesBetaThreadsMessageIncompleteDetailsToJSON(json: any): OpenaiTypesBetaThreadsMessageIncompleteDetails {
    return OpenaiTypesBetaThreadsMessageIncompleteDetailsToJSONTyped(json, false);
}

export function OpenaiTypesBetaThreadsMessageIncompleteDetailsToJSONTyped(value?: OpenaiTypesBetaThreadsMessageIncompleteDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'reason': value['reason'],
    };
}

