/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OpenaiTypesSharedParamsResponseFormatJsonSchemaJSONSchema
 */
export interface OpenaiTypesSharedParamsResponseFormatJsonSchemaJSONSchema {
    /**
     * 
     * @type {string}
     * @memberof OpenaiTypesSharedParamsResponseFormatJsonSchemaJSONSchema
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof OpenaiTypesSharedParamsResponseFormatJsonSchemaJSONSchema
     */
    description?: string;
    /**
     * 
     * @type {object}
     * @memberof OpenaiTypesSharedParamsResponseFormatJsonSchemaJSONSchema
     */
    schema?: object;
    /**
     * 
     * @type {boolean}
     * @memberof OpenaiTypesSharedParamsResponseFormatJsonSchemaJSONSchema
     */
    strict?: boolean | null;
}

/**
 * Check if a given object implements the OpenaiTypesSharedParamsResponseFormatJsonSchemaJSONSchema interface.
 */
export function instanceOfOpenaiTypesSharedParamsResponseFormatJsonSchemaJSONSchema(value: object): value is OpenaiTypesSharedParamsResponseFormatJsonSchemaJSONSchema {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function OpenaiTypesSharedParamsResponseFormatJsonSchemaJSONSchemaFromJSON(json: any): OpenaiTypesSharedParamsResponseFormatJsonSchemaJSONSchema {
    return OpenaiTypesSharedParamsResponseFormatJsonSchemaJSONSchemaFromJSONTyped(json, false);
}

export function OpenaiTypesSharedParamsResponseFormatJsonSchemaJSONSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenaiTypesSharedParamsResponseFormatJsonSchemaJSONSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'schema': json['schema'] == null ? undefined : json['schema'],
        'strict': json['strict'] == null ? undefined : json['strict'],
    };
}

export function OpenaiTypesSharedParamsResponseFormatJsonSchemaJSONSchemaToJSON(json: any): OpenaiTypesSharedParamsResponseFormatJsonSchemaJSONSchema {
    return OpenaiTypesSharedParamsResponseFormatJsonSchemaJSONSchemaToJSONTyped(json, false);
}

export function OpenaiTypesSharedParamsResponseFormatJsonSchemaJSONSchemaToJSONTyped(value?: OpenaiTypesSharedParamsResponseFormatJsonSchemaJSONSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'schema': value['schema'],
        'strict': value['strict'],
    };
}

