/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request model for querying a vector store.
 * @export
 * @interface QueryVectorStoreRequest
 */
export interface QueryVectorStoreRequest {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof QueryVectorStoreRequest
     */
    query: string;
    /**
     * 
     * @type {boolean}
     * @memberof QueryVectorStoreRequest
     */
    fullFiles?: boolean;
}

/**
 * Check if a given object implements the QueryVectorStoreRequest interface.
 */
export function instanceOfQueryVectorStoreRequest(value: object): value is QueryVectorStoreRequest {
    if (!('query' in value) || value['query'] === undefined) return false;
    return true;
}

export function QueryVectorStoreRequestFromJSON(json: any): QueryVectorStoreRequest {
    return QueryVectorStoreRequestFromJSONTyped(json, false);
}

export function QueryVectorStoreRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryVectorStoreRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'query': json['query'],
        'fullFiles': json['full_files'] == null ? undefined : json['full_files'],
    };
}

export function QueryVectorStoreRequestToJSON(json: any): QueryVectorStoreRequest {
    return QueryVectorStoreRequestToJSONTyped(json, false);
}

export function QueryVectorStoreRequestToJSONTyped(value?: QueryVectorStoreRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'query': value['query'],
        'full_files': value['fullFiles'],
    };
}

