/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RefusalContentBlock
 */
export interface RefusalContentBlock {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof RefusalContentBlock
     */
    refusal: string;
    /**
     * 
     * @type {string}
     * @memberof RefusalContentBlock
     */
    type: RefusalContentBlockTypeEnum;
}


/**
 * @export
 */
export const RefusalContentBlockTypeEnum = {
    Refusal: 'refusal'
} as const;
export type RefusalContentBlockTypeEnum = typeof RefusalContentBlockTypeEnum[keyof typeof RefusalContentBlockTypeEnum];


/**
 * Check if a given object implements the RefusalContentBlock interface.
 */
export function instanceOfRefusalContentBlock(value: object): value is RefusalContentBlock {
    if (!('refusal' in value) || value['refusal'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function RefusalContentBlockFromJSON(json: any): RefusalContentBlock {
    return RefusalContentBlockFromJSONTyped(json, false);
}

export function RefusalContentBlockFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefusalContentBlock {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'refusal': json['refusal'],
        'type': json['type'],
    };
}

export function RefusalContentBlockToJSON(json: any): RefusalContentBlock {
    return RefusalContentBlockToJSONTyped(json, false);
}

export function RefusalContentBlockToJSONTyped(value?: RefusalContentBlock | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'refusal': value['refusal'],
        'type': value['type'],
    };
}

