/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Entry stored in the registry.
 * @export
 * @interface RegistryEntry
 */
export interface RegistryEntry {
    /**
     * 
     * @type {number}
     * @memberof RegistryEntry
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof RegistryEntry
     */
    namespace: string;
    /**
     * 
     * @type {string}
     * @memberof RegistryEntry
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof RegistryEntry
     */
    version: string;
    /**
     * 
     * @type {Date}
     * @memberof RegistryEntry
     */
    time?: Date;
    /**
     * 
     * @type {string}
     * @memberof RegistryEntry
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof RegistryEntry
     */
    category?: string;
    /**
     * 
     * @type {object}
     * @memberof RegistryEntry
     */
    details?: object;
    /**
     * 
     * @type {boolean}
     * @memberof RegistryEntry
     */
    showEntry?: boolean;
}

/**
 * Check if a given object implements the RegistryEntry interface.
 */
export function instanceOfRegistryEntry(value: object): value is RegistryEntry {
    if (!('namespace' in value) || value['namespace'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function RegistryEntryFromJSON(json: any): RegistryEntry {
    return RegistryEntryFromJSONTyped(json, false);
}

export function RegistryEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegistryEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'namespace': json['namespace'],
        'name': json['name'],
        'version': json['version'],
        'time': json['time'] == null ? undefined : (new Date(json['time'])),
        'description': json['description'] == null ? undefined : json['description'],
        'category': json['category'] == null ? undefined : json['category'],
        'details': json['details'] == null ? undefined : json['details'],
        'showEntry': json['show_entry'] == null ? undefined : json['show_entry'],
    };
}

export function RegistryEntryToJSON(json: any): RegistryEntry {
    return RegistryEntryToJSONTyped(json, false);
}

export function RegistryEntryToJSONTyped(value?: RegistryEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'namespace': value['namespace'],
        'name': value['name'],
        'version': value['version'],
        'time': value['time'] == null ? undefined : ((value['time']).toISOString()),
        'description': value['description'],
        'category': value['category'],
        'details': value['details'],
        'show_entry': value['showEntry'],
    };
}

