/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RequiredActionSubmitToolOutputs } from './RequiredActionSubmitToolOutputs';
import {
    RequiredActionSubmitToolOutputsFromJSON,
    RequiredActionSubmitToolOutputsFromJSONTyped,
    RequiredActionSubmitToolOutputsToJSON,
    RequiredActionSubmitToolOutputsToJSONTyped,
} from './RequiredActionSubmitToolOutputs';

/**
 * 
 * @export
 * @interface RequiredAction
 */
export interface RequiredAction {
    [key: string]: any | any;
    /**
     * 
     * @type {RequiredActionSubmitToolOutputs}
     * @memberof RequiredAction
     */
    submitToolOutputs: RequiredActionSubmitToolOutputs;
    /**
     * 
     * @type {string}
     * @memberof RequiredAction
     */
    type: RequiredActionTypeEnum;
}


/**
 * @export
 */
export const RequiredActionTypeEnum = {
    SubmitToolOutputs: 'submit_tool_outputs'
} as const;
export type RequiredActionTypeEnum = typeof RequiredActionTypeEnum[keyof typeof RequiredActionTypeEnum];


/**
 * Check if a given object implements the RequiredAction interface.
 */
export function instanceOfRequiredAction(value: object): value is RequiredAction {
    if (!('submitToolOutputs' in value) || value['submitToolOutputs'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function RequiredActionFromJSON(json: any): RequiredAction {
    return RequiredActionFromJSONTyped(json, false);
}

export function RequiredActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequiredAction {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'submitToolOutputs': RequiredActionSubmitToolOutputsFromJSON(json['submit_tool_outputs']),
        'type': json['type'],
    };
}

export function RequiredActionToJSON(json: any): RequiredAction {
    return RequiredActionToJSONTyped(json, false);
}

export function RequiredActionToJSONTyped(value?: RequiredAction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'submit_tool_outputs': RequiredActionSubmitToolOutputsToJSON(value['submitToolOutputs']),
        'type': value['type'],
    };
}

