/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RequiredActionFunctionToolCall } from './RequiredActionFunctionToolCall';
import {
    RequiredActionFunctionToolCallFromJSON,
    RequiredActionFunctionToolCallFromJSONTyped,
    RequiredActionFunctionToolCallToJSON,
    RequiredActionFunctionToolCallToJSONTyped,
} from './RequiredActionFunctionToolCall';

/**
 * 
 * @export
 * @interface RequiredActionSubmitToolOutputs
 */
export interface RequiredActionSubmitToolOutputs {
    [key: string]: any | any;
    /**
     * 
     * @type {Array<RequiredActionFunctionToolCall>}
     * @memberof RequiredActionSubmitToolOutputs
     */
    toolCalls: Array<RequiredActionFunctionToolCall>;
}

/**
 * Check if a given object implements the RequiredActionSubmitToolOutputs interface.
 */
export function instanceOfRequiredActionSubmitToolOutputs(value: object): value is RequiredActionSubmitToolOutputs {
    if (!('toolCalls' in value) || value['toolCalls'] === undefined) return false;
    return true;
}

export function RequiredActionSubmitToolOutputsFromJSON(json: any): RequiredActionSubmitToolOutputs {
    return RequiredActionSubmitToolOutputsFromJSONTyped(json, false);
}

export function RequiredActionSubmitToolOutputsFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequiredActionSubmitToolOutputs {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'toolCalls': ((json['tool_calls'] as Array<any>).map(RequiredActionFunctionToolCallFromJSON)),
    };
}

export function RequiredActionSubmitToolOutputsToJSON(json: any): RequiredActionSubmitToolOutputs {
    return RequiredActionSubmitToolOutputsToJSONTyped(json, false);
}

export function RequiredActionSubmitToolOutputsToJSONTyped(value?: RequiredActionSubmitToolOutputs | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'tool_calls': ((value['toolCalls'] as Array<any>).map(RequiredActionFunctionToolCallToJSON)),
    };
}

