/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Function } from './Function';
import {
    FunctionFromJSON,
    FunctionFromJSONTyped,
    FunctionToJSON,
    FunctionToJSONTyped,
} from './Function';

/**
 * 
 * @export
 * @interface RequiredActionFunctionToolCall
 */
export interface RequiredActionFunctionToolCall {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof RequiredActionFunctionToolCall
     */
    id: string;
    /**
     * 
     * @type {Function}
     * @memberof RequiredActionFunctionToolCall
     */
    _function: Function;
    /**
     * 
     * @type {string}
     * @memberof RequiredActionFunctionToolCall
     */
    type: RequiredActionFunctionToolCallTypeEnum;
}


/**
 * @export
 */
export const RequiredActionFunctionToolCallTypeEnum = {
    Function: 'function'
} as const;
export type RequiredActionFunctionToolCallTypeEnum = typeof RequiredActionFunctionToolCallTypeEnum[keyof typeof RequiredActionFunctionToolCallTypeEnum];


/**
 * Check if a given object implements the RequiredActionFunctionToolCall interface.
 */
export function instanceOfRequiredActionFunctionToolCall(value: object): value is RequiredActionFunctionToolCall {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('_function' in value) || value['_function'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function RequiredActionFunctionToolCallFromJSON(json: any): RequiredActionFunctionToolCall {
    return RequiredActionFunctionToolCallFromJSONTyped(json, false);
}

export function RequiredActionFunctionToolCallFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequiredActionFunctionToolCall {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'],
        '_function': FunctionFromJSON(json['function']),
        'type': json['type'],
    };
}

export function RequiredActionFunctionToolCallToJSON(json: any): RequiredActionFunctionToolCall {
    return RequiredActionFunctionToolCallToJSONTyped(json, false);
}

export function RequiredActionFunctionToolCallToJSONTyped(value?: RequiredActionFunctionToolCall | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'id': value['id'],
        'function': FunctionToJSON(value['_function']),
        'type': value['type'],
    };
}

