/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OpenaiTypesSharedParamsResponseFormatJsonSchemaJSONSchema } from './OpenaiTypesSharedParamsResponseFormatJsonSchemaJSONSchema';
import {
    OpenaiTypesSharedParamsResponseFormatJsonSchemaJSONSchemaFromJSON,
    OpenaiTypesSharedParamsResponseFormatJsonSchemaJSONSchemaFromJSONTyped,
    OpenaiTypesSharedParamsResponseFormatJsonSchemaJSONSchemaToJSON,
    OpenaiTypesSharedParamsResponseFormatJsonSchemaJSONSchemaToJSONTyped,
} from './OpenaiTypesSharedParamsResponseFormatJsonSchemaJSONSchema';
import type { OpenaiTypesSharedParamsResponseFormatJsonSchemaResponseFormatJSONSchema } from './OpenaiTypesSharedParamsResponseFormatJsonSchemaResponseFormatJSONSchema';
import {
    OpenaiTypesSharedParamsResponseFormatJsonSchemaResponseFormatJSONSchemaFromJSON,
    OpenaiTypesSharedParamsResponseFormatJsonSchemaResponseFormatJSONSchemaFromJSONTyped,
    OpenaiTypesSharedParamsResponseFormatJsonSchemaResponseFormatJSONSchemaToJSON,
    OpenaiTypesSharedParamsResponseFormatJsonSchemaResponseFormatJSONSchemaToJSONTyped,
} from './OpenaiTypesSharedParamsResponseFormatJsonSchemaResponseFormatJSONSchema';
import type { OpenaiTypesSharedParamsResponseFormatJsonObjectResponseFormatJSONObject } from './OpenaiTypesSharedParamsResponseFormatJsonObjectResponseFormatJSONObject';
import {
    OpenaiTypesSharedParamsResponseFormatJsonObjectResponseFormatJSONObjectFromJSON,
    OpenaiTypesSharedParamsResponseFormatJsonObjectResponseFormatJSONObjectFromJSONTyped,
    OpenaiTypesSharedParamsResponseFormatJsonObjectResponseFormatJSONObjectToJSON,
    OpenaiTypesSharedParamsResponseFormatJsonObjectResponseFormatJSONObjectToJSONTyped,
} from './OpenaiTypesSharedParamsResponseFormatJsonObjectResponseFormatJSONObject';
import type { OpenaiTypesSharedParamsResponseFormatTextResponseFormatText } from './OpenaiTypesSharedParamsResponseFormatTextResponseFormatText';
import {
    OpenaiTypesSharedParamsResponseFormatTextResponseFormatTextFromJSON,
    OpenaiTypesSharedParamsResponseFormatTextResponseFormatTextFromJSONTyped,
    OpenaiTypesSharedParamsResponseFormatTextResponseFormatTextToJSON,
    OpenaiTypesSharedParamsResponseFormatTextResponseFormatTextToJSONTyped,
} from './OpenaiTypesSharedParamsResponseFormatTextResponseFormatText';

/**
 * Specifies the format that the model must output.
 * @export
 * @interface ResponseFormat2
 */
export interface ResponseFormat2 {
    /**
     * 
     * @type {string}
     * @memberof ResponseFormat2
     */
    type: ResponseFormat2TypeEnum;
    /**
     * 
     * @type {OpenaiTypesSharedParamsResponseFormatJsonSchemaJSONSchema}
     * @memberof ResponseFormat2
     */
    jsonSchema: OpenaiTypesSharedParamsResponseFormatJsonSchemaJSONSchema;
}


/**
 * @export
 */
export const ResponseFormat2TypeEnum = {
    Text: 'text',
    JsonObject: 'json_object',
    JsonSchema: 'json_schema'
} as const;
export type ResponseFormat2TypeEnum = typeof ResponseFormat2TypeEnum[keyof typeof ResponseFormat2TypeEnum];


/**
 * Check if a given object implements the ResponseFormat2 interface.
 */
export function instanceOfResponseFormat2(value: object): value is ResponseFormat2 {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('jsonSchema' in value) || value['jsonSchema'] === undefined) return false;
    return true;
}

export function ResponseFormat2FromJSON(json: any): ResponseFormat2 {
    return ResponseFormat2FromJSONTyped(json, false);
}

export function ResponseFormat2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseFormat2 {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'jsonSchema': OpenaiTypesSharedParamsResponseFormatJsonSchemaJSONSchemaFromJSON(json['json_schema']),
    };
}

export function ResponseFormat2ToJSON(json: any): ResponseFormat2 {
    return ResponseFormat2ToJSONTyped(json, false);
}

export function ResponseFormat2ToJSONTyped(value?: ResponseFormat2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'json_schema': OpenaiTypesSharedParamsResponseFormatJsonSchemaJSONSchemaToJSON(value['jsonSchema']),
    };
}

