/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JSONSchemaOutput } from './JSONSchemaOutput';
import {
    JSONSchemaOutputFromJSON,
    JSONSchemaOutputFromJSONTyped,
    JSONSchemaOutputToJSON,
    JSONSchemaOutputToJSONTyped,
} from './JSONSchemaOutput';

/**
 * 
 * @export
 * @interface ResponseFormatJSONSchemaOutput
 */
export interface ResponseFormatJSONSchemaOutput {
    [key: string]: any | any;
    /**
     * 
     * @type {JSONSchemaOutput}
     * @memberof ResponseFormatJSONSchemaOutput
     */
    jsonSchema: JSONSchemaOutput;
    /**
     * 
     * @type {string}
     * @memberof ResponseFormatJSONSchemaOutput
     */
    type: ResponseFormatJSONSchemaOutputTypeEnum;
}


/**
 * @export
 */
export const ResponseFormatJSONSchemaOutputTypeEnum = {
    JsonSchema: 'json_schema'
} as const;
export type ResponseFormatJSONSchemaOutputTypeEnum = typeof ResponseFormatJSONSchemaOutputTypeEnum[keyof typeof ResponseFormatJSONSchemaOutputTypeEnum];


/**
 * Check if a given object implements the ResponseFormatJSONSchemaOutput interface.
 */
export function instanceOfResponseFormatJSONSchemaOutput(value: object): value is ResponseFormatJSONSchemaOutput {
    if (!('jsonSchema' in value) || value['jsonSchema'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ResponseFormatJSONSchemaOutputFromJSON(json: any): ResponseFormatJSONSchemaOutput {
    return ResponseFormatJSONSchemaOutputFromJSONTyped(json, false);
}

export function ResponseFormatJSONSchemaOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseFormatJSONSchemaOutput {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'jsonSchema': JSONSchemaOutputFromJSON(json['json_schema']),
        'type': json['type'],
    };
}

export function ResponseFormatJSONSchemaOutputToJSON(json: any): ResponseFormatJSONSchemaOutput {
    return ResponseFormatJSONSchemaOutputToJSONTyped(json, false);
}

export function ResponseFormatJSONSchemaOutputToJSONTyped(value?: ResponseFormatJSONSchemaOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'json_schema': JSONSchemaOutputToJSON(value['jsonSchema']),
        'type': value['type'],
    };
}

