/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseFormatJSONObjectOutput
 */
export interface ResponseFormatJSONObjectOutput {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof ResponseFormatJSONObjectOutput
     */
    type: ResponseFormatJSONObjectOutputTypeEnum;
}


/**
 * @export
 */
export const ResponseFormatJSONObjectOutputTypeEnum = {
    JsonObject: 'json_object'
} as const;
export type ResponseFormatJSONObjectOutputTypeEnum = typeof ResponseFormatJSONObjectOutputTypeEnum[keyof typeof ResponseFormatJSONObjectOutputTypeEnum];


/**
 * Check if a given object implements the ResponseFormatJSONObjectOutput interface.
 */
export function instanceOfResponseFormatJSONObjectOutput(value: object): value is ResponseFormatJSONObjectOutput {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ResponseFormatJSONObjectOutputFromJSON(json: any): ResponseFormatJSONObjectOutput {
    return ResponseFormatJSONObjectOutputFromJSONTyped(json, false);
}

export function ResponseFormatJSONObjectOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseFormatJSONObjectOutput {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'type': json['type'],
    };
}

export function ResponseFormatJSONObjectOutputToJSON(json: any): ResponseFormatJSONObjectOutput {
    return ResponseFormatJSONObjectOutputToJSONTyped(json, false);
}

export function ResponseFormatJSONObjectOutputToJSONTyped(value?: ResponseFormatJSONObjectOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'type': value['type'],
    };
}

