/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OpenaiTypesSharedResponseFormatTextResponseFormatText } from './OpenaiTypesSharedResponseFormatTextResponseFormatText';
import {
    OpenaiTypesSharedResponseFormatTextResponseFormatTextFromJSON,
    OpenaiTypesSharedResponseFormatTextResponseFormatTextFromJSONTyped,
    OpenaiTypesSharedResponseFormatTextResponseFormatTextToJSON,
    OpenaiTypesSharedResponseFormatTextResponseFormatTextToJSONTyped,
} from './OpenaiTypesSharedResponseFormatTextResponseFormatText';
import type { OpenaiTypesSharedResponseFormatJsonObjectResponseFormatJSONObject } from './OpenaiTypesSharedResponseFormatJsonObjectResponseFormatJSONObject';
import {
    OpenaiTypesSharedResponseFormatJsonObjectResponseFormatJSONObjectFromJSON,
    OpenaiTypesSharedResponseFormatJsonObjectResponseFormatJSONObjectFromJSONTyped,
    OpenaiTypesSharedResponseFormatJsonObjectResponseFormatJSONObjectToJSON,
    OpenaiTypesSharedResponseFormatJsonObjectResponseFormatJSONObjectToJSONTyped,
} from './OpenaiTypesSharedResponseFormatJsonObjectResponseFormatJSONObject';
import type { OpenaiTypesSharedResponseFormatJsonSchemaJSONSchema } from './OpenaiTypesSharedResponseFormatJsonSchemaJSONSchema';
import {
    OpenaiTypesSharedResponseFormatJsonSchemaJSONSchemaFromJSON,
    OpenaiTypesSharedResponseFormatJsonSchemaJSONSchemaFromJSONTyped,
    OpenaiTypesSharedResponseFormatJsonSchemaJSONSchemaToJSON,
    OpenaiTypesSharedResponseFormatJsonSchemaJSONSchemaToJSONTyped,
} from './OpenaiTypesSharedResponseFormatJsonSchemaJSONSchema';
import type { OpenaiTypesSharedResponseFormatJsonSchemaResponseFormatJSONSchemaInput } from './OpenaiTypesSharedResponseFormatJsonSchemaResponseFormatJSONSchemaInput';
import {
    OpenaiTypesSharedResponseFormatJsonSchemaResponseFormatJSONSchemaInputFromJSON,
    OpenaiTypesSharedResponseFormatJsonSchemaResponseFormatJSONSchemaInputFromJSONTyped,
    OpenaiTypesSharedResponseFormatJsonSchemaResponseFormatJSONSchemaInputToJSON,
    OpenaiTypesSharedResponseFormatJsonSchemaResponseFormatJSONSchemaInputToJSONTyped,
} from './OpenaiTypesSharedResponseFormatJsonSchemaResponseFormatJSONSchemaInput';

/**
 * 
 * @export
 * @interface ResponseFormat
 */
export interface ResponseFormat {
    /**
     * 
     * @type {string}
     * @memberof ResponseFormat
     */
    type: ResponseFormatTypeEnum;
    /**
     * 
     * @type {OpenaiTypesSharedResponseFormatJsonSchemaJSONSchema}
     * @memberof ResponseFormat
     */
    jsonSchema: OpenaiTypesSharedResponseFormatJsonSchemaJSONSchema;
}


/**
 * @export
 */
export const ResponseFormatTypeEnum = {
    Text: 'text',
    JsonObject: 'json_object',
    JsonSchema: 'json_schema'
} as const;
export type ResponseFormatTypeEnum = typeof ResponseFormatTypeEnum[keyof typeof ResponseFormatTypeEnum];


/**
 * Check if a given object implements the ResponseFormat interface.
 */
export function instanceOfResponseFormat(value: object): value is ResponseFormat {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('jsonSchema' in value) || value['jsonSchema'] === undefined) return false;
    return true;
}

export function ResponseFormatFromJSON(json: any): ResponseFormat {
    return ResponseFormatFromJSONTyped(json, false);
}

export function ResponseFormatFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseFormat {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'jsonSchema': OpenaiTypesSharedResponseFormatJsonSchemaJSONSchemaFromJSON(json['json_schema']),
    };
}

export function ResponseFormatToJSON(json: any): ResponseFormat {
    return ResponseFormatToJSONTyped(json, false);
}

export function ResponseFormatToJSONTyped(value?: ResponseFormat | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'json_schema': OpenaiTypesSharedResponseFormatJsonSchemaJSONSchemaToJSON(value['jsonSchema']),
    };
}

