/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RevokeNonce
 */
export interface RevokeNonce {
    /**
     * 
     * @type {Blob}
     * @memberof RevokeNonce
     */
    nonce: Blob;
}

/**
 * Check if a given object implements the RevokeNonce interface.
 */
export function instanceOfRevokeNonce(value: object): value is RevokeNonce {
    if (!('nonce' in value) || value['nonce'] === undefined) return false;
    return true;
}

export function RevokeNonceFromJSON(json: any): RevokeNonce {
    return RevokeNonceFromJSONTyped(json, false);
}

export function RevokeNonceFromJSONTyped(json: any, ignoreDiscriminator: boolean): RevokeNonce {
    if (json == null) {
        return json;
    }
    return {
        
        'nonce': json['nonce'],
    };
}

export function RevokeNonceToJSON(json: any): RevokeNonce {
    return RevokeNonceToJSONTyped(json, false);
}

export function RevokeNonceToJSONTyped(value?: RevokeNonce | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nonce': value['nonce'],
    };
}

