/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LastError } from './LastError';
import {
    LastErrorFromJSON,
    LastErrorFromJSONTyped,
    LastErrorToJSON,
    LastErrorToJSONTyped,
} from './LastError';
import type { Usage } from './Usage';
import {
    UsageFromJSON,
    UsageFromJSONTyped,
    UsageToJSON,
    UsageToJSONTyped,
} from './Usage';
import type { ToolChoice } from './ToolChoice';
import {
    ToolChoiceFromJSON,
    ToolChoiceFromJSONTyped,
    ToolChoiceToJSON,
    ToolChoiceToJSONTyped,
} from './ToolChoice';
import type { ResponseFormat1 } from './ResponseFormat1';
import {
    ResponseFormat1FromJSON,
    ResponseFormat1FromJSONTyped,
    ResponseFormat1ToJSON,
    ResponseFormat1ToJSONTyped,
} from './ResponseFormat1';
import type { OpenaiTypesBetaThreadsRunIncompleteDetails } from './OpenaiTypesBetaThreadsRunIncompleteDetails';
import {
    OpenaiTypesBetaThreadsRunIncompleteDetailsFromJSON,
    OpenaiTypesBetaThreadsRunIncompleteDetailsFromJSONTyped,
    OpenaiTypesBetaThreadsRunIncompleteDetailsToJSON,
    OpenaiTypesBetaThreadsRunIncompleteDetailsToJSONTyped,
} from './OpenaiTypesBetaThreadsRunIncompleteDetails';
import type { RequiredAction } from './RequiredAction';
import {
    RequiredActionFromJSON,
    RequiredActionFromJSONTyped,
    RequiredActionToJSON,
    RequiredActionToJSONTyped,
} from './RequiredAction';
import type { TruncationStrategyOutput } from './TruncationStrategyOutput';
import {
    TruncationStrategyOutputFromJSON,
    TruncationStrategyOutputFromJSONTyped,
    TruncationStrategyOutputToJSON,
    TruncationStrategyOutputToJSONTyped,
} from './TruncationStrategyOutput';
import type { RunToolsInner } from './RunToolsInner';
import {
    RunToolsInnerFromJSON,
    RunToolsInnerFromJSONTyped,
    RunToolsInnerToJSON,
    RunToolsInnerToJSONTyped,
} from './RunToolsInner';

/**
 * 
 * @export
 * @interface Run
 */
export interface Run {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof Run
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Run
     */
    assistantId: string;
    /**
     * 
     * @type {number}
     * @memberof Run
     */
    cancelledAt?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Run
     */
    completedAt?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Run
     */
    createdAt: number;
    /**
     * 
     * @type {number}
     * @memberof Run
     */
    expiresAt?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Run
     */
    failedAt?: number | null;
    /**
     * 
     * @type {OpenaiTypesBetaThreadsRunIncompleteDetails}
     * @memberof Run
     */
    incompleteDetails?: OpenaiTypesBetaThreadsRunIncompleteDetails | null;
    /**
     * 
     * @type {string}
     * @memberof Run
     */
    instructions: string;
    /**
     * 
     * @type {LastError}
     * @memberof Run
     */
    lastError?: LastError | null;
    /**
     * 
     * @type {number}
     * @memberof Run
     */
    maxCompletionTokens?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Run
     */
    maxPromptTokens?: number | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof Run
     */
    metadata?: { [key: string]: string; } | null;
    /**
     * 
     * @type {string}
     * @memberof Run
     */
    model: string;
    /**
     * 
     * @type {string}
     * @memberof Run
     */
    object: RunObjectEnum;
    /**
     * 
     * @type {boolean}
     * @memberof Run
     */
    parallelToolCalls: boolean;
    /**
     * 
     * @type {RequiredAction}
     * @memberof Run
     */
    requiredAction?: RequiredAction | null;
    /**
     * 
     * @type {ResponseFormat1}
     * @memberof Run
     */
    responseFormat?: ResponseFormat1 | null;
    /**
     * 
     * @type {number}
     * @memberof Run
     */
    startedAt?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Run
     */
    status: RunStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof Run
     */
    threadId: string;
    /**
     * 
     * @type {ToolChoice}
     * @memberof Run
     */
    toolChoice?: ToolChoice | null;
    /**
     * 
     * @type {Array<RunToolsInner>}
     * @memberof Run
     */
    tools: Array<RunToolsInner>;
    /**
     * 
     * @type {TruncationStrategyOutput}
     * @memberof Run
     */
    truncationStrategy?: TruncationStrategyOutput | null;
    /**
     * 
     * @type {Usage}
     * @memberof Run
     */
    usage?: Usage | null;
    /**
     * 
     * @type {number}
     * @memberof Run
     */
    temperature?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Run
     */
    topP?: number | null;
}


/**
 * @export
 */
export const RunObjectEnum = {
    ThreadRun: 'thread.run'
} as const;
export type RunObjectEnum = typeof RunObjectEnum[keyof typeof RunObjectEnum];

/**
 * @export
 */
export const RunStatusEnum = {
    Queued: 'queued',
    InProgress: 'in_progress',
    RequiresAction: 'requires_action',
    Cancelling: 'cancelling',
    Cancelled: 'cancelled',
    Failed: 'failed',
    Completed: 'completed',
    Incomplete: 'incomplete',
    Expired: 'expired'
} as const;
export type RunStatusEnum = typeof RunStatusEnum[keyof typeof RunStatusEnum];


/**
 * Check if a given object implements the Run interface.
 */
export function instanceOfRun(value: object): value is Run {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('assistantId' in value) || value['assistantId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('instructions' in value) || value['instructions'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('parallelToolCalls' in value) || value['parallelToolCalls'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('threadId' in value) || value['threadId'] === undefined) return false;
    if (!('tools' in value) || value['tools'] === undefined) return false;
    return true;
}

export function RunFromJSON(json: any): Run {
    return RunFromJSONTyped(json, false);
}

export function RunFromJSONTyped(json: any, ignoreDiscriminator: boolean): Run {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'],
        'assistantId': json['assistant_id'],
        'cancelledAt': json['cancelled_at'] == null ? undefined : json['cancelled_at'],
        'completedAt': json['completed_at'] == null ? undefined : json['completed_at'],
        'createdAt': json['created_at'],
        'expiresAt': json['expires_at'] == null ? undefined : json['expires_at'],
        'failedAt': json['failed_at'] == null ? undefined : json['failed_at'],
        'incompleteDetails': json['incomplete_details'] == null ? undefined : OpenaiTypesBetaThreadsRunIncompleteDetailsFromJSON(json['incomplete_details']),
        'instructions': json['instructions'],
        'lastError': json['last_error'] == null ? undefined : LastErrorFromJSON(json['last_error']),
        'maxCompletionTokens': json['max_completion_tokens'] == null ? undefined : json['max_completion_tokens'],
        'maxPromptTokens': json['max_prompt_tokens'] == null ? undefined : json['max_prompt_tokens'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'model': json['model'],
        'object': json['object'],
        'parallelToolCalls': json['parallel_tool_calls'],
        'requiredAction': json['required_action'] == null ? undefined : RequiredActionFromJSON(json['required_action']),
        'responseFormat': json['response_format'] == null ? undefined : ResponseFormat1FromJSON(json['response_format']),
        'startedAt': json['started_at'] == null ? undefined : json['started_at'],
        'status': json['status'],
        'threadId': json['thread_id'],
        'toolChoice': json['tool_choice'] == null ? undefined : ToolChoiceFromJSON(json['tool_choice']),
        'tools': ((json['tools'] as Array<any>).map(RunToolsInnerFromJSON)),
        'truncationStrategy': json['truncation_strategy'] == null ? undefined : TruncationStrategyOutputFromJSON(json['truncation_strategy']),
        'usage': json['usage'] == null ? undefined : UsageFromJSON(json['usage']),
        'temperature': json['temperature'] == null ? undefined : json['temperature'],
        'topP': json['top_p'] == null ? undefined : json['top_p'],
    };
}

export function RunToJSON(json: any): Run {
    return RunToJSONTyped(json, false);
}

export function RunToJSONTyped(value?: Run | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'id': value['id'],
        'assistant_id': value['assistantId'],
        'cancelled_at': value['cancelledAt'],
        'completed_at': value['completedAt'],
        'created_at': value['createdAt'],
        'expires_at': value['expiresAt'],
        'failed_at': value['failedAt'],
        'incomplete_details': OpenaiTypesBetaThreadsRunIncompleteDetailsToJSON(value['incompleteDetails']),
        'instructions': value['instructions'],
        'last_error': LastErrorToJSON(value['lastError']),
        'max_completion_tokens': value['maxCompletionTokens'],
        'max_prompt_tokens': value['maxPromptTokens'],
        'metadata': value['metadata'],
        'model': value['model'],
        'object': value['object'],
        'parallel_tool_calls': value['parallelToolCalls'],
        'required_action': RequiredActionToJSON(value['requiredAction']),
        'response_format': ResponseFormat1ToJSON(value['responseFormat']),
        'started_at': value['startedAt'],
        'status': value['status'],
        'thread_id': value['threadId'],
        'tool_choice': ToolChoiceToJSON(value['toolChoice']),
        'tools': ((value['tools'] as Array<any>).map(RunToolsInnerToJSON)),
        'truncation_strategy': TruncationStrategyOutputToJSON(value['truncationStrategy']),
        'usage': UsageToJSON(value['usage']),
        'temperature': value['temperature'],
        'top_p': value['topP'],
    };
}

