/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CodeInterpreterTool } from './CodeInterpreterTool';
import {
    CodeInterpreterToolFromJSON,
    CodeInterpreterToolFromJSONTyped,
    CodeInterpreterToolToJSON,
    CodeInterpreterToolToJSONTyped,
} from './CodeInterpreterTool';
import type { FileSearchTool } from './FileSearchTool';
import {
    FileSearchToolFromJSON,
    FileSearchToolFromJSONTyped,
    FileSearchToolToJSON,
    FileSearchToolToJSONTyped,
} from './FileSearchTool';
import type { FunctionTool } from './FunctionTool';
import {
    FunctionToolFromJSON,
    FunctionToolFromJSONTyped,
    FunctionToolToJSON,
    FunctionToolToJSONTyped,
} from './FunctionTool';
import type { FunctionDefinition } from './FunctionDefinition';
import {
    FunctionDefinitionFromJSON,
    FunctionDefinitionFromJSONTyped,
    FunctionDefinitionToJSON,
    FunctionDefinitionToJSONTyped,
} from './FunctionDefinition';
import type { FileSearch } from './FileSearch';
import {
    FileSearchFromJSON,
    FileSearchFromJSONTyped,
    FileSearchToJSON,
    FileSearchToJSONTyped,
} from './FileSearch';

/**
 * 
 * @export
 * @interface RunToolsInner
 */
export interface RunToolsInner {
    /**
     * 
     * @type {string}
     * @memberof RunToolsInner
     */
    type: RunToolsInnerTypeEnum;
    /**
     * 
     * @type {FileSearch}
     * @memberof RunToolsInner
     */
    fileSearch?: FileSearch;
    /**
     * 
     * @type {FunctionDefinition}
     * @memberof RunToolsInner
     */
    _function: FunctionDefinition;
}


/**
 * @export
 */
export const RunToolsInnerTypeEnum = {
    CodeInterpreter: 'code_interpreter',
    FileSearch: 'file_search',
    Function: 'function'
} as const;
export type RunToolsInnerTypeEnum = typeof RunToolsInnerTypeEnum[keyof typeof RunToolsInnerTypeEnum];


/**
 * Check if a given object implements the RunToolsInner interface.
 */
export function instanceOfRunToolsInner(value: object): value is RunToolsInner {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('_function' in value) || value['_function'] === undefined) return false;
    return true;
}

export function RunToolsInnerFromJSON(json: any): RunToolsInner {
    return RunToolsInnerFromJSONTyped(json, false);
}

export function RunToolsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunToolsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'fileSearch': json['file_search'] == null ? undefined : FileSearchFromJSON(json['file_search']),
        '_function': FunctionDefinitionFromJSON(json['function']),
    };
}

export function RunToolsInnerToJSON(json: any): RunToolsInner {
    return RunToolsInnerToJSONTyped(json, false);
}

export function RunToolsInnerToJSONTyped(value?: RunToolsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'file_search': FileSearchToJSON(value['fileSearch']),
        'function': FunctionDefinitionToJSON(value['_function']),
    };
}

