/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RunUpdateParams
 */
export interface RunUpdateParams {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof RunUpdateParams
     */
    status?: RunUpdateParamsStatusEnum | null;
    /**
     * 
     * @type {Date}
     * @memberof RunUpdateParams
     */
    completedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof RunUpdateParams
     */
    failedAt?: Date | null;
    /**
     * 
     * @type {object}
     * @memberof RunUpdateParams
     */
    metadata?: object | null;
}


/**
 * @export
 */
export const RunUpdateParamsStatusEnum = {
    RequiresAction: 'requires_action',
    Failed: 'failed',
    Expired: 'expired',
    Completed: 'completed'
} as const;
export type RunUpdateParamsStatusEnum = typeof RunUpdateParamsStatusEnum[keyof typeof RunUpdateParamsStatusEnum];


/**
 * Check if a given object implements the RunUpdateParams interface.
 */
export function instanceOfRunUpdateParams(value: object): value is RunUpdateParams {
    return true;
}

export function RunUpdateParamsFromJSON(json: any): RunUpdateParams {
    return RunUpdateParamsFromJSONTyped(json, false);
}

export function RunUpdateParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunUpdateParams {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'status': json['status'] == null ? undefined : json['status'],
        'completedAt': json['completed_at'] == null ? undefined : (new Date(json['completed_at'])),
        'failedAt': json['failed_at'] == null ? undefined : (new Date(json['failed_at'])),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function RunUpdateParamsToJSON(json: any): RunUpdateParams {
    return RunUpdateParamsToJSONTyped(json, false);
}

export function RunUpdateParamsToJSONTyped(value?: RunUpdateParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'status': value['status'],
        'completed_at': value['completedAt'] == null ? undefined : ((value['completedAt'] as any).toISOString()),
        'failed_at': value['failedAt'] == null ? undefined : ((value['failedAt'] as any).toISOString()),
        'metadata': value['metadata'],
    };
}

