/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Job } from './Job';
import {
    JobFromJSON,
    JobFromJSONTyped,
    JobToJSON,
    JobToJSONTyped,
} from './Job';

/**
 * 
 * @export
 * @interface SelectedJob
 */
export interface SelectedJob {
    /**
     * 
     * @type {boolean}
     * @memberof SelectedJob
     */
    selected: boolean;
    /**
     * 
     * @type {Job}
     * @memberof SelectedJob
     */
    job: Job | null;
    /**
     * 
     * @type {string}
     * @memberof SelectedJob
     */
    registryPath: string | null;
    /**
     * 
     * @type {string}
     * @memberof SelectedJob
     */
    info: string;
}

/**
 * Check if a given object implements the SelectedJob interface.
 */
export function instanceOfSelectedJob(value: object): value is SelectedJob {
    if (!('selected' in value) || value['selected'] === undefined) return false;
    if (!('job' in value) || value['job'] === undefined) return false;
    if (!('registryPath' in value) || value['registryPath'] === undefined) return false;
    if (!('info' in value) || value['info'] === undefined) return false;
    return true;
}

export function SelectedJobFromJSON(json: any): SelectedJob {
    return SelectedJobFromJSONTyped(json, false);
}

export function SelectedJobFromJSONTyped(json: any, ignoreDiscriminator: boolean): SelectedJob {
    if (json == null) {
        return json;
    }
    return {
        
        'selected': json['selected'],
        'job': JobFromJSON(json['job']),
        'registryPath': json['registry_path'],
        'info': json['info'],
    };
}

export function SelectedJobToJSON(json: any): SelectedJob {
    return SelectedJobToJSONTyped(json, false);
}

export function SelectedJobToJSONTyped(value?: SelectedJob | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'selected': value['selected'],
        'job': JobToJSON(value['job']),
        'registry_path': value['registryPath'],
        'info': value['info'],
    };
}

