/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GitLabSource } from './GitLabSource';
import {
    GitLabSourceFromJSON,
    GitLabSourceFromJSONTyped,
    GitLabSourceToJSON,
    GitLabSourceToJSONTyped,
} from './GitLabSource';
import type { GitHubSource } from './GitHubSource';
import {
    GitHubSourceFromJSON,
    GitHubSourceFromJSONTyped,
    GitHubSourceToJSON,
    GitHubSourceToJSONTyped,
} from './GitHubSource';

/**
 * 
 * @export
 * @interface Source
 */
export interface Source {
    /**
     * 
     * @type {string}
     * @memberof Source
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof Source
     */
    owner: string;
    /**
     * 
     * @type {string}
     * @memberof Source
     */
    repo: string;
    /**
     * 
     * @type {string}
     * @memberof Source
     */
    branch?: string;
}

/**
 * Check if a given object implements the Source interface.
 */
export function instanceOfSource(value: object): value is Source {
    if (!('owner' in value) || value['owner'] === undefined) return false;
    if (!('repo' in value) || value['repo'] === undefined) return false;
    return true;
}

export function SourceFromJSON(json: any): Source {
    return SourceFromJSONTyped(json, false);
}

export function SourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Source {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'owner': json['owner'],
        'repo': json['repo'],
        'branch': json['branch'] == null ? undefined : json['branch'],
    };
}

export function SourceToJSON(json: any): Source {
    return SourceToJSONTyped(json, false);
}

export function SourceToJSONTyped(value?: Source | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'owner': value['owner'],
        'repo': value['repo'],
        'branch': value['branch'],
    };
}

