/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MessageCreateParams } from './MessageCreateParams';
import {
    MessageCreateParamsFromJSON,
    MessageCreateParamsFromJSONTyped,
    MessageCreateParamsToJSON,
    MessageCreateParamsToJSONTyped,
} from './MessageCreateParams';

/**
 * 
 * @export
 * @interface SubthreadCreateParams
 */
export interface SubthreadCreateParams {
    [key: string]: any | any;
    /**
     * 
     * @type {Array<number>}
     * @memberof SubthreadCreateParams
     */
    messagesToCopy?: Array<number> | null;
    /**
     * 
     * @type {Array<MessageCreateParams>}
     * @memberof SubthreadCreateParams
     */
    newMessages?: Array<MessageCreateParams> | null;
}

/**
 * Check if a given object implements the SubthreadCreateParams interface.
 */
export function instanceOfSubthreadCreateParams(value: object): value is SubthreadCreateParams {
    return true;
}

export function SubthreadCreateParamsFromJSON(json: any): SubthreadCreateParams {
    return SubthreadCreateParamsFromJSONTyped(json, false);
}

export function SubthreadCreateParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubthreadCreateParams {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'messagesToCopy': json['messages_to_copy'] == null ? undefined : json['messages_to_copy'],
        'newMessages': json['new_messages'] == null ? undefined : ((json['new_messages'] as Array<any>).map(MessageCreateParamsFromJSON)),
    };
}

export function SubthreadCreateParamsToJSON(json: any): SubthreadCreateParams {
    return SubthreadCreateParamsToJSONTyped(json, false);
}

export function SubthreadCreateParamsToJSONTyped(value?: SubthreadCreateParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'messages_to_copy': value['messagesToCopy'],
        'new_messages': value['newMessages'] == null ? undefined : ((value['newMessages'] as Array<any>).map(MessageCreateParamsToJSON)),
    };
}

