/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TextContentBlockParam
 */
export interface TextContentBlockParam {
    /**
     * 
     * @type {string}
     * @memberof TextContentBlockParam
     */
    text: string;
    /**
     * 
     * @type {string}
     * @memberof TextContentBlockParam
     */
    type: TextContentBlockParamTypeEnum;
}


/**
 * @export
 */
export const TextContentBlockParamTypeEnum = {
    Text: 'text'
} as const;
export type TextContentBlockParamTypeEnum = typeof TextContentBlockParamTypeEnum[keyof typeof TextContentBlockParamTypeEnum];


/**
 * Check if a given object implements the TextContentBlockParam interface.
 */
export function instanceOfTextContentBlockParam(value: object): value is TextContentBlockParam {
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function TextContentBlockParamFromJSON(json: any): TextContentBlockParam {
    return TextContentBlockParamFromJSONTyped(json, false);
}

export function TextContentBlockParamFromJSONTyped(json: any, ignoreDiscriminator: boolean): TextContentBlockParam {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
        'type': json['type'],
    };
}

export function TextContentBlockParamToJSON(json: any): TextContentBlockParam {
    return TextContentBlockParamToJSONTyped(json, false);
}

export function TextContentBlockParamToJSONTyped(value?: TextContentBlockParam | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'type': value['type'],
    };
}

