/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ThreadForkResponse
 */
export interface ThreadForkResponse {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof ThreadForkResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ThreadForkResponse
     */
    object?: string;
    /**
     * 
     * @type {number}
     * @memberof ThreadForkResponse
     */
    createdAt: number;
    /**
     * 
     * @type {object}
     * @memberof ThreadForkResponse
     */
    metadata?: object | null;
}

/**
 * Check if a given object implements the ThreadForkResponse interface.
 */
export function instanceOfThreadForkResponse(value: object): value is ThreadForkResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function ThreadForkResponseFromJSON(json: any): ThreadForkResponse {
    return ThreadForkResponseFromJSONTyped(json, false);
}

export function ThreadForkResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThreadForkResponse {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'],
        'object': json['object'] == null ? undefined : json['object'],
        'createdAt': json['created_at'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function ThreadForkResponseToJSON(json: any): ThreadForkResponse {
    return ThreadForkResponseToJSONTyped(json, false);
}

export function ThreadForkResponseToJSONTyped(value?: ThreadForkResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'id': value['id'],
        'object': value['object'],
        'created_at': value['createdAt'],
        'metadata': value['metadata'],
    };
}

