/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OpenaiTypesBetaThreadCreateParamsMessage } from './OpenaiTypesBetaThreadCreateParamsMessage';
import {
    OpenaiTypesBetaThreadCreateParamsMessageFromJSON,
    OpenaiTypesBetaThreadCreateParamsMessageFromJSONTyped,
    OpenaiTypesBetaThreadCreateParamsMessageToJSON,
    OpenaiTypesBetaThreadCreateParamsMessageToJSONTyped,
} from './OpenaiTypesBetaThreadCreateParamsMessage';
import type { ToolResourcesInput } from './ToolResourcesInput';
import {
    ToolResourcesInputFromJSON,
    ToolResourcesInputFromJSONTyped,
    ToolResourcesInputToJSON,
    ToolResourcesInputToJSONTyped,
} from './ToolResourcesInput';

/**
 * 
 * @export
 * @interface ThreadCreateParams
 */
export interface ThreadCreateParams {
    /**
     * 
     * @type {Array<OpenaiTypesBetaThreadCreateParamsMessage>}
     * @memberof ThreadCreateParams
     */
    messages?: Array<OpenaiTypesBetaThreadCreateParamsMessage>;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ThreadCreateParams
     */
    metadata?: { [key: string]: string; } | null;
    /**
     * 
     * @type {ToolResourcesInput}
     * @memberof ThreadCreateParams
     */
    toolResources?: ToolResourcesInput | null;
}

/**
 * Check if a given object implements the ThreadCreateParams interface.
 */
export function instanceOfThreadCreateParams(value: object): value is ThreadCreateParams {
    return true;
}

export function ThreadCreateParamsFromJSON(json: any): ThreadCreateParams {
    return ThreadCreateParamsFromJSONTyped(json, false);
}

export function ThreadCreateParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThreadCreateParams {
    if (json == null) {
        return json;
    }
    return {
        
        'messages': json['messages'] == null ? undefined : ((json['messages'] as Array<any>).map(OpenaiTypesBetaThreadCreateParamsMessageFromJSON)),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'toolResources': json['tool_resources'] == null ? undefined : ToolResourcesInputFromJSON(json['tool_resources']),
    };
}

export function ThreadCreateParamsToJSON(json: any): ThreadCreateParams {
    return ThreadCreateParamsToJSONTyped(json, false);
}

export function ThreadCreateParamsToJSONTyped(value?: ThreadCreateParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'messages': value['messages'] == null ? undefined : ((value['messages'] as Array<any>).map(OpenaiTypesBetaThreadCreateParamsMessageToJSON)),
        'metadata': value['metadata'],
        'tool_resources': ToolResourcesInputToJSON(value['toolResources']),
    };
}

