/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ThreadUpdateParams
 */
export interface ThreadUpdateParams {
    [key: string]: any | any;
    /**
     * 
     * @type {object}
     * @memberof ThreadUpdateParams
     */
    metadata?: object | null;
    /**
     * 
     * @type {object}
     * @memberof ThreadUpdateParams
     */
    toolResources?: object | null;
}

/**
 * Check if a given object implements the ThreadUpdateParams interface.
 */
export function instanceOfThreadUpdateParams(value: object): value is ThreadUpdateParams {
    return true;
}

export function ThreadUpdateParamsFromJSON(json: any): ThreadUpdateParams {
    return ThreadUpdateParamsFromJSONTyped(json, false);
}

export function ThreadUpdateParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThreadUpdateParams {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'toolResources': json['tool_resources'] == null ? undefined : json['tool_resources'],
    };
}

export function ThreadUpdateParamsToJSON(json: any): ThreadUpdateParams {
    return ThreadUpdateParamsToJSONTyped(json, false);
}

export function ThreadUpdateParamsToJSONTyped(value?: ThreadUpdateParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'metadata': value['metadata'],
        'tool_resources': value['toolResources'],
    };
}

