/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ToolResourcesOutput } from './ToolResourcesOutput';
import {
    ToolResourcesOutputFromJSON,
    ToolResourcesOutputFromJSONTyped,
    ToolResourcesOutputToJSON,
    ToolResourcesOutputToJSONTyped,
} from './ToolResourcesOutput';

/**
 * 
 * @export
 * @interface Thread
 */
export interface Thread {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof Thread
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof Thread
     */
    createdAt: number;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof Thread
     */
    metadata?: { [key: string]: string; } | null;
    /**
     * 
     * @type {string}
     * @memberof Thread
     */
    object: ThreadObjectEnum;
    /**
     * 
     * @type {ToolResourcesOutput}
     * @memberof Thread
     */
    toolResources?: ToolResourcesOutput | null;
}


/**
 * @export
 */
export const ThreadObjectEnum = {
    Thread: 'thread'
} as const;
export type ThreadObjectEnum = typeof ThreadObjectEnum[keyof typeof ThreadObjectEnum];


/**
 * Check if a given object implements the Thread interface.
 */
export function instanceOfThread(value: object): value is Thread {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    return true;
}

export function ThreadFromJSON(json: any): Thread {
    return ThreadFromJSONTyped(json, false);
}

export function ThreadFromJSONTyped(json: any, ignoreDiscriminator: boolean): Thread {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'],
        'createdAt': json['created_at'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'object': json['object'],
        'toolResources': json['tool_resources'] == null ? undefined : ToolResourcesOutputFromJSON(json['tool_resources']),
    };
}

export function ThreadToJSON(json: any): Thread {
    return ThreadToJSONTyped(json, false);
}

export function ThreadToJSONTyped(value?: Thread | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'id': value['id'],
        'created_at': value['createdAt'],
        'metadata': value['metadata'],
        'object': value['object'],
        'tool_resources': ToolResourcesOutputToJSON(value['toolResources']),
    };
}

