/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChunkingStrategy1 } from './ChunkingStrategy1';
import {
    ChunkingStrategy1FromJSON,
    ChunkingStrategy1FromJSONTyped,
    ChunkingStrategy1ToJSON,
    ChunkingStrategy1ToJSONTyped,
} from './ChunkingStrategy1';

/**
 * 
 * @export
 * @interface ToolResourcesFileSearchVectorStore
 */
export interface ToolResourcesFileSearchVectorStore {
    /**
     * 
     * @type {ChunkingStrategy1}
     * @memberof ToolResourcesFileSearchVectorStore
     */
    chunkingStrategy?: ChunkingStrategy1;
    /**
     * 
     * @type {Array<string>}
     * @memberof ToolResourcesFileSearchVectorStore
     */
    fileIds?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ToolResourcesFileSearchVectorStore
     */
    metadata?: { [key: string]: string; } | null;
}

/**
 * Check if a given object implements the ToolResourcesFileSearchVectorStore interface.
 */
export function instanceOfToolResourcesFileSearchVectorStore(value: object): value is ToolResourcesFileSearchVectorStore {
    return true;
}

export function ToolResourcesFileSearchVectorStoreFromJSON(json: any): ToolResourcesFileSearchVectorStore {
    return ToolResourcesFileSearchVectorStoreFromJSONTyped(json, false);
}

export function ToolResourcesFileSearchVectorStoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToolResourcesFileSearchVectorStore {
    if (json == null) {
        return json;
    }
    return {
        
        'chunkingStrategy': json['chunking_strategy'] == null ? undefined : ChunkingStrategy1FromJSON(json['chunking_strategy']),
        'fileIds': json['file_ids'] == null ? undefined : json['file_ids'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function ToolResourcesFileSearchVectorStoreToJSON(json: any): ToolResourcesFileSearchVectorStore {
    return ToolResourcesFileSearchVectorStoreToJSONTyped(json, false);
}

export function ToolResourcesFileSearchVectorStoreToJSONTyped(value?: ToolResourcesFileSearchVectorStore | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chunking_strategy': ChunkingStrategy1ToJSON(value['chunkingStrategy']),
        'file_ids': value['fileIds'],
        'metadata': value['metadata'],
    };
}

