/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ToolResourcesFileSearchVectorStoreChunkingStrategyStaticStatic } from './ToolResourcesFileSearchVectorStoreChunkingStrategyStaticStatic';
import {
    ToolResourcesFileSearchVectorStoreChunkingStrategyStaticStaticFromJSON,
    ToolResourcesFileSearchVectorStoreChunkingStrategyStaticStaticFromJSONTyped,
    ToolResourcesFileSearchVectorStoreChunkingStrategyStaticStaticToJSON,
    ToolResourcesFileSearchVectorStoreChunkingStrategyStaticStaticToJSONTyped,
} from './ToolResourcesFileSearchVectorStoreChunkingStrategyStaticStatic';

/**
 * 
 * @export
 * @interface ToolResourcesFileSearchVectorStoreChunkingStrategyStatic
 */
export interface ToolResourcesFileSearchVectorStoreChunkingStrategyStatic {
    /**
     * 
     * @type {ToolResourcesFileSearchVectorStoreChunkingStrategyStaticStatic}
     * @memberof ToolResourcesFileSearchVectorStoreChunkingStrategyStatic
     */
    _static: ToolResourcesFileSearchVectorStoreChunkingStrategyStaticStatic;
    /**
     * 
     * @type {string}
     * @memberof ToolResourcesFileSearchVectorStoreChunkingStrategyStatic
     */
    type: ToolResourcesFileSearchVectorStoreChunkingStrategyStaticTypeEnum;
}


/**
 * @export
 */
export const ToolResourcesFileSearchVectorStoreChunkingStrategyStaticTypeEnum = {
    Static: 'static'
} as const;
export type ToolResourcesFileSearchVectorStoreChunkingStrategyStaticTypeEnum = typeof ToolResourcesFileSearchVectorStoreChunkingStrategyStaticTypeEnum[keyof typeof ToolResourcesFileSearchVectorStoreChunkingStrategyStaticTypeEnum];


/**
 * Check if a given object implements the ToolResourcesFileSearchVectorStoreChunkingStrategyStatic interface.
 */
export function instanceOfToolResourcesFileSearchVectorStoreChunkingStrategyStatic(value: object): value is ToolResourcesFileSearchVectorStoreChunkingStrategyStatic {
    if (!('_static' in value) || value['_static'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ToolResourcesFileSearchVectorStoreChunkingStrategyStaticFromJSON(json: any): ToolResourcesFileSearchVectorStoreChunkingStrategyStatic {
    return ToolResourcesFileSearchVectorStoreChunkingStrategyStaticFromJSONTyped(json, false);
}

export function ToolResourcesFileSearchVectorStoreChunkingStrategyStaticFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToolResourcesFileSearchVectorStoreChunkingStrategyStatic {
    if (json == null) {
        return json;
    }
    return {
        
        '_static': ToolResourcesFileSearchVectorStoreChunkingStrategyStaticStaticFromJSON(json['static']),
        'type': json['type'],
    };
}

export function ToolResourcesFileSearchVectorStoreChunkingStrategyStaticToJSON(json: any): ToolResourcesFileSearchVectorStoreChunkingStrategyStatic {
    return ToolResourcesFileSearchVectorStoreChunkingStrategyStaticToJSONTyped(json, false);
}

export function ToolResourcesFileSearchVectorStoreChunkingStrategyStaticToJSONTyped(value?: ToolResourcesFileSearchVectorStoreChunkingStrategyStatic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'static': ToolResourcesFileSearchVectorStoreChunkingStrategyStaticStaticToJSON(value['_static']),
        'type': value['type'],
    };
}

