/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AssistantToolChoiceFunction } from './AssistantToolChoiceFunction';
import {
    AssistantToolChoiceFunctionFromJSON,
    AssistantToolChoiceFunctionFromJSONTyped,
    AssistantToolChoiceFunctionToJSON,
    AssistantToolChoiceFunctionToJSONTyped,
} from './AssistantToolChoiceFunction';
import type { AssistantToolChoice } from './AssistantToolChoice';
import {
    AssistantToolChoiceFromJSON,
    AssistantToolChoiceFromJSONTyped,
    AssistantToolChoiceToJSON,
    AssistantToolChoiceToJSONTyped,
} from './AssistantToolChoice';

/**
 * 
 * @export
 * @interface ToolChoice
 */
export interface ToolChoice {
    /**
     * 
     * @type {string}
     * @memberof ToolChoice
     */
    type: ToolChoiceTypeEnum;
    /**
     * 
     * @type {AssistantToolChoiceFunction}
     * @memberof ToolChoice
     */
    _function?: AssistantToolChoiceFunction;
}


/**
 * @export
 */
export const ToolChoiceTypeEnum = {
    Function: 'function',
    CodeInterpreter: 'code_interpreter',
    FileSearch: 'file_search'
} as const;
export type ToolChoiceTypeEnum = typeof ToolChoiceTypeEnum[keyof typeof ToolChoiceTypeEnum];


/**
 * Check if a given object implements the ToolChoice interface.
 */
export function instanceOfToolChoice(value: object): value is ToolChoice {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ToolChoiceFromJSON(json: any): ToolChoice {
    return ToolChoiceFromJSONTyped(json, false);
}

export function ToolChoiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToolChoice {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        '_function': json['function'] == null ? undefined : AssistantToolChoiceFunctionFromJSON(json['function']),
    };
}

export function ToolChoiceToJSON(json: any): ToolChoice {
    return ToolChoiceToJSONTyped(json, false);
}

export function ToolChoiceToJSONTyped(value?: ToolChoice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'function': AssistantToolChoiceFunctionToJSON(value['_function']),
    };
}

