/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ToolResourcesFileSearchVectorStore } from './ToolResourcesFileSearchVectorStore';
import {
    ToolResourcesFileSearchVectorStoreFromJSON,
    ToolResourcesFileSearchVectorStoreFromJSONTyped,
    ToolResourcesFileSearchVectorStoreToJSON,
    ToolResourcesFileSearchVectorStoreToJSONTyped,
} from './ToolResourcesFileSearchVectorStore';

/**
 * 
 * @export
 * @interface ToolResourcesFileSearchInput
 */
export interface ToolResourcesFileSearchInput {
    /**
     * 
     * @type {Array<string>}
     * @memberof ToolResourcesFileSearchInput
     */
    vectorStoreIds?: Array<string>;
    /**
     * 
     * @type {Array<ToolResourcesFileSearchVectorStore>}
     * @memberof ToolResourcesFileSearchInput
     */
    vectorStores?: Array<ToolResourcesFileSearchVectorStore>;
}

/**
 * Check if a given object implements the ToolResourcesFileSearchInput interface.
 */
export function instanceOfToolResourcesFileSearchInput(value: object): value is ToolResourcesFileSearchInput {
    return true;
}

export function ToolResourcesFileSearchInputFromJSON(json: any): ToolResourcesFileSearchInput {
    return ToolResourcesFileSearchInputFromJSONTyped(json, false);
}

export function ToolResourcesFileSearchInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToolResourcesFileSearchInput {
    if (json == null) {
        return json;
    }
    return {
        
        'vectorStoreIds': json['vector_store_ids'] == null ? undefined : json['vector_store_ids'],
        'vectorStores': json['vector_stores'] == null ? undefined : ((json['vector_stores'] as Array<any>).map(ToolResourcesFileSearchVectorStoreFromJSON)),
    };
}

export function ToolResourcesFileSearchInputToJSON(json: any): ToolResourcesFileSearchInput {
    return ToolResourcesFileSearchInputToJSONTyped(json, false);
}

export function ToolResourcesFileSearchInputToJSONTyped(value?: ToolResourcesFileSearchInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'vector_store_ids': value['vectorStoreIds'],
        'vector_stores': value['vectorStores'] == null ? undefined : ((value['vectorStores'] as Array<any>).map(ToolResourcesFileSearchVectorStoreToJSON)),
    };
}

