/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ToolResourcesFileSearchVectorStoreChunkingStrategyAuto
 */
export interface ToolResourcesFileSearchVectorStoreChunkingStrategyAuto {
    /**
     * 
     * @type {string}
     * @memberof ToolResourcesFileSearchVectorStoreChunkingStrategyAuto
     */
    type: ToolResourcesFileSearchVectorStoreChunkingStrategyAutoTypeEnum;
}


/**
 * @export
 */
export const ToolResourcesFileSearchVectorStoreChunkingStrategyAutoTypeEnum = {
    Auto: 'auto'
} as const;
export type ToolResourcesFileSearchVectorStoreChunkingStrategyAutoTypeEnum = typeof ToolResourcesFileSearchVectorStoreChunkingStrategyAutoTypeEnum[keyof typeof ToolResourcesFileSearchVectorStoreChunkingStrategyAutoTypeEnum];


/**
 * Check if a given object implements the ToolResourcesFileSearchVectorStoreChunkingStrategyAuto interface.
 */
export function instanceOfToolResourcesFileSearchVectorStoreChunkingStrategyAuto(value: object): value is ToolResourcesFileSearchVectorStoreChunkingStrategyAuto {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ToolResourcesFileSearchVectorStoreChunkingStrategyAutoFromJSON(json: any): ToolResourcesFileSearchVectorStoreChunkingStrategyAuto {
    return ToolResourcesFileSearchVectorStoreChunkingStrategyAutoFromJSONTyped(json, false);
}

export function ToolResourcesFileSearchVectorStoreChunkingStrategyAutoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToolResourcesFileSearchVectorStoreChunkingStrategyAuto {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
    };
}

export function ToolResourcesFileSearchVectorStoreChunkingStrategyAutoToJSON(json: any): ToolResourcesFileSearchVectorStoreChunkingStrategyAuto {
    return ToolResourcesFileSearchVectorStoreChunkingStrategyAutoToJSONTyped(json, false);
}

export function ToolResourcesFileSearchVectorStoreChunkingStrategyAutoToJSONTyped(value?: ToolResourcesFileSearchVectorStoreChunkingStrategyAuto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
    };
}

