/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ToolResourcesFileSearchVectorStoreChunkingStrategyStaticStatic
 */
export interface ToolResourcesFileSearchVectorStoreChunkingStrategyStaticStatic {
    /**
     * 
     * @type {number}
     * @memberof ToolResourcesFileSearchVectorStoreChunkingStrategyStaticStatic
     */
    chunkOverlapTokens: number;
    /**
     * 
     * @type {number}
     * @memberof ToolResourcesFileSearchVectorStoreChunkingStrategyStaticStatic
     */
    maxChunkSizeTokens: number;
}

/**
 * Check if a given object implements the ToolResourcesFileSearchVectorStoreChunkingStrategyStaticStatic interface.
 */
export function instanceOfToolResourcesFileSearchVectorStoreChunkingStrategyStaticStatic(value: object): value is ToolResourcesFileSearchVectorStoreChunkingStrategyStaticStatic {
    if (!('chunkOverlapTokens' in value) || value['chunkOverlapTokens'] === undefined) return false;
    if (!('maxChunkSizeTokens' in value) || value['maxChunkSizeTokens'] === undefined) return false;
    return true;
}

export function ToolResourcesFileSearchVectorStoreChunkingStrategyStaticStaticFromJSON(json: any): ToolResourcesFileSearchVectorStoreChunkingStrategyStaticStatic {
    return ToolResourcesFileSearchVectorStoreChunkingStrategyStaticStaticFromJSONTyped(json, false);
}

export function ToolResourcesFileSearchVectorStoreChunkingStrategyStaticStaticFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToolResourcesFileSearchVectorStoreChunkingStrategyStaticStatic {
    if (json == null) {
        return json;
    }
    return {
        
        'chunkOverlapTokens': json['chunk_overlap_tokens'],
        'maxChunkSizeTokens': json['max_chunk_size_tokens'],
    };
}

export function ToolResourcesFileSearchVectorStoreChunkingStrategyStaticStaticToJSON(json: any): ToolResourcesFileSearchVectorStoreChunkingStrategyStaticStatic {
    return ToolResourcesFileSearchVectorStoreChunkingStrategyStaticStaticToJSONTyped(json, false);
}

export function ToolResourcesFileSearchVectorStoreChunkingStrategyStaticStaticToJSONTyped(value?: ToolResourcesFileSearchVectorStoreChunkingStrategyStaticStatic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chunk_overlap_tokens': value['chunkOverlapTokens'],
        'max_chunk_size_tokens': value['maxChunkSizeTokens'],
    };
}

