/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ToolResourcesFileSearchOutput
 */
export interface ToolResourcesFileSearchOutput {
    [key: string]: any | any;
    /**
     * 
     * @type {Array<string>}
     * @memberof ToolResourcesFileSearchOutput
     */
    vectorStoreIds?: Array<string> | null;
}

/**
 * Check if a given object implements the ToolResourcesFileSearchOutput interface.
 */
export function instanceOfToolResourcesFileSearchOutput(value: object): value is ToolResourcesFileSearchOutput {
    return true;
}

export function ToolResourcesFileSearchOutputFromJSON(json: any): ToolResourcesFileSearchOutput {
    return ToolResourcesFileSearchOutputFromJSONTyped(json, false);
}

export function ToolResourcesFileSearchOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToolResourcesFileSearchOutput {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'vectorStoreIds': json['vector_store_ids'] == null ? undefined : json['vector_store_ids'],
    };
}

export function ToolResourcesFileSearchOutputToJSON(json: any): ToolResourcesFileSearchOutput {
    return ToolResourcesFileSearchOutputToJSONTyped(json, false);
}

export function ToolResourcesFileSearchOutputToJSONTyped(value?: ToolResourcesFileSearchOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'vector_store_ids': value['vectorStoreIds'],
    };
}

