/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TruncationStrategyInput
 */
export interface TruncationStrategyInput {
    /**
     * 
     * @type {string}
     * @memberof TruncationStrategyInput
     */
    type: TruncationStrategyInputTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof TruncationStrategyInput
     */
    lastMessages?: number | null;
}


/**
 * @export
 */
export const TruncationStrategyInputTypeEnum = {
    Auto: 'auto',
    LastMessages: 'last_messages'
} as const;
export type TruncationStrategyInputTypeEnum = typeof TruncationStrategyInputTypeEnum[keyof typeof TruncationStrategyInputTypeEnum];


/**
 * Check if a given object implements the TruncationStrategyInput interface.
 */
export function instanceOfTruncationStrategyInput(value: object): value is TruncationStrategyInput {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function TruncationStrategyInputFromJSON(json: any): TruncationStrategyInput {
    return TruncationStrategyInputFromJSONTyped(json, false);
}

export function TruncationStrategyInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): TruncationStrategyInput {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'lastMessages': json['last_messages'] == null ? undefined : json['last_messages'],
    };
}

export function TruncationStrategyInputToJSON(json: any): TruncationStrategyInput {
    return TruncationStrategyInputToJSONTyped(json, false);
}

export function TruncationStrategyInputToJSONTyped(value?: TruncationStrategyInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'last_messages': value['lastMessages'],
    };
}

