/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TruncationStrategyOutput
 */
export interface TruncationStrategyOutput {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof TruncationStrategyOutput
     */
    type: TruncationStrategyOutputTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof TruncationStrategyOutput
     */
    lastMessages?: number | null;
}


/**
 * @export
 */
export const TruncationStrategyOutputTypeEnum = {
    Auto: 'auto',
    LastMessages: 'last_messages'
} as const;
export type TruncationStrategyOutputTypeEnum = typeof TruncationStrategyOutputTypeEnum[keyof typeof TruncationStrategyOutputTypeEnum];


/**
 * Check if a given object implements the TruncationStrategyOutput interface.
 */
export function instanceOfTruncationStrategyOutput(value: object): value is TruncationStrategyOutput {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function TruncationStrategyOutputFromJSON(json: any): TruncationStrategyOutput {
    return TruncationStrategyOutputFromJSONTyped(json, false);
}

export function TruncationStrategyOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): TruncationStrategyOutput {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'type': json['type'],
        'lastMessages': json['last_messages'] == null ? undefined : json['last_messages'],
    };
}

export function TruncationStrategyOutputToJSON(json: any): TruncationStrategyOutput {
    return TruncationStrategyOutputToJSONTyped(json, false);
}

export function TruncationStrategyOutputToJSONTyped(value?: TruncationStrategyOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'type': value['type'],
        'last_messages': value['lastMessages'],
    };
}

