/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Usage
 */
export interface Usage {
    [key: string]: any | any;
    /**
     * 
     * @type {number}
     * @memberof Usage
     */
    completionTokens: number;
    /**
     * 
     * @type {number}
     * @memberof Usage
     */
    promptTokens: number;
    /**
     * 
     * @type {number}
     * @memberof Usage
     */
    totalTokens: number;
}

/**
 * Check if a given object implements the Usage interface.
 */
export function instanceOfUsage(value: object): value is Usage {
    if (!('completionTokens' in value) || value['completionTokens'] === undefined) return false;
    if (!('promptTokens' in value) || value['promptTokens'] === undefined) return false;
    if (!('totalTokens' in value) || value['totalTokens'] === undefined) return false;
    return true;
}

export function UsageFromJSON(json: any): Usage {
    return UsageFromJSONTyped(json, false);
}

export function UsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): Usage {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'completionTokens': json['completion_tokens'],
        'promptTokens': json['prompt_tokens'],
        'totalTokens': json['total_tokens'],
    };
}

export function UsageToJSON(json: any): Usage {
    return UsageToJSONTyped(json, false);
}

export function UsageToJSONTyped(value?: Usage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'completion_tokens': value['completionTokens'],
        'prompt_tokens': value['promptTokens'],
        'total_tokens': value['totalTokens'],
    };
}

