/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request model for creating a vector store file.
 * @export
 * @interface VectorStoreFileCreate
 */
export interface VectorStoreFileCreate {
    /**
     * 
     * @type {string}
     * @memberof VectorStoreFileCreate
     */
    fileId: string;
}

/**
 * Check if a given object implements the VectorStoreFileCreate interface.
 */
export function instanceOfVectorStoreFileCreate(value: object): value is VectorStoreFileCreate {
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    return true;
}

export function VectorStoreFileCreateFromJSON(json: any): VectorStoreFileCreate {
    return VectorStoreFileCreateFromJSONTyped(json, false);
}

export function VectorStoreFileCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): VectorStoreFileCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'fileId': json['file_id'],
    };
}

export function VectorStoreFileCreateToJSON(json: any): VectorStoreFileCreate {
    return VectorStoreFileCreateToJSONTyped(json, false);
}

export function VectorStoreFileCreateToJSONTyped(value?: VectorStoreFileCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'file_id': value['fileId'],
    };
}

