/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileCounts } from './FileCounts';
import {
    FileCountsFromJSON,
    FileCountsFromJSONTyped,
    FileCountsToJSON,
    FileCountsToJSONTyped,
} from './FileCounts';
import type { ExpiresAfterOutput } from './ExpiresAfterOutput';
import {
    ExpiresAfterOutputFromJSON,
    ExpiresAfterOutputFromJSONTyped,
    ExpiresAfterOutputToJSON,
    ExpiresAfterOutputToJSONTyped,
} from './ExpiresAfterOutput';

/**
 * 
 * @export
 * @interface VectorStore
 */
export interface VectorStore {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof VectorStore
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof VectorStore
     */
    createdAt: number;
    /**
     * 
     * @type {FileCounts}
     * @memberof VectorStore
     */
    fileCounts: FileCounts;
    /**
     * 
     * @type {number}
     * @memberof VectorStore
     */
    lastActiveAt?: number | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof VectorStore
     */
    metadata?: { [key: string]: string; } | null;
    /**
     * 
     * @type {string}
     * @memberof VectorStore
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof VectorStore
     */
    object: VectorStoreObjectEnum;
    /**
     * 
     * @type {string}
     * @memberof VectorStore
     */
    status: VectorStoreStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof VectorStore
     */
    usageBytes: number;
    /**
     * 
     * @type {ExpiresAfterOutput}
     * @memberof VectorStore
     */
    expiresAfter?: ExpiresAfterOutput | null;
    /**
     * 
     * @type {number}
     * @memberof VectorStore
     */
    expiresAt?: number | null;
}


/**
 * @export
 */
export const VectorStoreObjectEnum = {
    VectorStore: 'vector_store'
} as const;
export type VectorStoreObjectEnum = typeof VectorStoreObjectEnum[keyof typeof VectorStoreObjectEnum];

/**
 * @export
 */
export const VectorStoreStatusEnum = {
    Expired: 'expired',
    InProgress: 'in_progress',
    Completed: 'completed'
} as const;
export type VectorStoreStatusEnum = typeof VectorStoreStatusEnum[keyof typeof VectorStoreStatusEnum];


/**
 * Check if a given object implements the VectorStore interface.
 */
export function instanceOfVectorStore(value: object): value is VectorStore {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('fileCounts' in value) || value['fileCounts'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('usageBytes' in value) || value['usageBytes'] === undefined) return false;
    return true;
}

export function VectorStoreFromJSON(json: any): VectorStore {
    return VectorStoreFromJSONTyped(json, false);
}

export function VectorStoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): VectorStore {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'],
        'createdAt': json['created_at'],
        'fileCounts': FileCountsFromJSON(json['file_counts']),
        'lastActiveAt': json['last_active_at'] == null ? undefined : json['last_active_at'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'name': json['name'],
        'object': json['object'],
        'status': json['status'],
        'usageBytes': json['usage_bytes'],
        'expiresAfter': json['expires_after'] == null ? undefined : ExpiresAfterOutputFromJSON(json['expires_after']),
        'expiresAt': json['expires_at'] == null ? undefined : json['expires_at'],
    };
}

export function VectorStoreToJSON(json: any): VectorStore {
    return VectorStoreToJSONTyped(json, false);
}

export function VectorStoreToJSONTyped(value?: VectorStore | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'id': value['id'],
        'created_at': value['createdAt'],
        'file_counts': FileCountsToJSON(value['fileCounts']),
        'last_active_at': value['lastActiveAt'],
        'metadata': value['metadata'],
        'name': value['name'],
        'object': value['object'],
        'status': value['status'],
        'usage_bytes': value['usageBytes'],
        'expires_after': ExpiresAfterOutputToJSON(value['expiresAfter']),
        'expires_at': value['expiresAt'],
    };
}

