name: Artifact Upload
on:
  pull_request:
    branches: [develop]
jobs:
  create-artifact:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Build extension for testnet
        run: NEAR_MAINNET=testnet pnpm build
      - name: Upload a Build Artifact
        id: upload-testnet
        uses: actions/upload-artifact@v3.1.2
        with:
          name: mutable-web-extension-${{ github.head_ref }}-testnet
          path: apps/extension/build/
          if-no-files-found: error
      - name: Build extension for mainnet
        run: NEAR_MAINNET=mainnet pnpm build
      - name: Upload a Build Artifact
        id: upload-mainnet
        uses: actions/upload-artifact@v3.1.2
        with:
          name: mutable-web-extension-${{ github.head_ref }}-mainnet
          path: apps/extension/build/
          if-no-files-found: error